---
permalink: a1k/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a1k, how to recable the system, how to reassign disks 
summary: 将存储资源的控制权归还给替代控制器、以便AFF A1K系统可以恢复正常运行。 
---
= 交还控制器- AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将存储资源的控制权归还给替代控制器、以便AFF A1K系统可以恢复正常运行。恢复过程根据系统使用的加密类型而有所不同：无加密或板载密钥管理器 (OKM) 加密。

[role="tabbed-block"]
====
.无加密
--
通过交还存储使受损控制器恢复正常运行。

.步骤
. 在Loader提示符处，输入 `boot_ontap`。
. 当控制台消息停止时、按<enter>。
+
** 如果看到_login"提示符、请转到本节末尾的下一步。
** 如果您看到_wawaigif for nifecback_、请按<enter>键、登录到配对节点、然后转到本节末尾的下一步。


. 通过交还存储使受损控制器恢复正常运行： `storage failover giveback -ofnode _impaired_node_name_`
. 如果已禁用自动交还、请重新启用它： `storage failover modify -node local -auto-giveback _true_`
. 如果启用了AutoSupport、则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`


--
.板载加密(OKM)
--
重置板载加密并使控制器恢复正常运行。

.步骤
. 在Loader提示符处，输入 `boot_ontap maint`。
. 从Loader提示符处启动到ONTAP菜单 `boot_ontap menu`、然后选择选项10。
. 输入OKM密码短语。
+

NOTE: 系统会两次提示您输入密码短语。

. 出现提示时、输入备份密钥数据。
. 在启动菜单中、输入选项 `1`进行正常启动。
. 当显示_wawawaite_for vig-back_时、按<enter>键。
. 将控制台缆线移至配对节点并以身份登录 `admin`。
. 仅交还CFO聚合(根聚合)： `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** 如果遇到错误，请联系 https://support.netapp.com["NetApp 支持"]。


. 在恢复报告完成后等待5分钟，然后检查故障转移状态和恢复状态： `storage failover show`和 `storage failover show-giveback`。
. 同步并验证密钥状态：
+
.. 将控制台缆线移回替代控制器。
.. 同步缺少的密钥： `security key-manager onboard sync`
+

NOTE: 系统会提示您为此集群输入集群范围的OKM密码短语。

.. 验证密钥状态： `security key-manager key query -restored _false_`
+
正确同步后、输出不应显示任何结果。

+
如果输出显示结果(系统内部密钥表中不存在的密钥ID)，请与联系。 https://support.netapp.com["NetApp 支持"]



. 通过交还存储使受损控制器恢复正常运行： `storage failover giveback -ofnode _impaired_node_name_`
. 如果已禁用自动交还、请重新启用它： `storage failover modify -node local -auto-giveback _true_`
. 如果启用了AutoSupport、则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.下一步是什么？
在将存储资源的所有权转移回替代控制器后、您需要执行相关link:controller-replace-restore-system-rma.html["完成控制器更换"]步骤。
