---
permalink: a1k/install-prepare.html 
sidebar: sidebar 
keywords: aff a1k, prepare installation 
summary: 准备安装AFF A1K平台。 
---
= 准备安装- AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
准备安装AFF A1K存储系统、方法是准备好站点、打开包装箱包装、将包装箱中的物品与装箱单进行比较、并注册系统以获得支持权益。



== 第1步：准备站点

要安装存储系统、请确保您计划使用的站点和机柜或机架符合您的配置规格。

.步骤
. 使用 https://hwu.netapp.com["NetApp Hardware Universe"^]确认您的站点满足存储系统的环境和电气要求。
. 确保为存储系统、磁盘架和任何交换机提供足够的机柜或机架空间：
+
** HA配置中的4U
** 每个NS224存储架占用2U空间




. 安装所需的任何网络交换机。
+
有关安装说明和兼容性信息、请参见 https://docs.netapp.com/us-en/ontap-systems-switches/index.html["交换机文档"^] link:https://hwu.netapp.com["NetApp Hardware Universe"^] 。





== 第2步：打开包装箱

确保存储系统的站点和计划使用的机柜或机架符合所需规格后、打开所有包装箱的包装并将物品与装箱单上的物品进行比较。

.步骤
. 小心地打开所有箱子、并有序地布置物品。
. 将您已解包装的内容与装箱单上的列表进行比较。
+

NOTE: 您可以通过扫描装运箱侧面的QR码来获取装箱单。

+
以下项目是您可能会在框中看到的一些内容。

+
确保包装箱中的所有物品均与装箱单上的列表匹配。如果存在任何差异、请记下这些差异以供进一步操作。

+
[cols="12,9,4"]
|===


| * 硬件 * | *电缆* |  


 a| 
** 挡板
** 缆线管理设备
** 存储系统
** 带说明的导轨套件(可选)
** 存储架(如果您订购了额外的存储)

 a| 
** 管理以太网缆线(RJ-45缆线)
** 网络缆线
** 电源线
** 存储缆线(如果您订购了额外的存储)
** USB－C串行控制台电缆

|  
|===




== 第3步：注册存储系统

在确保您的站点满足存储系统规格的要求并确认您已订购所有部件后、您应注册存储系统。

.步骤
. 找到每个正在安装的控制器的系统序列号 (SSN)。
+
您可以在以下位置找到序列号：

+
** 在装箱单上
** 在您的确认电子邮件中
** 在每个控制器的系统管理模块上


+
image::../media/drw_ssn_label.svg[显示编号位置的系统序列号示例]

. 转到。 http://mysupport.netapp.com/["NetApp 支持站点"^]
. 确定是否需要注册存储系统：
+
[cols="1a,2a"]
|===
| 如果您是 ... | 请按照以下步骤操作 ... 


 a| 
现有 NetApp 客户
 a| 
.. 使用您的用户名和密码登录。
.. 选择*系统*>*我的系统*。
.. 确认新序列号已列出。
.. 如果不是，请按照适用于新 NetApp 客户的说明进行操作。




 a| 
NetApp 新客户
 a| 
.. 单击 * 立即注册 * ，然后创建帐户。
.. 选择*系统*>*注册系统*。
.. 输入存储系统的序列号和请求的详细信息。


注册获得批准后，您可以下载所需的任何软件。审批过程可能需要长达 24 小时。

|===


.下一步是什么？
准备好安装AFF A1K硬件后，您可以link:install-hardware.html["安装AFF A1K存储系统的硬件"]。
