---
permalink: a1k/maintain-overview.html 
sidebar: sidebar 
keywords: aff a1k maintenance, maintenance, repairing a1k, repairing aff a1k, replace aff a1k components, replace aff a1k components 
summary: 维护AFF A1K硬件 
---
= 维护AFF A1K硬件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可能需要对硬件执行维护过程。本节将介绍维护AFF A1K系统组件的特定过程。

本节中的过程假定AFF A1K系统已部署为ONTAP环境中的存储节点。



== 系统组件

对于AFF A1K存储系统、您可以对以下组件执行维护过程。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["启动介质"]
 a| 
启动介质用于存储系统在启动时使用的一组主和二级ONTAP映像文件。



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主板，固件和软件组成。它控制驱动器并运行ONTAP操作系统软件。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
双列直插式内存模块(DIMM)是一种计算机内存。安装它们是为了向控制器主板添加系统内存。



 a| 
link:fan-replace.html["风扇"]
 a| 
风扇冷却控制器。



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
NVRAM (非易失性随机存取存储器)是一个模块、可使控制器在系统断电时保护和保存传输中的数据。系统ID位于NVRAM模块中。更换后、控制器将从更换的NVRAM模块获取新的系统ID。



 a| 
link:nvdimm-battery-replace.html["NV电池"]
 a| 
NV电池负责在断电后将传输中的数据转存到闪存时为NVRAM模块供电。



 a| 
link:io-module-overview.html["I/O 模块"]
 a| 
I/O模块(输入/输出模块)是一个硬件组件、充当控制器与需要与控制器交换数据的各种设备或系统之间的媒介。



 a| 
link:power-supply-replace.html["电源"]
 a| 
电源设备在控制器中提供冗余电源。



 a| 
link:rtc-battery-replace.html["实时时钟电池"]
 a| 
实时时钟电池可在断电时保留系统日期和时间信息。



 a| 
link:system-management-replace.html["系统管理模块"]
 a| 
系统管理模块提供控制器与控制台或笔记本电脑之间的接口、用于控制器或系统维护。系统管理模块包含启动介质并存储系统序列号(SSN)。

|===