---
permalink: a400/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff a400, aff, a400, component, system, function, properly, contact, technical, support, replace, chassis, shut, down, controller, replacing, remove, module, fan, equipment, rack, cabinet, ha, state, switch, back, aggregate, two-node, metrocluster, configuration, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, verify and set the ha state of the chassis, switch back aggregates in a two-node metrocluster configuration, complete the replacement process 
summary: 将受损机箱中的风扇，硬盘驱动器和控制器模块或模块移至新机箱，然后将受损机箱从设备机架或系统机柜中更换为与受损机箱型号相同的新机箱。 
---
= 更换硬件— AFF A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将风扇、硬盘驱动器和控制器模块从受损机箱移至新机箱、然后将受损机箱更换为与受损机箱型号相同的新机箱。



== 第 1 步：卸下控制器模块

要更换机箱，必须从旧机箱中卸下控制器模块。

. 如果您尚未接地，请正确接地。
. 释放电源线固定器，然后从电源中拔下缆线。
. 松开将缆线绑在缆线管理设备上的钩环带，然后从控制器模块上拔下系统缆线和 SFP （如果需要），并跟踪缆线的连接位置。
+
将缆线留在缆线管理设备中，以便在重新安装缆线管理设备时，缆线排列有序。

. 从控制器模块的左右两侧卸下缆线管理设备并将其放在一旁。
. 向下按两个锁定闩锁，然后同时向下旋转两个闩锁。
+
此控制器模块会从机箱中略微移出。

. 将控制器模块滑出机箱。
+
将控制器模块滑出机箱时，请确保您支持控制器模块的底部。

. 将控制器模块放在安全的位置，并对机箱中的另一个控制器模块重复这些步骤。




== 第 2 步：移动风扇

要在更换机箱时将风扇模块移至更换机箱，您必须执行一系列特定的任务。

. 如果您尚未接地，请正确接地。
. 如有必要，请用两只手抓住挡板每一侧的开口，然后将其拉向您，直到挡板从机箱框架上的球形螺柱上松开，从而卸下挡板。
. 向下按风扇模块凸轮把手上的释放闩锁，然后向下旋转凸轮把手。
+
风扇模块会从机箱中移出一点。

. 将风扇模块从机箱中竖直拉出，确保用您的空闲手托住该模块，使其不会从机箱中摆出。
+

CAUTION: 风扇模块较短。请始终用您的空闲手托住风扇模块的底部，以免其突然从机箱中脱离并造成您的人身伤害。

. 将风扇模块放在一旁。
. 对其余所有风扇模块重复上述步骤。
. 将风扇模块与开口对齐，然后将其滑入机箱，从而将其插入更换机箱。
. 用力推动风扇模块凸轮把手，使其完全固定到机箱中。
+
风扇模块完全就位后，凸轮把手会略微升高。

. 将凸轮把手向上旋转到其闭合位置，确保凸轮把手释放闩锁卡入到锁定位置。
. 对其余风扇模块重复上述步骤。




== 第 3 步：从设备机架或系统机柜中更换机箱

您必须先从设备机架或系统机柜中卸下现有机箱，然后才能安装替代机箱。

. 从机箱安装点卸下螺钉。
. 两个人将旧机箱滑出系统机柜或设备机架中的机架导轨，然后放好备用。
. 如果您尚未接地，请正确接地。
. 由两个人将更换机箱安装到设备机架或系统机架中，方法是将机箱安装到系统机柜或设备机架中的机架导轨上。
. 将机箱完全滑入设备机架或系统机柜中。
. 使用从旧机箱中卸下的螺钉将机箱前部固定到设备机架或系统机柜。
. 如果尚未安装挡板，请安装挡板。




== 第 4 步：安装控制器模块

将控制器模块安装到新机箱后、需要启动它。

对于在同一机箱中具有两个控制器模块的 HA 对，安装控制器模块的顺序尤为重要，因为一旦将其完全装入机箱，它就会尝试重新启动。

. 将控制器模块的末端与机箱中的开口对齐，然后将控制器模块轻轻推入系统的一半。
+

NOTE: 请勿将控制器模块完全插入机箱中，除非系统指示您这样做。

. 将控制台重新连接到控制器模块，然后重新连接管理端口。
. 完成控制器模块的安装：
+
.. 将电源线插入电源，重新安装电源线锁定环，然后将电源连接到电源。
.. 使用锁定闩锁将控制器模块牢牢推入机箱，直到锁定闩锁开始上升。
+

NOTE: 将控制器模块滑入机箱时，请勿用力过大，以免损坏连接器。

.. 将锁定闩锁向上旋转，使其倾斜以清除锁定销，将控制器模块完全推入机箱中，然后将锁定闩锁降至锁定位置。
+
控制器模块一旦完全固定在机箱中，就会开始启动。准备中断启动过程。

.. 如果尚未重新安装缆线管理设备，请重新安装该设备。
.. 按 `Ctrl-C` 中断正常启动过程并启动到 LOADER 。
+

NOTE: 如果系统停留在启动菜单处，请选择启动到 LOADER 选项。

.. 在 LOADER 提示符处，输入 `bye` 以重新初始化 PCIe 卡和其他组件。
.. 按 `Ctrl-C` 中断启动过程并启动到加载程序提示符。
+
如果系统停留在启动菜单处，请选择启动到 LOADER 选项。



. 重复上述步骤，将第二个控制器安装到新机箱中。

