---
permalink: a70-90/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff a70, aff a90, move hardware components, replace the chassis 
summary: 将硬盘驱动器和控制器模块从受损机箱移至新机箱、然后将受损机箱从设备机架或系统机柜更换为与受损机箱型号相同的新机箱。 
---
= 更换机箱- AFF A70和AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将硬盘驱动器和控制器模块从受损机箱移至新机箱、然后将受损机箱更换为与受损机箱型号相同的新机箱。



== 第 1 步：卸下控制器模块

在更换控制器模块或更换控制器模块内的组件时，您必须从机箱中卸下控制器模块。

. 在机箱正面、用拇指用力推入每个驱动器、直到您感觉到有一定的停机。这样可确保驱动器牢固地固定在机箱中板上。
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[安装磁盘驱动器]

. 检查受损控制器模块背面插槽4/5中的琥珀色NVRAM状态指示灯是否熄灭。查找NV图标。
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[NVRAM警示和状态LED位置图]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["标注编号1、宽度=30制"]
 a| 
NVRAM 状态 LED



 a| 
image:../media/legend_icon_02.svg["标注编号1、宽度=30制"]
 a| 
NVRAM警示LED

|===
+

NOTE: 如果NVRAM状态LED闪烁、则可能表示控制器模块未被接管或正常暂停(未提交的数据)。如果受损控制器模块未被配对控制器模块成功接管、请先联系、 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"] 然后再继续此过程。

+
受损控制器模块上的NVRAM状态LED的一般行为如下：

+
** 当控制器模块断电、存储系统处于"正在等待恢复"状态、或者控制器模块未被正确接管或暂停(未提交的数据)时、NVRAM状态LED会闪烁。
** 从机箱中卸下控制器模块后、NVRAM状态LED会闪烁、这可能意味着控制器模块未被接管或暂停(未提交的数据)。确认此控制器模块已被配对控制器模块完全接管，或者受损控制器模块显示 `waiting for giveback`。然后、可以忽略闪烁的LED指示灯(并且可以从机箱中卸下控制器模块)。


. 如果您尚未接地，请正确接地。
. 从控制器模块电源(PSU)上拔下控制器模块电源线。
+

NOTE: 如果您的系统使用直流电源、请断开电源块与PSU的连接。

. 从控制器模块拔下系统缆线以及SFP和QSFP模块(如果需要)、并记录缆线的连接位置。
+
将缆线留在缆线管理设备中，以便在重新安装缆线管理设备时，缆线排列有序。

. 从控制器模块中卸下缆线管理设备。
. 向下按两个锁定闩锁，然后同时向下旋转两个闩锁。
+
此控制器模块会从机箱中略微移出。

+
image::../media/drw_a70-90_pcm_remove_replace_ieops-1365.svg[控制器删除图形]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["标注编号1、宽度=30制"]
| A锁定闩锁 


 a| 
image:../media/legend_icon_02.svg["标注编号2、宽度=30制"]
 a| 
锁定销

|===
. 将控制器模块滑出机箱、然后将其放在平稳的表面上。
+
将控制器模块滑出机箱时，请确保您支持控制器模块的底部。

. 对机箱中的另一个控制器模块重复上述步骤。




== 第 2 步：将驱动器移至新机箱

您需要将驱动器从旧机箱中的每个托架开口移至新机箱中的同一托架开口。

. 从系统正面轻轻卸下挡板。
. 删除驱动器：
+
.. 按下 LED 下方托架正面顶部的释放按钮。
.. 将凸轮把手拉至完全打开位置，以使驱动器从中板中取出，然后将驱动器轻轻滑出机箱。
+
驱动器应与机箱分离，以便滑出机箱。

+

NOTE: 卸下驱动器时，请始终用双手支撑其重量。

+

NOTE: 驱动器很脆弱。尽可能少地对其进行处理，以防止对其造成损坏。



. 跟踪每个驱动器的驱动器托架、并将驱动器放在无静电的手推车或桌子上。




== 第3步：从设备机架或系统机柜中更换机箱

您必须先从设备机架或系统机柜中卸下现有机箱，然后才能安装替代机箱。

. 从机箱安装点卸下螺钉。
. 两个人将旧机箱滑出系统机柜或设备机架中的机架导轨，然后放好备用。
. 由两个人将更换机箱安装到设备机架或系统机架中，方法是将机箱安装到系统机柜或设备机架中的机架导轨上。
. 将机箱完全滑入设备机架或系统机柜中。
. 使用从旧机箱中卸下的螺钉将机箱前部固定到设备机架或系统机柜。
. 将旧机箱中的驱动器安装到更换机箱中：
+
.. 将旧机箱中的驱动器与新机箱中的相同托架开口对齐。


. 将驱动器轻轻推入机箱，直至其完全移动。
+
凸轮把手啮合并开始向上旋转。

+
.. 将驱动器的其余部分用力推入机箱、然后向上推凸轮把手并顶住驱动器托架以锁定凸轮把手。
+
Be sure to close the cam handle slowly so that it aligns correctly with the front of the drive carrier.安全时，它会发出卡嗒声。

.. 对系统中的其余驱动器重复此过程。


. 如果尚未安装挡板，请安装挡板。




== 步骤4：重新安装控制器模块

重新安装控制器模块并重新启动。

. 将空气管道向下旋转到可以移动的位置、确保空气管道完全关闭。
+
它必须与控制器模块金属板平齐。

. 将控制器模块的末端与机箱中的开口对齐，然后将控制器模块轻轻推入系统的一半。
+

NOTE: 请勿将控制器模块完全插入机箱中，除非系统指示您这样做。

. 根据需要重新对系统进行布线。
+
如果您删除了收发器(QSFP或SFP)、请记得在使用光缆时重新安装它们。

. 完成控制器模块的重新安装：
+
.. 将控制器模块牢牢推入机箱，直到它与中板相距并完全就位。
+
控制器模块完全就位后，锁定闩锁会上升。



+

NOTE: 将控制器模块滑入机箱时，请勿用力过大，以免损坏连接器。

+
.. 将锁定闩锁向上旋转到锁定位置。


. 将电源线插入电源。
+

NOTE: 如果您有直流电源、请在控制器模块完全固定在机箱中后、将电源块重新连接到电源。

+
电源恢复后、控制器模块将启动。如果启动到加载程序提示符、请使用命令重新启动控制器 `boot_ontap` 。

. 使用 `storage failover modify -node local -auto-giveback true` 命令禁用自动交还后，可将其还原。
. 如果启用了AutoSupport、请使用命令还原/取消禁止自动创建案例 `system node autosupport invoke -node * -type all -message MAINT=END` 。
. 重复上述步骤，将第二个控制器安装到新机箱中。

