---
permalink: a70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a70, aff a90, how to recable the system, teboot the system 
summary: 您必须重新设置存储的可重新启动控制器。 
---
= 重新恢复并交还控制器- AFF A70、AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重新对存储和网络连接进行配线、然后交还控制器。



== 第 1 步：重新对系统进行布线

重新对控制器模块的存储和网络连接进行配线。

.步骤
. 将控制器模块重新连接到存储和网络连接。
. 使用验证布线是否正确 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。
+
.. 下载并安装 Config Advisor 。
.. 输入目标系统的信息，然后单击收集数据。
.. 单击布线选项卡，然后检查输出。确保显示所有磁盘架且所有磁盘均显示在输出中，以更正您发现的任何布线问题。
.. 单击相应的选项卡，然后检查 Config Advisor 的输出，以检查其他布线。






== 第2步：交还控制器

. 如果您的存储系统配置了加密、则必须使用以下过程还原存储或卷加密功能以重新启动系统：
+
.. 引导至菜单并运行选项10
.. 输入密码短语并备份数据，然后执行正常启动请参阅。 https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys["还原板载密钥管理加密密钥"]
.. 仅执行CFO交还
.. 执行板载同步并验证SVM-KEK是否设置为true、请参见 https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement["在MB替换失败后进行恢复—操作被keymanager否决"]
.. SFo、(无强制)


. 如果您的系统未配置加密、请完成以下过程以重新启动系统：
+
.. 引导至菜单并运行选项1。
.. 交还控制器：
.. 从运行正常的控制器中，交还更换的控制器的存储： `storage failover giveback -ofnode _replacement_node_name_`
+
_replacement_ 控制器将收回其存储并完成启动。

+

NOTE: 如果交还被否决，您可以考虑覆盖此否决。

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["查找适用于您的 ONTAP 9 版本的高可用性配置内容"]

.. 交还完成后，确认 HA 对运行状况良好且可以接管： `storage failover show`


. 如果系统采用 MetroCluster 配置，请监控控制器的状态： `MetroCluster node show`
+
在更换后， MetroCluster 配置需要几分钟才能恢复到正常状态，此时，每个控制器将显示已配置状态，并启用 DR 镜像并显示正常模式。The `metrocluster node show -fields node-systemid` command output displays the old system ID until the MetroCluster configuration returns to a normal state.

. 如果控制器采用 MetroCluster 配置，则根据 MetroCluster 状态，如果原始所有者是灾难站点上的控制器，请验证 DR 主 ID 字段是否显示磁盘的原始所有者。
+
如果同时满足以下条件，则必须执行此操作：

+
** MetroCluster 配置处于切换状态。
** _replacement_ 控制器是灾难站点上磁盘的当前所有者。
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["在四节点 MetroCluster 配置中，磁盘所有权会在 HA 接管和 MetroCluster 切换期间发生更改"]



. 如果您的系统采用 MetroCluster 配置，请验证是否已配置每个控制器： `MetroCluster node show - fields configuration-state`
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. 验证每个控制器是否存在所需的卷： `vol show -node node-name`
. 如果您在重新启动时禁用了自动接管，请从运行正常的控制器启用它： `storage failover modify -node replacement-node-name -onreboot true`

