---
permalink: a70-90/install-power-hardware.html 
sidebar: sidebar 
keywords: aff a70, a90, power controllers 
summary: 连接电源线并打开磁盘架和控制器的电源。 
---
= 打开存储系统的电源- AFF A70、AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
连接网络和任何磁盘架缆线后、您可以为控制器和任何其他磁盘架供电。


NOTE: 外部NS224磁盘架是可选的。



== 第1步：打开磁盘架电源并分配磁盘架ID

在ONTAP存储系统中、每个NS224磁盘架都有一个唯一的磁盘架ID来区分。此ID可确保存储架在存储系统设置中是不同的。默认情况下、磁盘架ID通常分配为‘00 '和‘01 '、但您可能需要调整这些ID、以便在存储系统中保持唯一性。


NOTE: 控制器机箱磁盘架ID硬编码为"00"。请勿对连接到平台的任何NS224磁盘架使用磁盘架ID "00"。

.关于此任务
* 有效磁盘架 ID 为 00 到 99 。
* 您必须重新启动磁盘架(拔下两根电源线、等待适当的时间、然后重新插入)、以使磁盘架ID生效。


.步骤
. 首先将电源线连接到磁盘架、使用电源线固定器将其固定到位、然后将电源线连接到不同电路上的电源、以此为磁盘架通电。
+
插入电源后、磁盘架将自动启动。

. 卸下左端盖、以便接触面板后面的磁盘架ID按钮。
+
image:drw_a900_oie_change_ns224_shelf_id_ieops-836.svg["更改NS224磁盘架ID、宽度= 300个素"]

+
[cols="20%,80%"]
|===


 a| 
image:legend_icon_01.svg["标注编号1，宽度=20"]
 a| 
磁盘架端盖



 a| 
image:legend_icon_02.svg["标注编号2，宽度=20"]
 a| 
磁盘架面板



 a| 
image:legend_icon_03.svg["标注编号3，宽度=20"]
 a| 
磁盘架ID编号



 a| 
image:legend_icon_04.svg["标注编号4，宽度=20"]
 a| 
磁盘架ID访问按钮

|===
. 更改磁盘架 ID 的第一个数字：
+
.. 将回形针或窄尖头圆珠笔的伸直端插入小孔。
.. 按住按钮，直到数字显示屏上的第一个数字闪烁，然后释放按钮。
+
此数字可能需要长达 15 秒才能闪烁。此操作将激活磁盘架 ID 编程模式。

+

NOTE: 如果此 ID 闪烁所需时间超过 15 秒，请再次按住此按钮，确保一直按此按钮。

.. 按下并释放此按钮可将此数字向前移动，直到达到所需数字 0 到 9 为止。
+
每个印刷和发布持续时间可短至一秒。

+
第一个数字将继续闪烁。



. 更改磁盘架 ID 的第二个数字：
+
.. 按住该按钮，直到数字显示屏上的第二个数字闪烁。
+
此数字可能需要长达三秒的时间才能闪烁。

+
数字显示屏上的第一个数字停止闪烁。

.. 按下并释放此按钮可将此数字向前移动，直到达到所需数字 0 到 9 为止。
+
第二个数字将继续闪烁。



. 锁定所需的数字，然后按住该按钮，直到第二个数字停止闪烁，以退出编程模式。
+
此数字可能需要长达三秒的时间才能停止闪烁。

+
数字显示屏上的两个数字开始闪烁，耗时值上的琥珀色 LED 在大约 5 秒后亮起，提醒您待定磁盘架 ID 尚未生效。

. 重新启动磁盘架至少10秒钟、以使磁盘架ID生效。
+
.. 从磁盘架上的两个电源拔下电源线。
.. Wait 10 seconds.
.. 将电源线重新插入磁盘架电源以完成重新启动。
+
插入电源线后立即打开电源。其双色 LED 应呈绿色亮起。



. 更换左端盖。




== 第2步：打开控制器的电源

. 将笔记本电脑连接到串行控制台端口、以便在控制器接通电源后监控启动顺序。
+
.. 使用N-8-1将笔记本电脑上的串行控制台端口设置为115、200波特。
+

NOTE: 有关如何配置串行控制台端口的说明，请参阅便携式计算机的联机帮助。

.. 将控制台电缆连接到笔记本电脑、然后使用平台随附的控制台电缆连接控制器上的串行控制台端口。
.. 将笔记本电脑连接到管理子网上的交换机。
+
image:drw_a1k_70-90_console_connection_ieops-1702.svg["控制台连接"]

.. 使用管理子网上的TCP/IP地址为笔记本电脑分配TCP/IP地址。


. 将电源线插入控制器电源，然后将其连接到不同电路上的电源。
+
image:drw_affa1k_power_source_icon_ieops-1700.svg["通用电源连接图"]

+
** 平台开始启动。Initial booting may take up to eight minutes.
** LED指示灯闪烁且风扇启动、这表示控制器正在通电。
** 风扇在首次启动时可能会发出很大的声音。启动期间风扇噪音较大是正常现象。


. 使用每个电源设备上的固定设备固定电源线。

