---
permalink: a70-90/io-module-replace.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace a pcie card 
summary: 要更换 PCIe 卡，您必须断开卡的缆线连接，从卡中卸下 SFP 和 QSFP 模块，然后再卸下提升板，重新安装提升板，最后重新安装 SFP 和 QSFP 模块，最后再为卡布线。 
---
= 更换I/O模块- AFF A70和AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用此过程更换发生故障的I/O模块。

* 您可以对存储系统支持的所有ONTAP版本使用此过程。
* 存储系统中的所有其他组件必须正常运行；否则，您必须联系技术支持。




== 第 1 步：关闭受损控制器

使用以下选项之一关闭或接管受损控制器。

[role="tabbed-block"]
====
.选项 1 ：大多数系统
--
要关闭受损控制器，您必须确定控制器的状态，并在必要时接管控制器，以便运行正常的控制器继续从受损控制器存储提供数据。

.关于此任务
If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示false、则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。

.步骤
. 如果启用了AutoSupport、则通过调用AutoSupport消息命令禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
以下AutoSupport命令将禁止自动创建案例两小时： `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
`正在等待交还 ...`
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
暂停受损控制器或从运行正常的控制器接管此控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===


--
.选项 2 ：控制器位于 MetroCluster 中
--

NOTE: 如果您的系统采用双节点 MetroCluster 配置，请勿使用此操作步骤。

要关闭受损控制器，您必须确定控制器的状态，并在必要时接管控制器，以便运行正常的控制器继续从受损控制器存储提供数据。

* If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示false、则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。
* 如果您使用的是 MetroCluster 配置，则必须确认已配置 MetroCluster 配置状态，并且节点处于已启用且正常的状态（`MetroCluster node show` ）。


.步骤
. 如果启用了AutoSupport、则通过调用AutoSupport命令禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
以下AutoSupport命令将禁止自动创建案例两小时： `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
正在等待交还
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
暂停受损控制器或从运行正常的控制器接管此控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===


--
====


== 第2步：更换发生故障的I/O模块

要更换I/O模块、请在控制器模块中找到该模块、然后按照特定的步骤顺序进行操作。

. 如果您尚未接地，请正确接地。
. 拔下目标 I/O 模块上的所有布线。
+
请务必为电缆贴上标签、以便您知道电缆的来源。

. 向下旋转缆线管理托架、方法是拉动缆线管理托架内部的按钮、然后向下旋转。
. 从控制器模块中卸下I/O模块：
+

NOTE: 下图显示了如何卸下水平和垂直I/O模块。通常、您只会卸下一个I/O模块。

+
image::../media/drw_a70_90_io_remove_replace_ieops-1532.svg[卸下I/O模块]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["标注编号1、Wides=30bex"]
 a| 
凸轮锁定按钮

|===
+
.. 按下凸轮闩锁按钮。
.. 将凸轮闩锁尽可能远离模块。
.. 将手指插入凸轮拉杆开口处、然后将模块拉出控制器模块、从而将模块从控制器模块中卸下。
+
确保跟踪 I/O 模块所在的插槽。



. 将 I/O 模块放在一旁。
. 将更换用的I/O模块安装到目标插槽中：
+
.. 将 I/O 模块与插槽边缘对齐。
.. 将模块轻轻地滑入插槽、直至完全滑入控制器模块、然后将凸轮闩锁一直向上旋转、以将模块锁定到位。


. 为I/O模块布线。
. 重复拆卸和安装步骤以更换控制器的其他模块。
. 将缆线管理托架旋转到锁定位置。




== 第3步：重新启动控制器

更换 I/O 模块后，必须重新启动控制器模块。


NOTE: 如果新I/O模块与故障模块型号不同、则必须先重新启动BMC。

.步骤
. 如果替代模块与旧模块的型号不同、请重新启动BMC：
+
.. 从加载程序提示符处、更改为高级权限模式：_set PRILEGE advanced_
.. 重新启动BMC：_sp reboot


. 在 LOADER 提示符处，重新启动节点： _bybye
+

NOTE: 此操作将重新初始化I/O卡和其他组件、然后重新启动节点。

+

NOTE: 请务必在完成转换后退出维护模式。

. 将节点恢复正常运行：_storage故障转移g交还-ofnode受损_ne_name_
. 如果已禁用自动交还、请重新启用它：_storage故障转移修改-node local -auto-交还true _




== 第 4 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"]有关详细信息、请参见页面。
