---
permalink: a900/chassis_replace_shutdown.html 
sidebar: sidebar 
keywords: aff a900, shutdown the controllers 
summary: 要更换机箱，必须关闭控制器。 
---
= 关闭受损控制器 - AFF A900
:allow-uri-read: 


[role="lead"]
您必须先关闭机箱中的控制器或控制器，然后再将其移至新机箱。

.关于此任务
* 如果集群包含两个以上的控制器，则该集群必须处于仲裁状态。如果集群未达到仲裁或控制器运行状况良好、则会显示 `false` 有关资格和运行状况、您必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。
* 如果启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
以下 AutoSupport 消息禁止自动创建案例两小时： `cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`



.步骤
. 如果您的系统有两个控制器模块，请禁用 HA 对。
+
[cols="1,2"]
|===
| 如果您的系统运行的是集群模式 ONTAP | 那么 ... 


 a| 
集群中的两个控制器
 a| 
`cluster ha modify -configured false`

`storage failover modify -node node0 -enabled false`



 a| 
集群中有两个以上的控制器
 a| 
`storage failover modify -node node0 -enabled false`

|===
. 暂停控制器，在系统提示您确认 halt 时按 `y` ： `ssystem node halt -node _node_name_`
+
确认消息如下所示：

+
[listing]
----
Warning: This operation will cause controller "node-name" to be marked as unhealthy. Unhealthy nodes do not participate in quorum voting. If the controller goes out of service and one more controller goes out of service there will be a data serving failure for the entire cluster. This will cause a client disruption. Use "cluster show" to verify cluster state. If possible bring other nodes online to improve the resiliency of this cluster.

Do you want to continue? {y|n}:
----
+

NOTE: 在更换机箱之前，您必须完全关闭系统，以避免丢失非易失性内存（ NVMEM/NVRAM ）中未写入的数据。根据您的系统，如果 NVMEM/NVRAM LED 闪烁，则 NVMEM/NVRAM 中有尚未保存到磁盘的内容。您需要重新启动控制器并从此操作步骤 开始。如果反复尝试完全关闭控制器失败，请注意，未保存到磁盘的任何数据可能会丢失。

. 如果适用，请暂停第二个控制器以避免在 HA 对配置中出现可能的仲裁错误消息： `ssystem node halt -node _second_node_name_ -ignore-quorum-warnings true -skip-lif-migration-before-shutdown true`
+
出现提示时，请选择问题解答 `y` 。


