---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_migrate_from_a_switched_configuration_with_dat_storage_by_adding_two_new_shared_switches.html 
keywords:  
summary:  
---
= 通过添加两个新的共享交换机，从具有数据存储的交换配置进行迁移
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




==== 从使用数据存储的交换配置进行迁移

在将某些旧的 Cisco Nexus 集群交换机更换为 Cisco Nexus 9336C-x2 共享交换机时，您必须了解某些配置信息，端口连接和布线要求。

* 支持以下交换机：
+
** Nexus 9336C-x2
** Nexus 3232C


* 交换机使用以下端口连接到节点：
* Nexus 9336C-x2 ：
+
** 端口 1-3 ：分支模式（ 4x10G ）集群内端口，内部 E1/1/1-4 ， E1/2/1-4 ， E1/3/1-4
** 端口 4 - 6 ：分支模式（ 4x25G ）集群内 /HA 端口，内部 E1/4/1-4 ， E1/5/1-4 ， E1/6/1-4
** 端口 7-34 ： 40/100GbE 集群内 /HA 端口，内部 E1/7-34


* Nexus 3232C ：
+
** 端口 1-30 ： 10/40/100 GbE


* 交换机使用以下交换机间链路（ ISL ）端口：
+
** 端口 int E1/35-36 ： Nexus 9336C-x2
** 端口 E1/31-32 ： Nexus 3232C


* Hardware Universe 包含有关所有集群交换机支持的布线的信息。
+
请参见 https://hwu.netapp.com["Hardware Universe"] 有关详细信息 ...

* 您已将 Nexus 9336C-FX2 交换机上的某些端口配置为以 100 GbE 运行。
* 您已规划，迁移并记录了从节点到 Nexus 9336C-x2 交换机的 100 GbE 连接。
* 此操作步骤中支持的 ONTAP 和 NX-OS 版本位于 Cisco 以太网交换机页面上。请参见 https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco 以太网交换机"]。
* 您可以无中断地将其他 Cisco 集群交换机从 ONTAP 集群迁移到 Cisco Nexus 9336C-x2 网络交换机。




===== 开始之前

* 必须正确设置现有交换机网络并使其正常运行。
* 所有端口都必须处于 * 启动 * 状态，以确保无中断运行。
* Nexus 9336C-FX2 交换机必须在安装的正确 NX-OS 版本和应用的参考配置文件（ Reference Configuration File ， RCF ）下进行配置和运行。
* 现有网络配置必须满足以下条件：
+
** 使用两个旧版 Cisco 交换机的冗余且功能完备的 NetApp 集群。
** 管理连接以及对旧 Cisco 交换机和新交换机的控制台访问。
** 与集群 LIF 处于 * 启动 * 状态的所有集群 LIF 均位于其主端口上。
** ISL 端口已启用，并已在其他 Cisco 交换机之间以及新交换机之间进行布线。






===== 关于此任务

此操作步骤中的示例使用以下交换机和节点命名：

* 现有 Cisco Nexus 3232C 集群交换机为 _c1_ 和 _c2_ 。
* 新的 Nexus 9336C-f2 交换机为 _SH1_ 和 _SH2_ 。
* 节点为 _node1_ 和 _node2_ 。
* 集群 LIF 分别是节点 1 上的 _node1_clus1_ 和 _node1_clus2_ 以及节点 2 上的 _node2_clus1_ 和 _node2_clus2_ 。
* 交换机 C2 首先由交换机 SH2 取代，然后交换机 C1 由交换机 SH1 取代。




===== 步骤

. 如果在此集群上启用了 AutoSupport ，请通过调用 AutoSupport 消息来禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all -message MAINT=x h`
+
其中 x 是维护时段的持续时间，以小时为单位。

. 检查每个集群端口的管理和运行状态。
. 确认所有集群端口均已启动且状态正常： `network port show – role cluster`


[listing]
----
cluster1::*> network port show -role cluster
Node: node1
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Ope    Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                   Ignore
                                             Speed(Mbps) Health    Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper  Status    Status
------- --------- ---------------- ---- ---- ----------- --------- ------
e3a     Cluster   Cluster          up   9000  auto/100000 healthy  false
e3b     Cluster   Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.
cluster1::*>
----
. 【第 4 步】确认所有集群接口（ LIF ）都位于主端口上： `network interface show -role cluster`


[listing]
----
cluster1::*> network interface show -role cluster
         Logical     Status     Network           Current     Current Is
Vserver  Interface   Admin/Oper Address/Mask      Node        Port    Home
-------  ----------- ---------- ----------------- ----------- ------- ----
Cluster
        node1_clus1  up/up      169.254.3.4/23    node1       e3a     true
        node1_clus2  up/up      169.254.3.5/23    node1       e3b     true
        node2_clus1  up/up      169.254.3.8/23    node2       e3a     true
        node2_clus2  up/up      169.254.3.9/23    node2       e3b     true
4 entries were displayed.
cluster1::*>
----
. `s确认集群显示两个集群交换机的信息：` system cluster-switch show -is-monitoring-enableed-Operational true


[listing]
----
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ------
sh1                       cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
sh2                       cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
. 【第 6 步】在集群 LIF 上禁用自动还原。


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert false
----
. 【第 7 步】关闭 C2 交换机：


[listing]
----
c2# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
c2(config)# interface ethernet <int range>
c2(config)#shutdown
----
. 【第 8 步】验证集群 LIF 是否已迁移到集群交换机 SH1 上托管的端口： `network interface show -role cluster` 这可能需要几秒钟的时间。


[listing]
----
cluster1::*> network interface show -role cluster
          Logical     Status     Network         Current      Current  Is
Vserver   Interface   Admin/Oper Address/Mask    Node         Port     Home
--------- ----------- ---------- --------------- ------------ -------- -----
Cluster
          node1_clus1 up/up      169.254.3.4/23  node1        e3a      true
          node1_clus2 up/up      169.254.3.5/23  node1        e3a      false
          node2_clus1 up/up      169.254.3.8/23  node2        e3a      true
          node2_clus2 up/up      169.254.3.9/23  node2        e3a      false
4 entries were displayed.
cluster1::*>
----
. 【第 9 步】将交换机 C2 更换为新交换机 SH2 并重新连接新交换机。
. 验证 SH2 上的端口是否已备份。* 注意 * LIF 仍位于交换机 C1 上。
. 关闭 C1 交换机：


[listing]
----
c1# configure terminal
Enter configuration commands, one per line. End with CNTL/Z.
c1(config)# interface ethernet <int range>
c1(config)#shutdown
----
. 【第 12 步】验证集群 LIF 是否已迁移到集群交换机 SH2 上托管的端口。这可能需要几秒钟的时间。


[listing]
----
cluster1::*> network interface show -role cluster
         Logical        Status     Network         Current   Current Is
Vserver  Interface      Admin/Oper Address/Mask    Node      Port    Home
-------- -------------- ---------- --------------- --------- ------- ----
Cluster
         node1_clus1    up/up      169.254.3.4/23  node1     e3a     true
         node1_clus2    up/up      169.254.3.5/23  node1     e3a     false
         node2_clus1    up/up      169.254.3.8/23  node2     e3a     true
         node2_clus2    up/up      169.254.3.9/23  node2     e3a     false
4 entries were displayed.
cluster1::*>
----
. 【第 13 步】将交换机 C1 更换为新交换机 SH1 ，然后重新为新交换机布线。
. 验证 SH1 上的端口是否已备份。* 注意 * LIF 仍位于交换机 C2 上。
. 在集群 LIF 上启用自动还原：


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert True
----
. 【第 16 步】验证集群是否运行正常： `cluster show`


[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
node1                true    true          false
node2                true    true          false
2 entries were displayed.
cluster1::*>
----