---
permalink: a220/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a220, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 要更换机箱，必须关闭控制器。 
---
= 关闭控制器- AFF A220
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用适用于您的配置的操作步骤 关闭或接管受损控制器。



== 选项 1 ：大多数配置

此过程适用于具有双节点配置的系统。有关在维护集群时正常关闭的详细信息，请参见 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["正常关闭和启动存储系统解决方案指南—NetApp知识库"]。

.开始之前
* 确保您具有必要的权限和凭据：
+
** ONTAP 的本地管理员凭据。
** 每个控制器的 BMC 可访问性。


* 确保您拥有进行更换所需的工具和设备。


.步骤
. 通过SSH登录到集群、或者使用本地控制台缆线和笔记本电脑/控制台从集群中的任何节点登录。
. 停止所有客户端/主机访问NetApp系统上的数据。
. 暂停外部备份作业。
. 如果启用了AutoSupport、则禁止创建案例、并指示系统预计脱机多长时间：
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. 确定所有集群节点的SP或BMC地址：
+
`system service-processor show -node * -fields address`

. 退出集群Shell：
+
`exit`

. 使用上一步中确定的 IP 地址登录到每个控制器的 SP/BMC：
+
** 如果通过 SSH 从 BMC 登录，请使用 SP/BMC 地址（例如 `ssh admin@<SP/BMC_address>`）进行连接，然后输入命令 `system console`并进行身份验证。
** 如果使用的是直接连接到控制器的本地控制台或笔记本电脑，请使用相同的集群管理员凭据登录。


. 暂停受损机箱中的两个节点：
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: 对于使用在StrictSync模式下运行的同步SnapMirror的集群： `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 如果出现以下情况，请为集群中的每个控制器输入*y*：
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. 等待每个控制器暂停、然后显示加载程序提示符。




== 选项 2 ：控制器采用 MetroCluster 配置


NOTE: 如果您的系统采用双节点 MetroCluster 配置，请勿使用此操作步骤。

接管并停止受损的控制器，以便健康控制器继续从受损的控制器的存储中提供数据。为此，您需要在 AutoSupport 中禁止自动创建案例，禁用自动回馈，并将受损的控制器带到 LOADER 提示符处。LOADER 提示符是安全停止状态，您可以从中更换 FRU。

* If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示false、则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。
* 如果您使用的是 MetroCluster 配置，则必须确认已配置 MetroCluster 配置状态，并且节点处于已启用且正常的状态（`MetroCluster node show` ）。


.步骤
. 如果启用了AutoSupport 、则通过调用AutoSupport 消息禁止自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
这可以防止在计划的维护时段内打开自动支持案例。最大抑制持续时间为 72 小时。如果维护提前完成，您可以通过调用带有  `MAINT=END` 的 AutoSupport 消息来重新启用案例创建。有关详细信息，请参见  https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["如何在计划维护窗口期间禁止自动创建案例"^]。

+
以下AutoSupport 消息禁止自动创建案例两小时：

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
正在等待交还
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
从运行正常的控制器接管或暂停受损的控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===

