---
settings:
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: ONTAP硬件系统文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: ONTAP硬件系统新增功能
      url: "/whats-new.html"
    - title: ONTAP硬件和软件兼容性
      url: "/supported-platforms.html"
    - title: 停止支持
      url: "/eoa-hardware.html"
  - title: 快速入门
    url: "/get-up-and-run.html"
  - title: AFF 系统
    url: "/aff-landing/index.html"
    entries:
    - title: A系列系统
      url: "/aff-aseries/index.html"
      entries:
      - section: a1k
      - section: a70-90
      - section: a20-30-50
      - section: a150
      - section: a250
      - section: a400
      - section: a800
      - section: a900
    - title: C系列系统
      url: "/aff-cseries/index.html"
      entries:
      - section: c30-60
      - section: c80
      - section: c250
      - section: c400
      - section: c800
  - title: AFX 系统
    url: "/afx/index.html"
    entries:
    - title: 安装和设置
      url: "/afx/afx-install-setup.html"
    - title: 维护
      pdf-filename: AFX 维护
      url: "/afx-landing-maintain/index.html"
      entries:
      - title: 维护概述
        url: "/afx-1k/maintain-overview.html"
      - title: 启动介质
        url: "/afx-1k/bootmedia-replace-workflow.html"
      - title: 机箱
        url: "/afx-1k/chassis-replace-workflow.html"
      - title: 控制器
        url: "/afx-1k/controller-replace-workflow.html"
      - title: DIMM
        url: "/afx-1k/dimm-replace.html"
      - title: 风扇
        url: "/afx-1k/fan-replace.html"
      - title: NVRAM
        url: "/afx-1k/nvram-replace.html"
      - title: NV电池
        url: "/afx-1k/nvdimm-battery-replace.html"
      - title: I/O 模块
        url: "/afx-1k/io-module-overview.html"
      - title: 电源
        url: "/afx-1k/power-supply-replace.html"
      - title: 实时时钟电池
        url: "/afx-1k/rtc-battery-replace.html"
      - title: 系统管理模块
        url: "/afx-1k/system-management-replace.html"
  - title: ASA 系统
    url: "/allsan-landing/index.html"
    entries:
    - title: A系列系统
      url: "/allsan-a-series/index.html"
      entries:
      - section: asa150
      - section: asa250
      - section: asa400
      - section: asa800
      - section: asa900
    - title: C系列系统
      url: "/allsan-c-series/index.html"
      entries:
      - section: asa-c250
      - section: asa-c400
      - section: asa-c800
  - title: ASA r2系统
    url: "/asa-r2/index.html"
    entries:
    - title: 安装和设置
      url: "/asa-r2/asa-r2-install-setup.html"
    - title: 维护
      url: "/asa-r2-landing-maintain/index.html"
      entries:
      - section: asa-r2-a1k-maintain
      - section: asa-r2-a70-90-maintain
      - section: asa-r2-a20-30-50-maintain
      - section: asa-r2-c30-maintain
    - section: asa-r2-key-specifications
  - title: FAS 系统
    url: "/fas/index.html"
    entries:
    - section: fas50
    - section: fas-70-90
    - section: fas2700
    - section: fas2800
    - section: fas8300
    - section: fas9500
  - title: 可用性已终止的系统
    url: "/endofavail/index.html"
    entries:
    - section: a200
    - section: a220
    - section: a300
    - section: a320
    - section: a700
    - section: a700s
    - section: c190
    - section: fas2600
    - section: fas500f
    - section: fas8200
    - section: fas9000
    - title: 其他型号
      url: "/other/other-models.html"
  - title: 驱动器架
    url: "/drive-shelves/index.html"
    entries:
    - section: ns224
    - section: nx224
    - section: sas3
  - title: 机柜和导轨套件
    entries:
    - title: SuperRail 套件
      url: "/platform-supplemental/superrail-install.html"
    - title: AFF A700/FAS9000 双柱导轨套件
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42U 1280 毫米系统机柜
      entries:
      - title: 准备安装机柜
        entries:
        - title: 机柜功能
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: 所需工具 / 设备
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: 空间要求和机柜尺寸
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: 支持的 PDU 类型和规格
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: 打开系统机柜的包装
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: 安装机柜
        entries:
        - title: 概述
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: 安装机柜互连套件
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: 安装固定套件
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: 安装支持导轨
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: 安装设备
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: 打开机柜电源
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: 更换 PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: 反转机柜前盖
        entries:
        - title: 您需要的内容
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: 拆下照明标志
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: 卸下机柜门
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: 移动标志电源和布线
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: 反向车门转轴和锁扣
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: 重新安装车门和照明标志
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - title: 组件更换程序
    url: "/fru-reference/index.html"
    entries:
    - title: 启动介质
      url: "/fru-reference/bootmedia-fru-links.html"
    - title: 缓存模块
      url: "/fru-reference/caching-module-fru-links.html"
    - title: 机箱
      url: "/fru-reference/chassis-fru-links.html"
    - title: 控制器
      url: "/fru-reference/controller-fru-links.html"
    - title: DCPM电源模块
      url: "/fru-reference/dcpm-power-fru-links.html"
    - title: DIMM
      url: "/fru-reference/dimm-fru-links.html"
    - title: 驱动器
      url: "/fru-reference/drive-fru-links.html"
    - title: 风扇
      url: "/fru-reference/fan-fru-links.html"
    - title: I/O 模块
      url: "/fru-reference/io-module-fru-links.html"
    - title: LED 模块
      url: "/fru-reference/led-module-fru-links.html"
    - title: 夹层
      url: "/fru-reference/mezzanine-fru-links.html"
    - title: NVDIMM
      url: "/fru-reference/nvdimm-fru-links.html"
    - title: NVMEM/ NVRAM电池
      url: "/fru-reference/nvmem-battery-fru-links.html"
    - title: NVRAM模块
      url: "/fru-reference/nvram-module-fru-links.html"
    - title: PCI 卡和转接卡
      url: "/fru-reference/pci-cards-fru-links.html"
    - title: 电源
      url: "/fru-reference/power-supply-fru-links.html"
    - title: RTC 电池
      url: "/fru-reference/rtc-battery-fru-links.html"
    - title: 系统管理模块
      url: "/fru-reference/system-management-fru-links.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: ONTAP hardware systems
  repo: ontap-systems-family
