---
settings:
  search: ontap-systems
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  rss_page: whats-new.html
  langs: zh-cn,us-en,ja-jp,ko-kr,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: AFF 和 FAS 系统文档
    url: "/index.html"
  - title: 发行说明
    url: "/rel-notes.html"
  - title: 入门
    entries:
    - title: 新增功能
      url: "/whats-new.html"
    - title: 启动并运行
      url: "/get-up-and-run.html"
  - title: AFF 系统
    entries:
    - section: c190
    - section: c250
    - section: c400
    - section: c800
    - section: a150
    - section: a220
    - section: a250
    - section: a400
    - section: a700
    - section: a800
    - section: a900
  - title: FAS 系统
    entries:
    - section: fas500f
    - section: fas8300
    - section: fas9000
    - section: fas9500
  - title: 可用性已终止的系统
    entries:
    - section: a200
    - section: a300
    - section: a320
    - section: a700s
    - section: fas2600
    - section: fas2700
    - section: fas8200
  - section: allsan
  - section: upgrade
  - title: 系统级诊断
    entries:
    - title: 简介
      url: "/platform-supplemental/sldiag-introduction.html"
    - title: 要求
      url: "/platform-supplemental/sldiag-requirements.html"
    - title: 如何使用命令行帮助
      url: "/platform-supplemental/sldiag-use-cli-help.html"
    - title: 运行系统安装诊断
      url: "/platform-supplemental/sldiag-system-installation-diagnostics.html"
    - title: 运行系统崩溃诊断
      url: "/platform-supplemental/sldiag-system-panic-diagnostics.html"
    - title: 运行系统响应缓慢诊断
      url: "/platform-supplemental/sldiag-slow-system-diagnostics.html"
    - title: 运行硬件安装诊断
      url: "/platform-supplemental/sldiag-hardware-installation-diagnostics.html"
    - title: 运行设备故障诊断
      url: "/platform-supplemental/sldiag-device-failure-diagnostics.html"
  - title: 驱动器架
    entries:
    - section: ns224
    - section: sas3
  - section: switch
  - title: 机柜和导轨套件
    entries:
    - title: SuperRail 套件
      url: "/platform-supplemental/superrail-install.html"
    - title: AFF A700/FAS9000 双柱导轨套件
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42U 1280 毫米系统机柜
      entries:
      - title: 准备安装机柜
        entries:
        - title: 机柜功能
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: 所需工具 / 设备
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: 空间要求和机柜尺寸
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: 支持的 PDU 类型和规格
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: 打开系统机柜的包装
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: 安装机柜
        entries:
        - title: 概述
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: 安装机柜互连套件
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: 安装固定套件
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: 安装支持导轨
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: 安装设备
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: 打开机柜电源
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: 更换 PDU
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: 反转机柜前盖
        entries:
        - title: 您需要的内容
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: 拆下照明标志
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: 卸下机柜门
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: 移动标志电源和布线
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: 反向车门转轴和锁扣
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: 重新安装车门和照明标志
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - section: other
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
