---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, afx, asa r2, aff, asa, fas 
summary: 了解适用于ONTAP硬件系统的新平台。 
---
= ONTAP硬件系统新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解ONTAP硬件系统的新增功能。有关其他支持信息，请参阅link:supported-platforms.html["ONTAP硬件和软件兼容性"]和link:eoa-hardware.html["不再支持硬件"] 。



== 2025年10月



=== AFX存储系统

全新NetApp AFX 存储系统提供分解式解决方案，旨在满足高性能 NAS 和 S3 工作负载（包括 AI/ML 应用程序）的严格要求。AFX 系统为需要可扩展、高吞吐量文件和对象存储的客户提供专门的功能。

link:https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["了解有关 AFX 系统的更多信息"] 。



=== AFX 的新驱动器架

AFX 的新型 NXS224 存储架使用非易失性内存快速架构 (NVMe-oF) 连接高密度 SSD。磁盘使用融合以太网上的 RDMA (RoCE) 通过超低延迟结构进行通信。存储架（包括 I/O 模块、NIC、风扇和电源）完全冗余，没有单点故障。自管理技术用于管理和控制 RAID 配置和磁盘布局的各个方面。



=== AFX 的新开关

Cisco 9364D-GX2A 交换机和Cisco 9332D-GX2B 交换机将 AFX 控制器节点与存储架连接起来。这些新交换机允许您构建具有两个以上节点的ONTAP集群。使用先进的协议来优化性能。该设计基于具有多个网络路径的 VLAN 标记以及技术更新配置，以确保持续运行和轻松升级。



== 2025年9月



=== 平台规格

ONTAP硬件系统文档现在包括以下规范：link:https://hwu.netapp.com["Hardware Universe"] 。例如，link:https://docs.netapp.com/us-en/ontap-systems/a1k/overview.html["AFF A1K的主要规格"] 。



=== 按平台系列划分的替换参考

ONTAP硬件系统文档现在提供按平台系列组织的NetApp存储系统的更换程序。

link:fru-reference/index.html["查找替换程序"]用于存储系统的现场可更换单元 (FRU)。



== 2025年5月



=== ASA C30

全新ASA C30系统将高性能、智能、全面的数据管理功能扩展到更多客户和工作负载。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["详细了解ASA R2系统"^] 。



== 2025年4月



=== FAS50

FAS50 系统为二级存储和安全网络保险库提供了最低的每 GB 成本，同时通过更快的备份、更高的 IOPS 和 5-10 毫秒的低延迟提高了二级工作负载的性能。

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["详细了解FAS系统"^] 。



== 2025年2月



=== ASA A20、ASA A30和ASA A50

入门级ASA A20和中端ASA A30和A50系统使各种规模的公司都可以使用块存储来运行数据库和虚拟机等任务关键型应用程序。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["详细了解ASA R2系统"^] 。



== 2024 年发行

.2024年12月
[%collapsible]
====
.AFF A20、AFF A30和AFF A50
全新的AFF A20、A30和A50硬件系统将高性能、智能和全面的数据管理功能扩展到更多客户和工作负载。

这些系统可为AI、VMware、数据库和分析等任务关键型工作负载提供基于ML的实时勒索软件检测、无缝云集成和无与伦比的性能、并支持块、文件和对象存储。

link:https://www.netapp.com/data-storage/aff-a-series/["详细了解AFF A系列系统"^] 。

.AFF C30、AFF C60和AFF C80
全新的AFF C30、AFF C60和AFF C80硬件系统通过在双机架部署中提供行业领先的1.5 PB存储容量、使企业更容易获得闪存的性能和效率提升。

该解决方案可通过60 TB驱动器提供超群的密度、提高性能并提高I/O灵活性。

link:https://www.netapp.com/data-storage/aff-c-series/["详细了解AFF C系列系统"^] 。

.具有NSM100B磁盘架模块的NS224驱动器架
借助NS224和全新的NSM100B NVMe存储扩展模块增强数据中心的功能。全新的NSM100B磁盘架模块可直接取代NSM100模块、可无缝集成到您的现有设置中。它支持NS224磁盘架的直连和交换机连接配置、可提供卓越的灵活性、以优化存储系统的效率和可扩展性。

====
.2024年9月
[%collapsible]
====
.ASA r2系统
新的ASA R2硬件系统(ASA A1K、ASA A70和ASA A90)提供了一个统一的硬件和软件解决方案、可根据仅SAN客户的需求提供简化的体验。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["详细了解ASA R2系统"^] 。

.FAS70和FAS90
全新的FAS70和FAS90硬件系统可提供经济实惠且性能高的备份存储、从而实现安全的网络存储、以便从勒索软件攻击中恢复。

link:https://www.netapp.com/data-storage/fas/["详细了解FAS系统"^] 。

====