---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: 了解适用于ONTAP硬件系统的新平台。 
---
= ONTAP硬件系统新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解ONTAP硬件系统的新增功能。



== 2024年12月



=== 具有NSM100B模块的NS224磁盘架

具有NSM100B模块的NS224驱动器架可提供高性能和灵活性、以满足您的数字化转型需求。

link:ns224/hot-add-shelf-overview.html["使用NS224磁盘架扩展硬件系统存储"](英文)



=== AFF A20、AFF A30和AFF A50

全新的AFF A20、A30和A50硬件系统将高性能、智能和全面的数据管理功能扩展到更多客户和工作负载。

这些系统可为AI、VMware、数据库和分析等任务关键型工作负载提供基于ML的实时勒索软件检测、无缝云集成和无与伦比的性能、并支持块、文件和对象存储。

link:https://www.netapp.com/data-storage/aff-a-series/["详细了解AFF A系列系统"](英文)



=== AFF C30、AFF C60和AFF C80

全新的AFF C30、AFF C60和AFF C80硬件系统通过在双机架部署中提供行业领先的1.5 PB存储容量、使企业更容易获得闪存的性能和效率提升。

该解决方案可通过60 TB驱动器提供超群的密度、提高性能并提高I/O灵活性。

link:https://www.netapp.com/data-storage/aff-c-series/["详细了解AFF C系列系统"](英文)



=== 具有NSM100B磁盘架模块的NS224驱动器架

借助NS224和全新的NSM100B NVMe存储扩展模块增强数据中心的功能。全新的NSM100B磁盘架模块可直接取代NSM100模块、可无缝集成到您的现有设置中。它支持NS224磁盘架的直连和交换机连接配置、可提供卓越的灵活性、以优化存储系统的效率和可扩展性。



== 2024年9月



=== ASA r2系统

新的ASA R2硬件系统(ASA A1K、ASA A70和ASA A90)提供了一个统一的硬件和软件解决方案、可根据仅SAN客户的需求提供简化的体验。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["详细了解ASA R2系统"](英文)



=== FAS70和FAS90

全新的FAS70和FAS90硬件系统可提供经济实惠且性能高的备份存储、从而实现安全的网络存储、以便从勒索软件攻击中恢复。

link:https://www.netapp.com/data-storage/fas/["详细了解FAS系统"](英文)
