---
permalink: asa400/overview.html 
sidebar: sidebar 
keywords: ASA A400 specifications, ASA A400 specs, NetApp ASA A400, ASA A400 hardware 
summary: ASA A400存储系统的主要规格 
---
= ASA A400的主要规格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是ASA A400的部分规格。访问 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）获取ASA A400规格的完整列表。此页面反映的是单个高可用性对。



=== ASA A400的主要规格

平台配置： ASA A400单机箱 HA 对，以太网捆绑包

最大原始容量：14.6880 PB

内存：256.0000 GB

外形尺寸：4U 机箱，带 2 个 HA 控制器

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 扩展槽：10

最低ONTAP版本： ONTAP 9.13.1



=== 横向扩展最大值

|===


| 类型 | HA 对 | 原始容量 | 最大内存 


| NAS |  |  |  


| SAN | 6 | 88.1 PB / 78.3 PiB | 1536 GB 


| HA 对 |  | 14.7 PB / 13.0 PiB | 256.0000 
|===


=== 输入输出



==== 板载 IO

|===


| 协议 | 端口 


| 以太网 100 Gbps | 4 


| 以太网 25 Gbps | 12 


| SAS 12 Gbps | 8 
|===


==== 总 IO

|===


| 协议 | 端口 


| 以太网 100 Gbps | 20 


| 以太网 25 Gbps | 24 


| 以太网 10 Gbps | 32 


| 光纤通道 32 Gbps | 24 


| NVMe/FC 32 Gbps | 24 


|  | 0 


| SAS 12 Gbps | 32 
|===


==== 管理端口

|===


| 协议 | 端口 


| 以太网 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== 支持的存储网络

足球俱乐部； iSCSI； NVMe/FC； NVMe/TCP；



=== 系统环境规格

* 典型功率：4209 BTU/小时
* 最坏情况下的功率：5212 BTU/小时
* 重量：110.0 磅/49.9 千克
* 高度：4U
* 宽度：19 英寸 IEC 机架兼容（17.6 英寸 44.7 厘米）
* 深度：32.6 英寸/（34.7 英寸，含电缆管理支架）
* 工作温度/海拔/湿度：海拔 3048 英尺时 10°C 至 35°C（50°F 至 95°F）；相对湿度 8% 至 80%，无凝结
* 非工作温度/湿度：-40°C 至 70°C（-40°F 至 158°F），最高海拔 12192 米（40000 英尺）<br/>10% 至 95% 相对湿度，非冷凝，原包装箱内
* 噪音：标称声功率 (LwAd)：8.5；br/声压 (LpAm)（旁观者位置）：67.2 dB




=== Compliance

* EMC/EMI 认证：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全认证：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI认证：EAC、UKRSEPRO
* 认证安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 标准 EMC/EMI：BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC 第 15 部分 A 类、ICES-003、KS C 9832、KS C 9835
* 标准安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

基于以太网的基板管理控制器 (BMC) 和ONTAP管理接口；冗余热插拔控制器；冗余热插拔电源；通过 SAS 连接进行 SAS 带内管理；
