---
permalink: asa400/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: asa a400, asa, a400, component, system, function, properly, contact, technical, support, replace, chassis, shut, down, controller, replacing, remove, module, fan, equipment, rack, cabinet, ha, state, switch, back, aggregate, two-node, metrocluster, configuration, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, verify and set the ha state of the chassis, switch back aggregates in a two-node metrocluster configuration, complete the replacement process 
summary: 要更换机箱，必须关闭控制器。 
---
= 关闭控制器- ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用适用于您的配置的操作步骤 关闭或接管受损控制器。



== 选项 1 ：在更换机箱时关闭控制器

此过程适用于具有双节点配置的系统。有关在维护集群时正常关闭的详细信息，请参见 https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage["正常关闭和启动存储系统解决方案指南—NetApp知识库"]。

.开始之前
* 确保您具有必要的权限和凭据：
+
** ONTAP 的本地管理员凭据。
** 每个控制器的BMC可访问性。


* 确保您拥有进行更换所需的工具和设备。
* 作为关闭之前的最佳实践、您应：
+
** 执行其他 https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["系统运行状况检查"]。
** 将ONTAP 升级到系统的建议版本。
** 解决任何问题 https://activeiq.netapp.com/["Active IQ 健康提醒和风险"]。记下系统当前的任何故障、例如系统组件上的LED。




.步骤
. 通过SSH登录到集群、或者使用本地控制台缆线和笔记本电脑/控制台从集群中的任何节点登录。
. 停止所有客户端/主机访问NetApp系统上的数据。
. 暂停外部备份作业。
. 如果启用了AutoSupport、则禁止创建案例、并指示系统预计脱机多长时间：
+
`system node autosupport invoke -node * -type all -message "MAINT=2h Replace chassis"`

. 确定所有集群节点的SP或BMC地址：
+
`system service-processor show -node * -fields address`

. 退出集群Shell：
+
`exit`

. 使用上一步输出中列出的任何节点的IP地址通过SSH登录到SP或BMC以监控进度。
+
如果您使用的是控制台/笔记本电脑、请使用相同的集群管理员凭据登录到控制器。

. 暂停受损机箱中的两个节点：
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: 对于使用在StrictSync模式下运行的同步SnapMirror的集群： `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 如果出现以下情况，请为集群中的每个控制器输入*y*：
+
`Warning: Are you sure you want to halt node _<node_name>_? {y|n}:`

. 等待每个控制器暂停、然后显示加载程序提示符。




== 选项 2 ：关闭双节点 MetroCluster 配置中的控制器

要关闭受损控制器，您必须确定控制器的状态，并在必要时切换控制器，以便运行正常的控制器继续从受损控制器存储提供数据。

.关于此任务
* 您必须在此操作步骤 末尾保持电源处于打开状态，以便为运行正常的控制器供电。


.步骤
. 检查 MetroCluster 状态以确定受损控制器是否已自动切换到运行正常的控制器： `MetroCluster show`
. 根据是否发生了自动切换，按照下表继续操作：
+
[cols="1,2"]
|===
| 如果控制器受损 ... | 那么 ... 


 a| 
已自动切换
 a| 
继续执行下一步。



 a| 
未自动切换
 a| 
从运行正常的控制器执行计划内切换操作： `MetroCluster switchover`



 a| 
未自动切换，您尝试使用 `MetroCluster switchover` 命令进行切换，并且切换已被否决
 a| 
查看否决消息，如果可能，请解决问题描述并重试。如果无法解决问题描述问题，请联系技术支持。

|===
. 在运行正常的集群中运行 `MetroCluster heal -phase aggregates` 命令，以重新同步数据聚合。
+
[listing]
----
controller_A_1::> metrocluster heal -phase aggregates
[Job 130] Job succeeded: Heal Aggregates is successful.
----
+
如果修复被否决，您可以使用 ` override-vetoes` 参数重新发出 `MetroCluster heal` 命令。如果使用此可选参数，则系统将覆盖任何阻止修复操作的软否决。

. 使用 MetroCluster operation show 命令验证操作是否已完成。
+
[listing]
----
controller_A_1::> metrocluster operation show
    Operation: heal-aggregates
      State: successful
Start Time: 7/25/2016 18:45:55
   End Time: 7/25/2016 18:45:56
     Errors: -
----
. 使用 `storage aggregate show` 命令检查聚合的状态。
+
[listing]
----
controller_A_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 mcc1-a2          raid_dp, mirrored, normal...
----
. 使用 `MetroCluster heal -phase root-aggregates` 命令修复根聚合。
+
[listing]
----
mcc1A::> metrocluster heal -phase root-aggregates
[Job 137] Job succeeded: Heal Root Aggregates is successful
----
+
如果修复被否决，您可以使用 -override-vetoes 参数重新发出 `MetroCluster heal` 命令。如果使用此可选参数，则系统将覆盖任何阻止修复操作的软否决。

. 在目标集群上使用 `MetroCluster operation show` 命令验证修复操作是否已完成：
+
[listing]
----

mcc1A::> metrocluster operation show
  Operation: heal-root-aggregates
      State: successful
 Start Time: 7/29/2016 20:54:41
   End Time: 7/29/2016 20:54:42
     Errors: -
----
. 在受损控制器模块上，断开电源。

