---
permalink: c80/overview.html 
sidebar: sidebar 
keywords: AFF C80 specifications, AFF C80 specs, NetApp AFF C80, AFF C80 hardware 
summary: AFF C80 存储系统的主要规格 
---
= AFF C80 的主要规格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是AFF C80 的部分规格。访问 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）获取AFF C80 规格的完整列表。此页面反映的是单个高可用性对。



=== AFF C80 的主要规格

平台配置： AFF C80 单机箱 HA 对

最大原始容量：14.7360 PB

内存：512.0000 GB

外形尺寸：4U 机箱，配备 2 个 HA 控制器和 48 个驱动器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 扩展槽：18

最低ONTAP版本： ONTAP 9.16.1RC1



=== 横向扩展最大值

|===


| 类型 | HA 对 | 原始容量 | 最大内存 


| NAS | 12 | 176.8 PB / 157.0 PiB | 6144 GB 


| SAN | 6 | 88.4 PB / 78.5 PiB | 3072 GB 


| HA 对 |  | 14.7 PB / 13.1 PiB | 512.0000 
|===


=== 输入输出



==== 板载 IO

无板载 IO 数据。



==== 总 IO

|===


| 协议 | 端口 


| 以太网 200 Gbps | 24 


| 以太网 100 Gbps | 36 


| 以太网 25 Gbps | 56 


| 以太网 10 Gbps | 56 


| 光纤通道 64 Gbps | 56 


| NVMe/FC 64 Gbps | 56 


|  | 0 
|===


==== 管理端口

|===


| 协议 | 端口 


| 以太网 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== 支持的存储网络

CIFS；FC；iSCSI；NFS v3；NFS v4.0；NFS v4.1；NFS v4.2；NFSv3/RDMA；NFSv4/RDMA；NVMe/FC；NVMe/TCP；S3；带 NAS 的 S3；SMB 2.0；SMB 2.1；SMB 2.x；SMB 3.0；SMB 3.1；SMB 3.1.1；



=== 系统环境规格

没有可用的环境数据。



=== Compliance

* EMC/EMI 认证：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全认证：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI认证：EAC、UKRSEPRO
* 认证安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 标准 EMC/EMI：BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC 第 15 部分 A 类、ICES-003、KS C 9832、KS C 9835
* 标准安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

基于以太网的基板管理控制器 (BMC) 和ONTAP管理接口；冗余热插拔控制器；冗余热插拔电源；[//] 2025-10-15 ontap-systems-internal/issues/1357
