---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: 系统机柜由侧面板，前后门，可选的固定套件，可选的互连套件，设备的 PDU 以及集成的缆线管理系统组成。 
---
= 系统机柜功能
:icons: font
:imagesdir: ../media/


[role="lead"]
系统机柜由侧面板，前后门，可选的固定套件，可选的互连套件，设备的 PDU 以及集成的缆线管理系统组成。

[cols="1,2"]
|===
| 功能 | Description 


 a| 
侧面板
 a| 
系统机柜具有可锁定，可拆卸和可互换的侧面板。



 a| 
前后车门有多孔
 a| 
系统机柜具有可拆卸的前后门，并具有快速释放机制。前挡盖可反转，后挡盖拆分。两个门都有多孔，用于散热。



 a| 
通用密钥
 a| 
此密钥用于解锁前车门，后车门和侧面板。



 a| 
备件套件
 a| 
此套件位于系统机柜内，与机柜门相连。它包含以下组件：

* 四个 10-32 x 0.75 英寸十字定位螺钉
* 四个 10-32 螺钉
* 一个锁紧螺母插入工具
* 两个主密钥副本




 a| 
缆线访问
 a| 
缆线直通内置于机柜顶部和底部，以及后盖底部和框架之间。



 a| 
缆线管理
 a| 
缆线管理钩和环路捆带以相同的间隔连接到系统机柜框架。



 a| 
支持导轨
 a| 
您收到的支持导轨数量取决于您的配置。空的系统机柜在出厂时未安装任何支持导轨。

* 对于已配置的系统机柜，系统机柜随附一个固定导轨套件，用于支持 80xx ， FAS8200 和 DS4486 后固定支架。
* 快速发货系统机柜不包括额外的固定导轨套件。




 a| 
空白面板
 a| 
接收的空白面板的数量和大小取决于您的配置。空系统机柜出厂时未安装任何空白面板。



 a| 
固定套件
 a| 
通过此可选套件，您可以将系统机柜固定到数据中心楼层。该套件不适用于地震稳定性。

* 四个固定支架
* 四个隔套支架
* 六个 M8x20 毫米六角头螺钉和垫圈




 a| 
互连套件
 a| 
通过此可选套件，您可以将多个系统机柜彼此连接起来。

* 互连支架
+
** 一组四个互连支架，用于连接带有侧面板的系统机柜
** 一组四个互连支架，用于在侧面板关闭的情况下连接系统机柜


* 系统机柜中使用的四个 M12 x 20 内星形 30 螺钉，侧面板位于上。
* 在侧面板关闭的情况下，系统机柜中使用了八个 M6X10 半沉头内星形 30 螺钉。




 a| 
支持导轨套件
 a| 
如果您随系统机柜一起订购了额外的支持导轨，则每个套件都包含一个左右支持导轨。


NOTE: 支持导轨和套件仅适用于 NetApp 42U 1280 毫米系统机柜。请勿使用其他系统机柜中的导轨或导轨套件，因为它们不适用于 42U 1280 毫米系统机柜。

* 左侧和右侧支撑导轨
* 每个导轨两个螺钉，用于将导轨固定到系统机柜框架




 a| 
新月扳手
 a| 
新月形扳手用于卸下包装托盘上的固定支架，调整系统机柜水平垫，如果订购，则安装固定套件支架。

|===