---
permalink: platform-supplemental/42u-1280mm-replace-pdus.html 
sidebar: sidebar 
keywords: replace, fail, PDU, system, cabinet, replace, exist, replace pdu 
summary: 您可以更换系统机柜中发生故障的 PDU ，也可以将现有 PDU 更换为其他类型的 PDU 。 
---
= 更换 PDU
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更换系统机柜中发生故障的 PDU ，也可以将现有 PDU 更换为其他类型的 PDU 。

更换用的 PDU 必须由系统机柜支持，并且必须为已安装的设备提供足够的电源。

https://hwu.netapp.com/["hwu.netapp.com"]

. 关闭目标 PDU 上的断路器，然后从交流电源中拔下旧 PDU 的插头。
. 将您自己接地到系统机柜，然后从每个系统组件和 PDU 上拔下电源线。
. 从 PDU 框架上卸下螺钉，首先拧下底部螺钉。
+

NOTE: 从 PDU 顶部卸下最后一个螺钉时，请确保用一只手支撑 PDU 。这样可以防止 PDU 在卸下螺钉后跌落或跌落至您的位置。

. 从系统机柜中卸下旧 PDU 。
+
请务必跟踪安装螺钉，以便在安装更换用的 PDU 时可以重复使用这些螺钉。

. 从旧 PDU 中卸下支架，然后将其安装在替代 PDU 的背面。
. 在支持替代 PDU 时，将 PDU 安装支架上的插槽与系统机柜内框架顶部的孔对齐，然后使用旧 PDU 中的安装螺钉将 PDU 固定到系统机柜框架上。
. 将 PDU 的底部固定到系统机柜框架上，然后拧紧所有安装螺钉。
. 确认所有电源开关或断路器均处于 OFF 位置。
+
如果断路器未处于 OFF 位置，请将一个小螺丝刀或直发的回形针推入 OFF 标签右侧的插槽，以使断路器跳闸并关闭电路。

. 将系统电源线插入 PDU ，将每个组件直接插入组件对面的 PDU 插座。
+

TIP: 最佳做法是，在 PDU 分支之间分布总负载，使每个分支的负载尽可能相等。

. 通过将缆线固定夹的弯曲边缘滑过插头肩，将每个组件的电源缆线插头用其上方的缆线固定夹锁定到位。
. 将 PDU 电源线插入交流电源。
. 打开 PDU 电源开关或 PDU 断路器。
+
对于 PDU 断路器，当该按钮与 PDU 帧平齐时，该按钮将打开。


