---
permalink: platform-supplemental/drive-hotswap-drive.html 
sidebar: sidebar 
keywords: drive, fail, platform, log, warning, message, system, console, drive, addition, fault, led, operator, display, panel, fault, led, illuminate, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 驱动器发生故障时，平台会向系统控制台记录一条警告消息，指示哪个驱动器发生故障。此外，操作员显示面板上的故障 LED 和故障驱动器上的故障 LED 都会亮起。您可以在 I/O 运行期间无中断更换故障驱动器。 
---
= 热插拔驱动器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
驱动器发生故障时，平台会向系统控制台记录一条警告消息，指示哪个驱动器发生故障。此外，操作员显示面板上的故障 LED 和故障驱动器上的故障 LED 都会亮起。您可以在 I/O 运行期间无中断更换故障驱动器。

* 您的平台必须支持替代驱动器。
+
https://["NetApp Hardware Universe"]

* 如果启用了 SED 身份验证，则必须使用 ONTAP 文档中的 SED 更换说明。
+
ONTAP 文档中的说明介绍了在更换 SED 之前和之后必须执行的其他步骤。

+
https://["《 ONTAP 9 NetApp 加密高级指南》"]

* 系统中的所有其他组件必须正常运行；否则，请联系技术支持。
* 运行 `storage disk show -broken` 命令，验证要删除的驱动器是否出现故障。故障驱动器将显示在故障驱动器列表中。如果不是，则应等待，然后重新运行命令。
+

NOTE: 根据驱动器类型和容量，该驱动器可能需要长达数小时才能显示在故障驱动器列表中。

* * 最佳实践： * 最佳实践是，在热插拔驱动器之前，安装最新版本的磁盘认证包（ DQP ）。
* 在固件版本不是最新的新驱动器上，驱动器固件会自动更新（无中断）。
* 拆开备用驱动器的包装时，请保存所有包装材料，以便在退回故障驱动器时使用。
+
.. 如果要手动为替代驱动器分配驱动器所有权，则需要禁用自动驱动器分配替代驱动器（如果已启用）
+

NOTE: 您可以手动分配驱动器所有权，然后在此操作步骤中稍后重新启用自动驱动器分配。

+
... 验证是否已启用自动驱动器分配： `storage disk option show`
+
您可以在任一控制器模块上输入命令。

+
如果启用了自动驱动器分配，则输出会在 "`Auto Assign` " 列中显示 `on` （对于每个控制器模块）。

... 如果启用了自动驱动器分配，请将其禁用： `storage disk option modify -node node_name -autodassign off`
+
您必须在两个控制器模块上禁用自动驱动器分配。



.. 正确接地。
.. 以物理方式确定故障驱动器。
+
驱动器发生故障时，系统会向系统控制台记录一条警告消息，指示哪个驱动器发生故障。此外，驱动器架操作员显示面板上的警示（琥珀色） LED 和故障驱动器将亮起。

+

NOTE: 故障驱动器上的活动（绿色） LED 可能会亮起（稳定亮起），表示驱动器已通电，但不应闪烁，这表示 I/O 活动。故障驱动器没有 I/O 活动。

.. 删除故障驱动器：
+
... 按下驱动器表面上的释放按钮以打开凸轮把手。
... 使用凸轮把手将驱动器滑出磁盘架，并用另一只手支撑驱动器。


.. 请至少等待 70 秒，然后再插入替代驱动器。
+
这样，系统就可以识别出驱动器已被删除。

.. 插入替代驱动器：
+
... 在凸轮把手处于打开位置的情况下，用双手插入替代驱动器。
... 按，直到驱动器停止。
... 合上凸轮把手，使驱动器完全固定在中间板上，并使把手卡入到位。
+
请务必缓慢地关闭凸轮把手，使其与驱动器正面正确对齐。



.. 验证驱动器的活动（绿色） LED 是否亮起。
+
如果驱动器的活动 LED 稳定亮起，则表示驱动器已通电。当驱动器的活动 LED 闪烁时，表示驱动器已通电且 I/O 正在进行中。如果驱动器固件正在自动更新，则 LED 将闪烁。

.. 如果要更换另一个驱动器，请重复步骤 3 至 7 。
.. 如果您在步骤 1 中禁用了自动驱动器分配，则手动分配驱动器所有权，然后根据需要重新启用自动驱动器分配。
+
... 显示所有未分配的驱动器： `storage disk show -container-type unassigned`
+
您可以在任一控制器模块上输入命令。

... 分配每个驱动器： `storage disk assign -disk disk_name -owner owner_name`
+
您可以在任一控制器模块上输入命令。

+
您可以使用通配符一次分配多个驱动器。

... 如果需要，请重新启用自动驱动器分配： `storage disk option modify -node node_name -autodassign on`
+
您必须在两个控制器模块上重新启用自动驱动器分配。



.. 按照套件随附的 RMA 说明将故障部件退回 NetApp 。
+
请通过联系技术支持 https://["NetApp 支持"]， 888-463-8277 （北美）， 00-800-44-638277 （欧洲）或 +800-800-80-800 （亚太地区）（如果您需要 RMA 编号或有关更换操作步骤的其他帮助）。




