---
permalink: platform-supplemental/sldiag-system-installation-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, initial, system, installation, identify, version, system-level, diagnostic, support, device, storage, system, successful, hardware, function, properly, run system installation diagnostic 
summary: 您可以在初始系统安装后运行诊断，以确定系统级诊断的版本以及存储系统上支持的设备，并验证安装是否成功以及所有硬件是否正常运行。 
---
= 运行系统安装诊断
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在初始系统安装后运行诊断，以确定系统级诊断的版本以及存储系统上支持的设备，并验证安装是否成功以及所有硬件是否正常运行。

存储系统必须已运行 Data ONTAP 。

. 在存储系统提示符处，切换到 LOADER 提示符： `halt`
. 在 LOADER 提示符处输入以下命令： `boot_diags`
+

NOTE: 您必须从 LOADER 提示符处运行此命令，系统级诊断才能正常运行。boot_diags 命令会启动专为系统级诊断而设计的特殊驱动程序。

. 输入以下命令以查看存储系统上的系统级诊断版本： `sldiag version show`
+
此版本的显示格式为 System Level 诊断 x.nn.nn 。X 是字母引用， nn.nn 分别是主要引用和次要引用。

. 输入以下命令，确定新系统安装中的设备类型，以了解要验证的组件： `sldiag device types`
+
您的存储系统将显示以下部分或全部设备：

+
** `ata` 是一种高级技术附件设备。
** `bootmedia` 是系统启动设备。
** `CNA` 是未连接到网络或存储设备的融合网络适配器。
** `env` 是主板环境。
** `fcache` 是 Flash Cache 适配器，也称为性能加速模块 2 。
** `FCAL` 是未连接到存储设备或光纤通道网络的光纤通道仲裁环路设备。
** `fcvi` 是未连接到光纤通道网络的光纤通道虚拟接口。
** `interconnect` 或 `nvram-ib` 是高可用性接口。
** MEM 是系统内存。
** `NIC` 是未连接到网络的网络接口卡。
** `NVRAM` 是非易失性 RAM 。
** `nvmem` 是 NVRAM 和系统内存的混合。
** `sas` 是未连接到磁盘架的串行连接 SCSI 设备。
** `serviceproc` 是服务处理器。
** `storage` 是已连接磁盘架的 ATA ， FC-AL 或 SAS 接口。
** `toe` 是一种 TCP 卸载引擎，一种 NIC 。


. 输入以下命令，在存储系统上运行所有默认选定的诊断测试： `sldiag device run`
. 输入以下命令以查看测试状态： `sldiag device status`
+
在测试仍在运行时，存储系统会提供以下输出：

+
[listing]
----
There are still test(s) being processed.
----
+
完成所有测试后，默认情况下会显示以下响应：

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 输入以下命令，验证新存储系统上是否没有硬件问题： `sldiag device status -long -state failed`
+
以下示例显示了在没有相应硬件的情况下运行测试时如何显示故障的完整状态：

+
[listing]
----

*> **sldiag device status -long -state failed**

TEST START ------------------------------------------
DEVTYPE: nvram_ib
NAME: external  loopback test
START DATE: Sat Jan  3 23:10:55 GMT 2009

STATUS: Completed
ib3a: could not set loopback mode, test failed
END DATE: Sat Jan  3 23:11:04 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| 如果系统级诊断测试 ... | 那么 ... 


 a| 
已完成，无任何故障
 a| 
没有硬件问题，存储系统将返回到提示符。

.. 输入以下命令以清除状态日志： `sldiag device clearstatus`
.. 输入以下命令以验证是否已清除日志： `sldiag device status`
+
此时将显示以下默认响应：

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 输入以下命令退出维护模式： `halt`
.. 在 Loader 提示符处输入以下命令以启动存储系统： `boot_ontap` 您已完成系统级诊断。




 a| 
导致某些测试失败
 a| 
确定问题的发生原因。

.. 输入以下命令退出维护模式： `halt`
.. 执行完全关闭并断开电源。
.. 验证您是否已遵循在运行系统级诊断时确定的所有注意事项，缆线是否已牢固连接以及硬件组件是否已正确安装在存储系统中。
.. 重新连接电源并打开存储系统的电源。
.. 重复 _running system installation diagnostics_的 步骤 1 到 7 。


|===

