---
permalink: platform-supplemental/sldiag-requirements.html 
sidebar: sidebar 
keywords: system-level, diagnostic, test, run, time, system, requirement, system, memory, general, nic, sas, fc-al, cna, interconnect, requirement for running system-level diagnostic 
summary: 根据您正在运行的系统级诊断测试，您需要了解时间和系统硬件要求。 
---
= 运行系统级诊断的要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根据您正在运行的系统级诊断测试，您需要了解时间和系统硬件要求。

每个记录的任务都略有不同；请使用建议的操作步骤执行此任务。

运行系统级诊断时，必须满足以下要求；否则，部分测试将失败，并且状态报告中会显示错误消息：



== 一般要求

* 要测试的每个系统都必须位于一个单独的网络上。
+
网络接口测试会从 172.25.150.23 开始为存储系统上的所有可用网络接口分配唯一的静态 IP 地址。这会导致为不同存储控制器上的网络接口端口分配相同的 IP 地址。如果要测试的所有系统都位于同一网络上，则连接的控制台会显示重复的 IP 地址警告消息。这些警告消息不会影响测试结果。





== 系统内存要求

* 运行内存测试时需要留出时间；存储系统的内存容量越大，所需时间越长。




== NIC 要求

* 必须使用标准以太网缆线连接系统上的所有相邻网络接口端口，以获得最佳性能。
+
相邻端口的示例为 e0a 和 e0b 或 e2C 和 e2d 。

+

NOTE: 由于内部交换机连接， e0M 和 e0P 端口无法连接在一起。在具有 e0M 和 e0P 端口的系统中，最高效的配对是 e0M 与 e0a ， e0P 与 e0b 。

* 如果系统上有多个网络接口端口，则可能需要多次运行 NIC 系统级诊断测试，每次运行限制为不超过两对。




== SAS 要求

* 运行 SAS 系统级诊断测试时，必须连接相邻的 SAS 端口以获得最佳性能；存储架必须与端口断开连接。
+

NOTE: 对于运行 Data ONTAP 8.2 的系统，不再需要在相邻 SAS 端口之间进行连接；但是，对于未连接 SAS 端口的系统，只会运行内部环回测试。





== FC-AL 要求

* 运行 FC-AL 系统级诊断测试时，您必须在主板或扩展适配器的 FC-AL 接口上安装环回罩，以获得最佳性能；存储或光纤通道网络的所有其他缆线必须与端口断开连接。
+

NOTE: 虽然运行 Data ONTAP 8.2 的系统不再要求在 FC-AL 接口上使用环回罩，但该接口的测试覆盖范围也会缩小。





== CNA 要求

* 运行 CNA 系统级诊断测试时，不需要使用环回罩。




== 互连要求

* 双控制器系统中的两个平台控制器模块都必须处于维护模式，才能运行互连系统级诊断测试。
+

NOTE: 如果您尝试使用其他系统级诊断测试运行互连系统级诊断测试，则会收到警告消息。


