---
permalink: platform-supplemental/sldiag-introduction.html 
sidebar: sidebar 
keywords: system-level, diagnostic, command-line, interface, test, search, hardware, problem, storage, system, component, operating, identify, faulty, component, introduction, introduction to system-level diagnostic 
summary: 系统级诊断可通过命令行界面进行测试，以搜索并确定受支持存储系统上的硬件问题。您可以使用系统级诊断来确认特定组件运行正常或帮助确定故障组件。 
---
= ‑级别诊断简介
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系统级诊断可通过命令行界面进行测试，以搜索并确定受支持存储系统上的硬件问题。您可以使用系统级诊断来确认特定组件运行正常或帮助确定故障组件。

系统级诊断仅适用于受支持的存储系统。在不受支持的存储系统的命令行界面中输入系统级诊断会生成一条错误消息。

在出现以下常见故障排除情况之一后，您可以运行系统级诊断：

* 初始系统安装
* 添加或更换硬件组件
* 由未标识的硬件故障导致的系统崩溃
* 对特定设备的访问将会间歇性发生，或者该设备将不可用
* 系统响应时间变得缓慢


要运行系统级诊断，必须已运行 Data ONTAP ，因为您需要访问 Data ONTAP 中的 * 维护模式启动 * 选项。可以通过多种方法使用此选项，但本指南中记录的过程建议采用这种方法。系统中的某些硬件组件可能需要特定方法，相关的现场可更换单元（ Field Replaceable Unit ， FRU ）宣传单会对此进行说明。本指南不详细介绍特定命令，子命令，测试或条件。

输入命令后，测试将在后台运行，测试通过或失败的结果将记录在基于内存的内部日志中，该日志大小固定。某些测试是实用程序，只会指出已完成，而不是通过或失败。运行相应的测试后，本指南中介绍的过程可帮助您生成状态报告。一旦测试结果显示成功完成系统级诊断，建议清除日志。

如果测试失败，状态报告将帮助技术支持提出适当的建议。要解决此故障，可以重新安装 FRU ，确保已连接电缆，或者启用技术支持建议的特定测试，然后重新运行这些测试。如果无法解决此故障，则表示出现硬件故障，必须更换受影响的硬件。

没有需要进一步定义或说明的错误消息。
