---
permalink: sas3/install-change-shelf-id.html 
sidebar: sidebar 
keywords: change, shelf, id, system, ontap, run, hot-add, ontap, controller, module, available, serve, data, unown, spare, offline, aggregate 
summary: 当 ONTAP 尚未运行或在将磁盘架连接到系统之前热添加磁盘架时，您可以更改系统中的磁盘架 ID 。您也可以在 ONTAP 启动并运行 \ （控制器模块可用于提供数据 \ ）且磁盘架中的所有驱动器均为无所有者，备用或脱机聚合的一部分时更改磁盘架 ID 。 
---
= 更改机架 ID - DS212C、DS224C 或 DS460C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在配备 IOM12/IOM12B 模块的系统中，您可以在ONTAP尚未运行或在将磁盘架连接到系统之前进行热添加时更改磁盘架 ID。您还可以在ONTAP已启动并运行（控制器模块可用于提供数据）且磁盘架中的所有驱动器均为无主驱动器、备用驱动器或属于已脱机聚合体时更改磁盘架 ID。

.关于此任务
* 有效磁盘架 ID 为 00 到 99 。
* 在 HA 对或单控制器配置中，磁盘架 ID 必须是唯一的。
+
如果您的平台具有内部存储，则磁盘架 ID 必须在内部磁盘架和任何外部连接的磁盘架之间是唯一的。

* 您必须重新启动磁盘架才能使磁盘架 ID 生效。
+
重新打开电源之前等待的时间取决于 ONTAP 的状态，如本操作步骤后面所述。



.开始之前
* 如果 ONTAP 已启动且正在运行（控制器模块可用于提供数据），则必须已验证磁盘架中的所有驱动器是否为无主聚合，备用聚合或脱机聚合的一部分。
+
您可以使用 `storage disk show -shelf _shelf_number_` 命令验证驱动器的状态。如果驱动器发生故障，则 Container Type 列中的输出应显示 spare 或 broken 。此外， Container Name 和 owner 列应包含一个短划线。

* 您可以通过运行Active IQ Config Advisor或使用 `storage shelf show -fields shelf-id`命令。您可以 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["下载并访问Active IQ Config Advisor"]在NetApp支持站点上。


.步骤
. 如果磁盘架尚未打开，请打开其电源。
. 取下左端盖，找到靠近磁盘架 LED 的按钮。
. 按住橙色按钮，直到数字显示屏上的第一个数字闪烁，这可能需要长达三秒钟的时间，从而更改磁盘架 ID 的第一个数字。
+
[NOTE]
====
如果此 ID 闪烁所需时间超过三秒，请再次按此按钮，确保一直按此按钮。

此操作将激活磁盘架 ID 编程模式。

====
. 按按钮将此数字向前移动，直到达到所需数字 0 到 9 。
+
第一个数字将继续闪烁。

. 按住此按钮，直到数字显示屏上的第二个数字闪烁，这可能需要长达三秒的时间，从而更改磁盘架 ID 的第二个数字。
+
数字显示屏上的第一个数字停止闪烁。

. 按按钮将此数字向前移动，直到达到所需数字 1 到 9 。
+
第二个数字将继续闪烁。

. 锁定所需的数字，然后按住按钮退出编程模式，直到第二个数字停止闪烁，这可能需要长达三秒钟的时间。
+
数字显示屏上的两个数字开始闪烁，操作员显示屏面板上的琥珀色 LED 在大约 5 秒钟后亮起，提醒您待定磁盘架 ID 尚未生效。

. 重新启动磁盘架以使磁盘架 ID 生效。
+
您必须关闭两个电源开关，等待适当的时间，然后重新打开它们，才能完成重新启动。

+
** 如果 ONTAP 尚未运行或您要热添加磁盘架（尚未通过缆线连接到系统），请至少等待 10 秒钟。
** 如果ONTAP正在运行（控制器可用于提供数据），并且机架中的所有磁盘驱动器均为无人拥有、备用或脱机聚合的一部分，则等待至少 120 秒。
+
此时， ONTAP 可以正确删除旧磁盘架地址并更新新磁盘架地址的副本。



. 更换左端盖。
. 对每个额外的磁盘架重复上述步骤。
. 验证您的系统没有重复的磁盘架 ID 。
+
如果两个或更多磁盘架具有相同的 ID ，系统会为重复的磁盘架分配一个等于或大于 100 的软 ID 编号。您必须更改软 ID （重复）编号。

+
.. 运行 Active IQ Config Advisor 检查是否存在重复的磁盘架 ID 警报，或者运行 `storage shelf show -fields shelf-id` 命令查看已在使用的磁盘架 ID 列表，包括任何重复的 ID 。
.. 如果您的系统具有任何重复的磁盘架 ID ，请重复执行此操作步骤以更改重复的磁盘架 ID 。



