---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, diagnostic, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, run diagnostics, complete the replacement process 
summary: 将受损机箱中的风扇，硬盘驱动器和控制器模块或模块移至新机箱，然后将受损机箱从设备机架或系统机柜中更换为与受损机箱型号相同的新机箱。 
---
= 移动并更换硬件— AFF A320
:icons: font
:imagesdir: ../media/




== 第 1 步：卸下控制器模块

[role="lead"]
要更换机箱，必须从旧机箱中卸下控制器模块。

. 如果您尚未接地，请正确接地。
. 释放电源线固定器，然后从电源中拔下缆线。
. 松开将缆线绑在缆线管理设备上的钩环带，然后从控制器模块上拔下系统缆线和 SFP （如果需要），并跟踪缆线的连接位置。
+
将缆线留在缆线管理设备中，以便在重新安装缆线管理设备时，缆线排列有序。

. 从控制器模块的左右两侧卸下缆线管理设备并将其放在一旁。
. 从机箱中卸下控制器模块：
+
.. 将前掌插入控制器模块两侧的锁定装置。
.. 向下按压闩锁装置顶部的橙色卡舌，直到其脱离机箱上的闩锁销。
+
闩锁机制挂钩应接近垂直，并且应远离机箱销。

.. 将控制器模块轻轻向您的方向拉几英寸，以便抓住控制器模块两侧。
.. 用双手将控制器模块轻轻拉出机箱，并将其放在平稳的表面上。


. 对机箱中的另一个控制器模块重复上述步骤。




== 第 2 步：移动风扇

[role="lead"]
要在更换机箱时将风扇模块移至更换机箱，您必须执行一系列特定的任务。

. 如果您尚未接地，请正确接地。
. 如有必要，请用两只手抓住挡板每一侧的开口，然后将其拉向您，直到挡板从机箱框架上的球形螺柱上松开，从而卸下挡板。
. 向下按风扇模块凸轮把手上的释放闩锁，然后向下旋转凸轮把手。
+
风扇模块会从机箱中移出一点。

. 将风扇模块从机箱中竖直拉出，确保用您的空闲手托住该模块，使其不会从机箱中摆出。
+
* 小心： *

+
风扇模块较短。请始终用您的空闲手托住风扇模块的底部，以免其突然从机箱中脱离并造成您的人身伤害。

. 将风扇模块放在一旁。
. 对其余所有风扇模块重复上述步骤。
. 将风扇模块与开口对齐，然后将其滑入机箱，从而将其插入更换机箱。
. 用力推动风扇模块凸轮把手，使其完全固定到机箱中。
+
风扇模块完全就位后，凸轮把手会略微升高。

. 将凸轮把手向上旋转到其闭合位置，确保凸轮把手释放闩锁卡入到锁定位置。
+
风扇固定到位后，风扇 LED 应呈绿色亮起，并且转速已达到运行速度。

. 对其余风扇模块重复上述步骤。




== 第 3 步：从设备机架或系统机柜中更换机箱

[role="lead"]
您必须先从设备机架或系统机柜中卸下现有机箱，然后才能安装替代机箱。

. 从机箱安装点卸下螺钉。
. 两个人将旧机箱滑出系统机柜或设备机架中的机架导轨，然后放好备用。
. 如果您尚未接地，请正确接地。
. 由两个人将更换机箱安装到设备机架或系统机架中，方法是将机箱安装到系统机柜或设备机架中的机架导轨上。
. 将机箱完全滑入设备机架或系统机柜中。
. 使用从旧机箱中卸下的螺钉将机箱前部固定到设备机架或系统机柜。
. 如果尚未安装挡板，请安装挡板。




== 第 4 步：安装控制器模块

[role="lead"]
将控制器模块安装到新机箱中后，您需要将其启动到可以运行诊断测试的状态。

对于在同一机箱中具有两个控制器模块的 HA 对，安装控制器模块的顺序尤为重要，因为一旦将其完全装入机箱，它就会尝试重新启动。

. 将控制器模块的末端与机箱中的开口对齐，然后将控制器模块轻轻推入系统的一半。
+

NOTE: 请勿将控制器模块完全插入机箱中，除非系统指示您这样做。

. 将控制台重新连接到控制器模块，然后重新连接管理端口。
. 将电源线插入电源，然后重新安装电源线固定器。
. 完成控制器模块的重新安装：
+
.. 确保闩锁臂锁定在扩展位置。
.. 使用闩锁臂将控制器模块推入机箱托架，直到其停止。
.. 按住锁定机制顶部的橙色卡舌。
.. 将控制器模块轻轻推入机箱托架，直至其与机箱边缘平齐。
+

NOTE: 锁定机制臂滑入机箱。

+
控制器模块一旦完全固定在机箱中，就会开始启动。

.. 释放闩锁，将控制器模块锁定到位。
.. 已重新连接电源。
.. 如果尚未重新安装缆线管理设备，请重新安装该设备。
.. 按 `Ctrl-C` 以中断正常启动过程。


. 重复上述步骤，将第二个控制器安装到新机箱中。

