---
permalink: fas500f/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas500f, shutdown the controllers 
summary: 要更换机箱，必须关闭控制器。 
---
= 关闭控制器— FAS500f
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须先关闭机箱中的一个或多个节点，然后才能将其移至新机箱。

.关于此任务
* If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的节点在资格和运行状况方面显示 `false` ，则必须在关闭受损节点之前更正问题描述；请参见 https://docs.netapp.com/us-en/ontap/system-admin/index.html["CLI 管理概述"]。
* 如果启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
以下 AutoSupport 消息禁止自动创建案例两小时： `cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`



.步骤
. 如果您的系统有两个控制器模块，请禁用 HA 对。
+
[cols="1,2"]
|===
| 如果您的系统运行的是集群模式 ONTAP | 那么 ... 


 a| 
集群中的两个节点
 a| 
`cluster ha modify -configured false` `storage failover modify -node node0 -enabled false`



 a| 
集群中的两个以上节点
 a| 
`storage failover modify -node node0 -enabled false`

|===
. 暂停节点，在系统提示您确认 halt 时按 `y` ： `ssystem node halt -node node_name`
+
确认消息如下所示：

+
[listing]
----
Warning: Rebooting or halting node
"node_name" in an HA-enabled cluster may result in client disruption or data access
failure. To ensure continuity of service, use the "storage
failover takeover" command. Are you sure you want to halt node
"node_name"? {y|n}:
----
+

NOTE: 在更换机箱之前，您必须完全关闭系统，以避免丢失非易失性内存（ NVMEM ）中未写入的数据。如果 NVMEM LED 闪烁，则表示 NVMEM 中有尚未保存到磁盘的内容。您需要重新启动节点并从此操作步骤开始。如果重复尝试完全关闭节点失败，请注意，未保存到磁盘的任何数据可能会丢失。

. 如果适用，请暂停第二个节点以避免在 HA 对配置中出现可能的仲裁错误消息： `ssystem node halt -node second_node_name -ignore-quorum-warnings true`

