---
permalink: a800/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a800, shutdown the controllers 
summary: 要更换机箱，必须关闭控制器。 
---
= 关闭控制器— AFF A800
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须先关闭机箱中的一个或多个节点，然后才能将其移至新机箱。

.关于此任务
* If you have a cluster with more than two nodes, it must be in quorum.If the cluster is not in quorum or a healthy node shows `false` for eligibility and health, you must correct the issue before shutting down the impaired node.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["_ONTAP 9 System Administration Reference_"]

* 如果启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
以下 AutoSupport 消息禁止自动创建案例两小时： `cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`



.步骤
. 如果您的系统有两个控制器模块，请禁用 HA 对。
+
[cols="1,2"]
|===
| 如果您的系统运行的是集群模式 ONTAP | 那么 ... 


 a| 
集群中的两个节点
 a| 
`cluster ha modify -configured false` `storage failover modify -node node0 -enabled false`



 a| 
集群中的两个以上节点
 a| 
`storage failover modify -node node0 -enabled false`

|===
. 暂停节点，在系统提示您确认暂停时按 `y` ： `ssystem node halt -node _node_name_`
+
确认消息如下所示：

+
[listing]
----
Warning: This operation will cause node "node-name" to be marked as unhealthy. Unhealthy nodes do not participate in quorum voting. If the node goes out of service and one more node goes out of service there will be a data serving failure for the entire cluster. This will cause a client disruption. Use "cluster show" to verify cluster state. If possible bring other nodes online to improve the resiliency of this cluster.

Do you want to continue? {y|n}:
----
+

NOTE: 在更换机箱之前，您必须完全关闭系统，以避免丢失非易失性内存（ NVMEM ）中未写入的数据。如果 NVMEM LED 闪烁，则表示 NVMEM 中有尚未保存到磁盘的内容。您需要重新启动节点并从此操作步骤开始。如果重复尝试完全关闭节点失败，请注意，未保存到磁盘的任何数据可能会丢失。

. 如果适用，请暂停第二个节点以避免在 HA 对配置中出现可能的仲裁错误消息： `ssystem node halt -node _second_node_name_ -ignore-quorum-warnings true -skip-lif-migration-before-shutdown true`
+
出现提示时，请选择问题解答 `y` 。


