---
permalink: fas8200/bootmedia-2n-mcc-switchback.html 
sidebar: sidebar 
keywords: fas8200, switch back aggregate in a two-node metrocluster configuration, manual, manual boot recovery 
summary: 在双节点MetroCluster配置中完成启动介质更换后，对FAS8200系统执行MetroCluster切换回操作。FAS8200系统仅支持手动启动介质恢复程序。不支持自动启动介质恢复。 
---
= 切回双节点 MetroCluster 配置中的聚合— FAS8200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在双节点MetroCluster配置中完成启动介质更换后，对FAS8200系统执行MetroCluster切换回操作。此过程包括验证节点和存储虚拟机 (SVM) 的状态，执行回退命令，并确认配置恢复到正常运行状态，同步源 SVM 从本地磁盘池提供数据。

FAS8200系统仅支持手动启动介质恢复程序。不支持自动启动介质恢复。

此任务仅限适用场景双节点 MetroCluster 配置。

.步骤
. 验证所有节点是否处于 `enabled` 状态： `MetroCluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 验证所有 SVM 上的重新同步是否已完成： `MetroCluster SVM show`
. 验证修复操作正在执行的任何自动 LIF 迁移是否已成功完成： `MetroCluster check lif show`
. 在运行正常的集群中的任何节点上使用 `MetroCluster switchback` 命令执行切回。
. 验证切回操作是否已完成： `MetroCluster show`
+
当集群处于 `waiting for-switchback` 状态时，切回操作仍在运行：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
当集群处于 `normal` 状态时，切回操作完成。：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切回需要很长时间才能完成，您可以使用 `MetroCluster config-replication resync-status show` 命令检查正在进行的基线的状态。

. 重新建立任何 SnapMirror 或 SnapVault 配置。

