---
permalink: afx-1k/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: afx 1k,  verify and set HA state, complete the replacement process 
summary: 重新启动控制器，验证系统健康状况，并将故障部件返回给NetApp ，以完成AFF A1K机箱更换程序的最后一步。 
---
= 完成底盘更换 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重新启动控制器，验证系统健康状况，并将故障部件返回给NetApp ，以完成 AFX 1K 机箱更换程序的最后一步。



== 第1步：启动控制器并交还控制器

控制器重新启动后、启动ONTAP并交还控制器。

.步骤
. Check the console output:
+
.. 如果控制器在 LOADER 提示符处停止，则使用 `boot_ontap`命令。
.. 节点启动并提供登录提示后，登录合作伙伴控制器并检查更换的控制器是否已准备好进行交还 `storage failover show`命令。


. 执行回给：
+
.. 将控制台缆线连接到配对控制器。
.. 当控制台消息停止时、按<enter>。
+
*** 如果您看到_login_提示，请转到下一步。
*** 如果您没有看到登录提示，请登录合作伙伴节点。


.. 仅返回具有 override-destination-checks 选项的根：
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 以下命令仅在诊断模式权限级别下可用。有关权限级别的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 命令的权限级别"^]。

+
如果遇到错误，请联系 https://support.netapp.com["NetApp 支持"]。

.. 在恢复报告完成后等待5分钟、然后检查故障转移状态和恢复状态：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令仅在诊断模式权限级别下可用。

.. 如果 HA 互连链路已断开，请将其恢复：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

.. 通过交还存储使受损控制器恢复正常运行：
+
`storage failover giveback -ofnode _impaired_node_name_`

.. 如果自动交还功能已禁用，请重新启用它： `storage failover modify -node _impaired_node_name_ -auto-giveback-of _true_`
.. 如果启用了AutoSupport、则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`






== 第2步：验证存储系统运行状况

控制器归还存储后，使用 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。

.步骤
. 完成恢复后、运行Active IQ Config Advisor以验证存储系统的运行状况。
. 更正您遇到的任何问题。




== 第 3 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"]有关详细信息、请参见页面。
