---
permalink: afx-1k/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: afx 1k, how to recable the system, how to reassign disks 
summary: 将存储资源的控制权交还给替换控制器，以便您的 AFX 1K 存储系统可以恢复正常运行。 
---
= 归还控制器 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将存储资源的控制权交还给替换控制器，以便您的 AFX 1K 存储系统可以恢复正常运行。恢复过程根据系统使用的加密类型而有所不同：无加密或板载密钥管理器 (OKM) 加密。

[role="tabbed-block"]
====
.无加密
--
通过交还存储使受损控制器恢复正常运行。

.步骤
. 在 LOADER 提示符下输入
+
`boot_ontap`

. 当控制台消息停止时、按<enter>。
+
** 如果看到_login"提示符、请转到本节末尾的下一步。
** 如果没有看到登录提示，请按<enter>键，如果仍然没有提示，请登录到合作伙伴节点。


. 仅返回具有 override-destination-checks 选项的根：
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 以下命令仅在诊断模式权限级别下可用。有关权限级别的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 命令的权限级别"^]。

+
如果遇到错误，请联系 https://support.netapp.com["NetApp 支持"]。

. 等待交还报告完成后 5 分钟，然后检查故障转移和交还状态：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令仅在诊断模式权限级别下可用。

. 如果 HA 互连链路已断开，请将其恢复：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. 通过交还存储使受损控制器恢复正常运行：
+
`storage failover giveback -ofnode _impaired_node_name_`

. 如果已禁用自动交还、请重新启用它：
+
`storage failover modify -node local -auto-giveback-of true`

. 如果启用了AutoSupport、则还原/取消禁止自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.OKM加密
--
重置板载加密并使控制器恢复正常运行。

.步骤
. 在Loader提示符处、输入：
+
`boot_ontap maint`

. 从Loader提示符处启动到ONTAP菜单 `boot_ontap menu`、然后选择选项10。
. 输入OKM密码短语。您可以从客户处获取此密码短语，也可以联系 https://support.netapp.com["NetApp 支持"]。
+

NOTE: 系统将提示您输入密码短语两次。

. 出现提示时、输入备份密钥数据。
. 在启动菜单中、输入选项 `1`进行正常启动。
. 将控制台电缆移至合作伙伴节点并输入以下登录信息：
+
`admin`

. 仅返回具有 override-destination-checks 选项的根：
+
`storage  failover giveback -ofnode impaired-node -only-root true -override-destination-checks true`

+

NOTE: 以下命令仅在诊断模式权限级别下可用。有关权限级别的更多信息，请参阅link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["了解ONTAP CLI 命令的权限级别"^]。

+
如果遇到错误，请联系 https://support.netapp.com["NetApp 支持"]。

. 等待交还报告完成后 5 分钟，然后检查故障转移和交还状态：
+
`storage failover show`和 `storage failover show-giveback`

+

NOTE: 以下命令仅在诊断模式权限级别下可用。

. 将控制台电缆移至替换节点并输入以下内容：
+
`security key-manager onboard sync`

+

NOTE: 系统将提示您为此集群输入集群范围的OKM密码短语。

. 使用以下命令检查密钥的状态：
+
`security key-manager key query -key-type svm-KEK`

+
如果_Restored_列显示_TRUE_以外的内容，请联系 https://support.netapp.com["NetApp 支持"]。

. 通过交还存储使受损控制器恢复正常运行：
+
`storage failover giveback -ofnode _impaired_node_name_`

+
.. 如果 HA 互连链路已断开，请将其恢复以恢复自动交还：
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



. 如果已禁用自动交还、请重新启用它：
+
`storage failover modify -node local -auto-giveback-of true`

. 如果启用了AutoSupport、则还原/取消禁止自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
====
.下一步是什么？
将存储资源所有权转移至更换控制器后，link:controller-replace-restore-system-rma.html["完成更换控制器"] 。
