---
permalink: asa150/overview.html 
sidebar: sidebar 
keywords: ASA A150 specifications, ASA A150 specs, NetApp ASA A150, ASA A150 hardware 
summary: ASA A150存储系统的主要规格 
---
= ASA A150的主要规格
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下是ASA A150的精选规格。访问 https://hwu.netapp.com["NetApp Hardware Universe"^]（HWU）获取ASA A150规格的完整列表。此页面反映的是单个高可用性对。



=== ASA A150的主要规格

平台配置： ASA A150 UTA2 单机箱 HA 对

最大原始容量：0.5472 PB

内存：64.0000 GB

外形尺寸：2U 机箱，配备 2 个 HA 控制器和 24 个驱动器插槽

ONTAP版本：b_startONTAP：9.16.1P2b_end

PCIe 扩展槽：

最低ONTAP版本： ONTAP 9.13.1



=== 横向扩展最大值

|===


| 类型 | HA 对 | 原始容量 | 最大内存 


| NAS |  |  |  


| SAN | 6 | 3.3 PB / 2.9 PiB | 384 GB 


| HA 对 |  | 0.5 PB / 0.5 PiB | 64.0000 
|===


=== 输入输出



==== 板载 IO

|===


| 协议 | 端口 


| 以太网 10 Gbps | 12 


| 光纤通道 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== 总 IO

|===


| 协议 | 端口 


| 以太网 10 Gbps | 12 


| 光纤通道 16 Gbps | 8 


| SAS 12 Gbps | 4 
|===


==== 管理端口

|===


| 协议 | 端口 


| 以太网 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2. 
|===


=== 支持的存储网络

光纤通道；iSCSI；NVMe/TCP；



=== 系统环境规格

没有可用的环境数据。



=== Compliance

* EMC/EMI 认证：AMCA、FCC、ICES、KC、摩洛哥、VCCI
* 安全认证：BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 安全/EMC/EMI认证：EAC、UKRSEPRO
* 认证安全/EMC/EMI/RoHS：BSMI、CE DoC、UKCA DoC
* 标准 EMC/EMI：BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC 第 15 部分 A 类、ICES-003、KS C 9832、KS C 9835
* 标准安全：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（第 1 部分）




=== 高可用性

基于以太网的基板管理控制器 (BMC) 和ONTAP管理接口；冗余热插拔控制器；冗余热插拔电源；通过 SAS 连接进行 SAS 带内管理；[//] 2025-10-15 ontap-systems-internal/issues/1357
