---
permalink: fas9500/add_io_module.html 
sidebar:  
keywords:  
summary: 您可以将 I/O 模块添加到系统中，方法是在已完全填充的系统中将现有 I/O 模块更换为新的 I/O 模块，或者将新的 I/O 模块添加到机箱中的空插槽中。 
---
= 添加一个I/O模块—FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以通过在已完全填充的系统中将 NIC 或存储适配器更换为新的 NIC 或存储适配器，或者将新的 NIC 或存储适配器添加到系统中的空机箱插槽中来向系统添加 I/O 模块。

.开始之前
* 检查 https://hwu.netapp.com/["NetApp Hardware Universe"] 确保新 I/O 模块与您正在运行的系统和 ONTAP 版本兼容。
* 如果有多个可用插槽，请在中检查插槽优先级 https://hwu.netapp.com/["NetApp Hardware Universe"] 并使用适用于您的 I/O 模块的最佳配置。
* 要无中断地添加 I/O 模块，您必须接管目标控制器，卸下目标插槽中的插槽空白盖或卸下现有 I/O 模块，添加新的或更换的 I/O 模块，然后交还目标控制器。
* 确保所有其他组件均正常运行。




== 选项 1 ：将 I/O 模块添加到插槽已打开的系统中

您可以将I/O模块作为NIC或SAS存储架的存储模块添加到系统中的空模块插槽中。

. 关闭控制器 A ：
+
.. 禁用自动交还： `storage failover modify -node local -auto-giveback false`
.. 接管目标节点： `storage failover takeover -ofnode target_node_name`
+
控制台连接显示，接管完成后，节点将进入 LOADER 提示符。



. 如果您尚未接地，请正确接地。
. 卸下目标插槽空白盖：
+
.. 按下带字母和编号的凸轮按钮。
.. 向下旋转凸轮闩锁，直到其处于打开位置。
.. 拆下空白盖板。


. 安装 I/O 模块：
+
.. 将 I/O 模块与插槽边缘对齐。
.. 将 I/O 模块滑入插槽，直到带字母和编号的 I/O 凸轮闩锁开始与 I/O 凸轮销接合。
.. 将 I/O 凸轮闩锁完全向上推，以将模块锁定到位。


. 如果更换用的 I/O 模块是 NIC ，请使用缆线将此模块连接到数据交换机。
+

NOTE: 确保所有未使用的 I/O 插槽都安装了空格，以防止可能出现散热问题。

. 从 LOADER 提示符 _bybye 重新启动控制器
+

NOTE: 此操作将重新初始化PCIe卡和其他组件、并重新启动节点。

. 从配对节点交还节点。`storage failover giveback -ofnode target_node_name`
. 如果已禁用，请启用自动交还： `storage failover modify -node local -auto-giveback true`
. 如果您使用插槽 3 和 / 或 7 进行网络连接，请使用 `storage port modify -node _<node name>_ -port _<port name>__ -mode network` 命令转换插槽以供网络连接使用。
. 对控制器 B 重复上述步骤
. 如果您安装了存储I/O模块、请按照中所述安装SAS磁盘架并为其布线 https://docs.netapp.com/us-en/ontap-systems/sas3/install-hot-add-shelf.html["热添加SAS磁盘架"^]。




== 选项 2 ：在没有打开插槽的系统中添加 I/O 模块

您必须删除系统中的一个或多个现有 NIC 或存储模块，才能将一个或多个 I/O 模块安装到已完全填充的系统中。

. 如果您是：
+
[cols="1,2"]
|===
| 替换 ... | 那么 ... 


 a| 
具有相同端口数的 NIC I/O 模块
 a| 
LIF 将在其控制器模块关闭时自动迁移。



 a| 
NIC I/O 模块，端口更少
 a| 
将受影响的 LIF 永久重新分配到其他主端口。请参见 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["迁移 LIF"^] 有关使用 System Manager 永久移动 LIF 的信息，请参见。



 a| 
带有存储 I/O 模块的 NIC I/O 模块
 a| 
使用 System Manager 将 LIF 永久迁移到不同的主端口，如中所述 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["迁移 LIF"^]。

|===
. 关闭控制器 A ：
+
.. 禁用自动交还： `storage failover modify -node local -auto-giveback false`
.. 接管目标节点： `storage failover takeover -ofnode target_node_name`
+
控制台连接显示，接管完成后，节点将进入 LOADER 提示符。



. 如果您尚未接地，请正确接地。
. 拔下目标 I/O 模块上的所有布线。
. 从机箱中卸下目标 I/O 模块：
+
.. 按下带字母和编号的凸轮按钮。
+
凸轮按钮离开机箱。

.. 向下旋转凸轮闩锁，直到其处于水平位置。
+
I/O 模块从机箱中分离，并从 I/O 插槽中移出大约 1/2 英寸。

.. 拉动 I/O 模块侧面的拉片，将 I/O 模块从机箱中卸下。
+
确保跟踪 I/O 模块所在的插槽。

+
.动画-更换I/O模块
video::0903b1f9-187b-4bb8-9548-ae9b0012bb21[panopto]
+
image::../media/drw_9500_remove_PCIe_module.svg[DRW 9500-卸下PCIe模块]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
I/O 凸轮闩锁有字母和编号



 a| 
image::../media/legend_icon_02.svg[图例图标 02]
 a| 
I/O 凸轮闩锁完全解锁

|===


. 将 I/O 模块安装到目标插槽中：
+
.. 将 I/O 模块与插槽边缘对齐。
.. 将 I/O 模块滑入插槽，直到带字母和编号的 I/O 凸轮闩锁开始与 I/O 凸轮销接合。
.. 将 I/O 凸轮闩锁完全向上推，以将模块锁定到位。


. 重复执行拆卸和安装步骤以更换控制器 A 的其他模块
. 如果更换用的 I/O 模块是 NIC ，请使用缆线将此模块连接到数据交换机。
. 重新启动BMC、然后重新启动节点：
+
.. 在LOADER提示符处、更改为高级权限模式：`priv set advanced`
.. 重新启动BMC：`sp reboot`


. 从LOADER提示符处、重新启动节点：`bye`
+

NOTE: 此操作将重新初始化PCIe卡和其他组件、并重新启动节点。

. 从配对节点交还节点。`storage failover giveback -ofnode target_node_name`
. 如果已禁用，请启用自动交还： `storage failover modify -node local -auto-giveback true`
. 如果您添加了：
+
[cols="1,2"]
|===
| 如果 I/O 模块为 ... | 那么 ... 


 a| 
插槽 3 或 7 中的 NIC 模块，
 a| 
对每个端口使用 `storage port modify -node *_< 节点名称 >_ -port *_< 端口名称 >__ -mode network` 命令。



 a| 
存储模块
 a| 
安装SAS磁盘架并为其布线、如中所述https://docs.netapp.com/us-en/ontap-systems/sas3/install-hot-add-shelf.html["热添加SAS磁盘架"^]。

|===
. 对控制器 B 重复上述步骤

