---
permalink: fas9500/chassis_replace_move_hardware.html 
sidebar: sidebar 
keywords:  
summary: 系统中的所有其他组件必须正常运行；否则，您必须联系技术支持。 
---
= 移动并更换硬件—FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要更换机箱，您必须从旧机箱中卸下组件，然后将其安装到更换机箱中。



== 第 1 步：卸下电源

[role="lead"]
更换机箱时，要卸下电源，需要关闭电源，断开连接，然后从旧机箱中卸下电源。

. 如果您尚未接地，请正确接地。
. 关闭电源并断开电源线：
+
.. 关闭电源上的电源开关。
.. 打开电源线固定器，然后从电源拔下电源线。
.. 从电源拔下电源线。


. 按住电源手柄上的 Terra cotta 按钮，然后将电源从机箱中拉出。
+

NOTE: 卸下电源时，请始终用双手支撑其重量。

+
.动画-删除/安装PSU
video::590b3414-6ea5-42b2-b7f4-ae78004b86a4[panopto]
+
image::../media/drw_9500_remove_install_PSU_module.svg[DRW 9500remove install PSU module]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
锁定按钮

|===
. 对其余所有电源重复上述步骤。




== 第 2 步：卸下风扇

[role="lead"]
要在更换机箱时卸下风扇模块，您必须执行一系列特定的任务。

. 如果您尚未接地，请正确接地。
. 如有必要，请用两只手抓住挡板每一侧的开口，然后将其拉向您，直到挡板从机箱框架上的球形螺柱上松开，从而卸下挡板。
. 按下风扇模块上的 Terra cotta 按钮，然后将风扇模块竖直拉出机箱，确保用您的空闲手托住该模块。
+

NOTE: 风扇模块较短。请始终用您的空闲手托住风扇模块的底部，以免其突然从机箱中脱离并造成您的人身伤害。

+
.动画-拆卸/安装风扇
video::86b0ed39-1083-4b3a-9e9c-ae78004c2ffc[panopto]
+
image::../media/drw_9500_remove_install_fan.svg[DRW 9500-卸下安装风扇]

+
[cols="20%,80%"]
|===


 a| 
image:../media/legend_icon_01.svg["宽度= 20"]
 a| 
Terra cotta 释放按钮



 a| 
image:../media/legend_icon_02.svg["宽度= 20"]
 a| 
将风扇滑入 / 滑出机箱

|===
. 将风扇模块放在一旁。
. 对其余所有风扇模块重复上述步骤。




== 第 3 步：卸下控制器模块

[role="lead"]
要更换机箱，您必须从旧机箱中卸下控制器模块。

. 如果您尚未接地，请正确接地。
. 从受损控制器模块拔下缆线，并跟踪缆线的连接位置。
. 向下滑动凸轮把手上的 Terra cotta 按钮，直到其解锁为止。
+
.动画-删除控制器模块
video::5e029a19-8acc-4fa1-be5d-ae78004b365a[panopto]
+
image::../media/drw_9500_remove_PCM.svg[DRW 9500-删除PCM]

+
[cols="20%,80%"]
|===


 a| 
image:../media/legend_icon_01.svg["宽度= 20"]
 a| 
凸轮把手释放按钮



 a| 
image:../media/legend_icon_02.svg["宽度= 20"]
 a| 
凸轮把手

|===
. 旋转凸轮把手，使其完全脱离机箱，然后将控制器模块滑出机箱。
+
将控制器模块滑出机箱时，请确保您支持控制器模块的底部。

. 将控制器模块放在安全的位置，如果机箱中有其他控制器模块，请重复上述步骤。




== 第 4 步：卸下 I/O 模块

[role="lead"]
To remove I/O modules from the old chassis, including the NVRAM modules, follow the specific sequence of steps.将 FlashCache 模块移至新机箱时，无需从 NVRAM 模块中卸下该模块（如果存在）。

. 如果您尚未接地，请正确接地。
. 拔下与目标 I/O 模块关联的所有布线。
+
请确保为这些缆线贴上标签，以便您知道这些缆线来自何处。

. 从机箱中卸下目标 I/O 模块：
+
.. 按下带字母和编号的凸轮按钮。
+
凸轮按钮离开机箱。

.. 向下旋转凸轮闩锁，直到其处于水平位置。
+
I/O 模块从机箱中分离，并从 I/O 插槽中移出大约 1/2 英寸。

.. 拉动 I/O 模块侧面的拉片，将 I/O 模块从机箱中卸下。
+
确保跟踪 I/O 模块所在的插槽。

+
.动画-删除/安装I/O模块
video::0903b1f9-187b-4bb8-9548-ae9b0012bb21[panopto]
+
image::../media/drw_9500_remove_PCIe_module.svg[DRW 9500-卸下PCIe模块]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
I/O 凸轮闩锁有字母和编号



 a| 
image::../media/legend_icon_02.svg[图例图标 02]
 a| 
I/O 凸轮闩锁完全解锁

|===


. 将 I/O 模块放在一旁。
. 对旧机箱中的其余 I/O 模块重复上述步骤。




== 第 5 步：卸下降级控制器电源模块

[role="lead"]
您必须从旧机箱中卸下降级控制器电源模块，以便为安装更换机箱做好准备。

. 如果您尚未接地，请正确接地。
. 按下模块把手上的 Terra cotta 锁定按钮，然后将 DCPM 模块滑出机箱。
+
.动画-删除/安装DCPM
video::c067cf9d-35b8-4fbe-9573-ae78004c2328[panopto]
+
image::../media/drw_9500_remove_NV_battery.svg[DRW 9500-取出NV电池]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
DCPM 模块的 Terra cotta 锁定按钮

|===
. 将 DCPM 模块放在安全位置，然后对其余 DCPM 模块重复此步骤。




== 第 6 步：从设备机架或系统机柜中更换机箱

[role="lead"]
您必须先从设备机架或系统机柜中卸下现有机箱，然后才能安装替代机箱。

. 从机箱安装点卸下螺钉。
+

NOTE: 如果系统位于系统机柜中，则可能需要卸下后部系紧支架。

. 在两三个人的帮助下，将旧机箱滑出系统机柜中的机架导轨或设备机架中的 _L_ 支架，然后将其放在一旁。
. 如果您尚未接地，请正确接地。
. 由两到三人组成，通过将更换机箱引导至系统机柜中的机架导轨或设备机架中的 _L_ 支架，将更换机箱安装到设备机架或系统机柜中。
. 将机箱完全滑入设备机架或系统机柜中。
. 使用从旧机箱中卸下的螺钉将机箱前部固定到设备机架或系统机柜。
. 将机箱后部固定到设备机架或系统机柜。
. 如果您使用的是缆线管理支架，请将其从旧机箱中卸下，然后将其安装在更换机箱上。
. 如果尚未安装挡板，请安装挡板。




== 第 7 步：将 USB LED 模块移至新机箱

[role="lead"]
将新机箱安装到机架或机柜中后，必须将 USB LED 模块从旧机箱移至新机箱。

.动画-删除/安装USB模块
video::bc46a3e8-6541-444e-973b-ae78004bf153[panopto]
image::../media/drw_9500_remove_replace_LED_mod.svg[DRW 9500-删除更换LED模块]

[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
弹出模块。



 a| 
image:../media/legend_icon_02.svg["宽度= 20"]
 a| 
滑出机箱。

|===
. 找到旧机箱正面，电源托架正下方的 USB LED 模块。
. 按下模块右侧的黑色锁定按钮，将模块从机箱中释放，然后将其滑出旧机箱。
. 将模块边缘与更换机箱前下方的 USB LED 托架对齐，然后将模块一直轻轻推入机箱，直到其卡入到位。




== 第 8 步：在更换机箱时安装降级控制器电源模块

将替代机箱安装到机架或系统机柜中后，您必须将降级控制器电源模块重新安装到其中。

. 如果您尚未接地，请正确接地。
. 将 DCPM 模块的末端与机箱开口对齐，然后将其轻轻滑入机箱，直到其卡入到位。
+

NOTE: 模块和插槽采用键控方式。请勿强行将模块插入开口。如果模块不易插入，请重新对齐模块并将其滑入机箱。

. 对其余 DCPM 模块重复此步骤。




== 第 9 步：将风扇安装到机箱中

[role="lead"]
要在更换机箱时安装风扇模块，您必须执行一系列特定的任务。

. 如果您尚未接地，请正确接地。
. 将替代风扇模块的边缘与机箱中的开口对齐，然后将其滑入机箱，直至其卡入到位。
+
将风扇模块成功插入机箱后，琥珀色警示 LED 会闪烁四次。

. 对其余风扇模块重复上述步骤。
. 将挡板与球形螺柱对齐，然后将挡板轻轻推入球形螺柱上。




== 第 10 步：安装 I/O 模块

[role="lead"]
要安装 I/O 模块，包括旧机箱中的 NVRAM/FlashCache 模块，请按照特定步骤顺序进行操作。

您必须安装机箱，以便将 I/O 模块安装到新机箱中的相应插槽中。

. 如果您尚未接地，请正确接地。
. 将更换机箱安装到机架或机柜中后，通过将 I/O 模块轻轻滑入插槽，将 I/O 模块安装到更换机箱中相应的插槽中，直到带字母和编号的 I/O 凸轮闩锁开始啮合为止。 然后，将 I/O 凸轮闩锁完全向上推，以将模块锁定到位。
. 根据需要重新对 I/O 模块进行布线。
. 对其余已预留的 I/O 模块重复上述步骤。
+

NOTE: 如果旧机箱具有空白 I/O 面板，请此时将其移至更换机箱。





== 第 11 步：安装电源

[role="lead"]
在更换机箱时安装电源涉及到将电源安装到更换机箱以及连接到电源。

. 如果您尚未接地，请正确接地。
. 用双手支撑电源边缘并将其与系统机箱中的开口对齐，然后将电源轻轻推入机箱，直到其锁定到位。
+
电源具有键控功能，只能单向安装。

+

IMPORTANT: 将电源滑入系统时，请勿用力过大。您可能会损坏连接器。

. 重新连接电源线，并使用电源线锁定机制将其固定到电源。
+

IMPORTANT: 仅将电源线连接到电源。此时请勿将电源线连接到电源。

. 对其余所有电源重复上述步骤。




== 第 12 步：安装控制器

[role="lead"]
将控制器模块和任何其他组件安装到新机箱中后，将其启动到可以运行互连诊断测试的状态。

. 如果您尚未接地，请正确接地。
. 将控制器模块的末端与机箱中的开口对齐，然后将控制器模块轻轻推入系统的一半。
+

NOTE: 请勿将控制器模块完全插入机箱中，除非系统指示您这样做。

. 将控制台重新连接到控制器模块，然后重新连接管理端口。
. 将电源连接到不同的电源，然后打开电源。
. 在凸轮把手处于打开位置的情况下，将控制器模块滑入机箱并用力推入控制器模块，直到它与中板相距并完全就位，然后合上凸轮把手，直到它卡入到锁定位置。
+

IMPORTANT: 将控制器模块滑入机箱时，请勿用力过大，否则可能会损坏连接器。

+
控制器模块一旦完全固定在机箱中，就会开始启动。

. 重复上述步骤，将第二个控制器安装到新机箱中。
. 将每个节点启动至维护模式：
+
.. 在每个节点开始启动时，如果您看到 Press Ctrl-C for Boot Menu 消息，请按 `Ctrl-C` 以中断启动过程。
+

NOTE: 如果您未看到此提示，并且控制器模块启动到 ONTAP ，请输入 `halt` ，然后在 LOADER 提示符处输入 `boot_ontap` ，并在出现提示时按 `Ctrl-C` ，然后重复此步骤。

.. 从启动菜单中，选择维护模式选项。



