---
permalink: fas9500/install_detailed_guide.html 
sidebar: sidebar 
keywords: FAS9500 
summary: 此提供了有关安装典型 NetApp 系统的详细分步说明。 
---
= 详细步骤—FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本文详细介绍了安装典型 NetApp 系统的分步说明。如果您需要更详细的安装说明，请使用本文。



== 第 1 步：准备安装

要安装系统，您需要在 NetApp 支持站点上创建帐户，注册系统并获取许可证密钥。此外，您还需要为系统清点适当数量和类型的缆线，并收集特定的网络信息。

您需要有权访问 https://hwu.netapp.com["NetApp Hardware Universe"^] 有关站点要求以及已配置系统上的追加信息的信息。

.您需要的内容
您可能还希望有权访问 http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["《 ONTAP 9 发行说明》"^] 有关此系统的详细信息，请参见您的 ONTAP 版本。

您需要在站点上提供以下内容：

* 存储系统的机架空间
* 2 号十字螺丝刀
* 使用其他网络缆线通过 Web 浏览器将系统连接到网络交换机和笔记本电脑或控制台


.步骤
. 打开所有框内容的包装。
. 记录控制器的系统序列号。
+
image::../media/drw_ssn_label.svg[显示编号位置的系统序列号示例]

. 清点并记下收到的缆线数量和类型。
+
下表列出了您可能收到的电缆类型。如果您收到的电缆未在表中列出，请参见 Hardware Universe 以找到该电缆并确定其用途。

+
https://hwu.netapp.com["NetApp Hardware Universe"^]

+
[cols="1,2,1,2"]
|===
| 缆线类型 ... | 部件号和长度 | 连接器类型 | 针对 ... 


 a| 
25 GbE 数据缆线
 a| 
X66240A-05 （ 112-00639 ）， 0.5 米

X66240A-2 （ 112-00598 ）， 2 米

X66240A-5 （ 112-00600 ）， 5 米
 a| 
image::../media/oie_cable_sfp_gbe_copper.svg[OIE 使用缆线连接 SFP GbE 铜缆]
 a| 
网络缆线



 a| 
32 Gb FC （ SFP+ 操作）
 a| 
X66250-2 （ 112-00342 ）， 2 米

X66250-5 （ 112-00344 ）， 5 米

X66250-15 （ 112-00346 ）， 15 米
 a| 
image::../media/oie_cable_sfp_gbe_copper.svg[OIE 使用缆线连接 SFP GbE 铜缆]
 a| 
FC 光纤网络缆线



 a| 
40 GbE 网络缆线
 a| 
X66100-1 （ 112-00542 ）， 1 米

X66100-3 （ 112-00543 ）， 3 米

X66100-5 （ 112-00544 ）， 5 米
 a| 
image::../media/oie_cable100_gbe_qsfp28.svg[OIE cable100 GbE QSFP28]
 a| 
以太网数据，集群网络



 a| 
100 GbE 缆线
 a| 
X6621B-1 （ 112-00573 ）， 1 米

X6621B-2 （ 112-00574 ）， 2 米

X6621B-5 （ 112-00576 ）， 5 米
 a| 
image::../media/oie_cable100_gbe_qsfp28.svg[OIE cable100 GbE QSFP28]
 a| 
网络，

以太网数据，

集群网络



 a| 
光缆
 a| 
X66031A （ 112-00436A ）， 1 米

X66032A （ 112-00437 ）， 2 米

X66033A （ 112-00438 ）， 3 米
 a| 
image::../media/oie_cable_fiber_lc_connector.svg[OIE 缆线光纤 LC 连接器]
 a| 
FC 光纤网络



 a| 
6 类， RJ-45 （取决于订单）
 a| 
部件号 X6585-R6 （ 112-00291 ）， 3 米

X6562-R6 （ 112-00196 ）， 5 米
 a| 
image::../media/oie_cable_rj45.svg[OIE 缆线 RJ45]
 a| 
管理网络和以太网数据



 a| 
存储
 a| 
X66031A （ 112-00436A ）， 1 米

X66032A （ 112-00437 ）， 2 米

X66033A （ 112-00438 ）， 3 米
 a| 
image::../media/oie_cable_mini_sas_hd_to_mini_sas_hd.svg[OIE使用缆线将迷你SAS HD连接到迷你SAS HD]
 a| 
存储



 a| 
微型 USB 控制台缆线
 a| 
不适用
 a| 
image::../media/oie_cable_micro_usb.svg[OIE缆线微型USB]
 a| 
在非 Windows 或 Mac 笔记本电脑 / 控制台上设置软件期间连接控制台



 a| 
电源线
 a| 
不适用
 a| 
image::../media/oie_cable_power.svg[OIE缆线电源]
 a| 
启动系统

|===
. 查看 https://library.netapp.com/ecm/ecm_download_file/ECMLP2862613["《 ONTAP 配置指南》"^] 并收集该指南中列出的所需信息。




== 第 2 步：安装硬件

您需要根据需要将系统安装在四柱机架或 NetApp 系统机柜中。

. 根据需要安装导轨套件。
. 按照导轨套件附带的说明安装并固定系统。
+

NOTE: 您需要了解与系统重量相关的安全问题。

+
左侧的标签表示空机箱，右侧的标签表示系统已完全填充。

+
image::../media/drw_9500_lifting_icon.svg[举重注意标签]

. 连接缆线管理设备（如图所示）。
+
image::../media/drw_9500_cable_management_arms.svg[提升手柄和缆线管理设备]

. 将挡板放在系统正面。




== 第 3 步：使用缆线将控制器连接到网络

您可以使用双节点无交换机集群方法或集群互连网络将控制器连接到网络。

[role="tabbed-block"]
====
.选项 1 ：双节点无交换机集群
--
控制器上的管理网络，数据网络和管理端口连接到交换机。两个控制器上的集群互连端口均已通过缆线连接。

.开始之前
您必须已联系网络管理员，了解有关将系统连接到交换机的信息。

在端口中插入缆线时，请务必检查缆线拉片的方向。所有网络模块端口的缆线拉片均已启动。

image::../media/oie_cable_pull_tab_up.svg[电缆拉片方向]


NOTE: 插入连接器时、您应感觉到连接器卡入到位；如果您不觉得连接器卡嗒声、请将其卸下、然后将其翻转并重试。

. 使用动画或插图完成控制器与交换机之间的布线：
+
.动画—双节点无交换机集群布线
video::da08295f-ba8c-4de7-88c3-ae7c0170408d[panopto]
+
image::../media/drw_9500_tnsc_network_cabling.svg[DRW 9500tnsc网络布线]

+
|===
| 步骤 | 在每个控制器上执行 


 a| 
image::../media/oie_legend_icon_1_lg.svg[OIE图例图标1长]
 a| 
使用缆线连接集群互连端口：

** 插槽 A4 和 B4 （ E4A ）
** 插槽 -A8 和 B8 （ E8a ）


image::../media/oie_cable100_gbe_qsfp28.svg[OIE cable100 GbE QSFP28]



 a| 
image::../media/oie_legend_icon_2_lp.svg[OIE 图例图标 2 LP]
 a| 
使用缆线连接控制器管理（扳手）端口。

image::../media/oie_cable_rj45.svg[OIE 缆线 RJ45]



 a| 
image::../media/oie_legend_icon_3_o.svg[OIE 图例图标 3 o]
 a| 
使用缆线连接32 Gb FC网络交换机：

插槽A3和B3 (E3A和E3C)以及插槽A9和B9 (e9a和e9c)中的端口连接到32 Gb FC网络交换机。

image::../media/oie_cable_sfp_gbe_copper.svg[OIE 使用缆线连接 SFP GbE 铜缆]

40GbE 主机网络交换机：

使用缆线将插槽 A4 和 B4 （ e4b ）以及插槽 A4 和 B8 （ e8b ）中的主机‐端 b 端口连接到主机交换机。

image::../media/oie_cable100_gbe_qsfp28.svg[OIE cable100 GbE QSFP28]



 a| 
image::../media/oie_legend_icon_4_dr.svg[OIE 图例图标 4 驱动器]
 a| 
使用缆线连接25 GbE连接：

使用缆线将插槽5和B5 (5a、5b、5c和5d)以及插槽A7和B7 (7a、7b、7c和7d)中的端口连接到25 GbE网络交换机。

image::../media/oie_cable_sfp_gbe_copper.svg[OIE 使用缆线连接 SFP GbE 铜缆]



 a| 
** 将缆线固定到缆线管理臂上(未显示)。
** 将电源线连接到PSU并将其连接到不同的电源(未显示)。PSU 1和3为所有A侧组件供电、而PSU2和PSU4则为所有B侧组件供电。

 a| 
image::../media/oie_cable_power.svg[OIE缆线电源]

image::../media/drw_a900fas9500_power_source_icon_IEOPS-1142.svg[DRW a900FAS9500电源图标IEOPS 1142.]

|===


--
.选项 2 ：交换集群
--
控制器上的管理网络，数据网络和管理端口连接到交换机。集群互连和 HA 端口通过缆线连接到集群 /HA 交换机。

.开始之前
您必须已联系网络管理员，了解有关将系统连接到交换机的信息。

在端口中插入缆线时，请务必检查缆线拉片的方向。所有网络模块端口的缆线拉片均已启动。

image::../media/oie_cable_pull_tab_up.svg[电缆拉片方向]


NOTE: 插入连接器时、您应感觉到连接器卡入到位；如果您不觉得连接器卡嗒声、请将其卸下、然后将其翻转并重试。

. 使用动画或插图完成控制器与交换机之间的布线：
+
.动画—切换集群布线
video::3ad3f118-8339-4683-865f-ae7c0170400c[panopto]
+
image::../media/drw_9500_switched_network_cabling.svg[DRW 9500"交换网络布线"]

+
|===
| 步骤 | 在每个控制器上执行 


 a| 
image::../media/oie_legend_icon_1_lg.svg[OIE图例图标1长]
 a| 
使用缆线连接集群互连 A 端口：

** 插槽 A4 和 B4 （ E4A ）连接到集群网络交换机。
** 插槽 "A8 和 B8 （ E8a ）连接到集群网络交换机。


image::../media/oie_cable100_gbe_qsfp28.svg[OIE cable100 GbE QSFP28]



 a| 
image::../media/oie_legend_icon_2_lp.svg[OIE 图例图标 2 LP]
 a| 
使用缆线连接控制器管理（扳手）端口。

image::../media/oie_cable_rj45.svg[OIE 缆线 RJ45]



 a| 
image::../media/oie_legend_icon_3_o.svg[OIE 图例图标 3 o]
 a| 
使用缆线连接32 Gb FC网络交换机：

插槽A3和B3 (E3A和E3C)以及插槽A9和B9 (e9a和e9c)中的端口连接到32 Gb FC网络交换机。

image::../media/oie_cable_sfp_gbe_copper.svg[OIE 使用缆线连接 SFP GbE 铜缆]

40GbE 主机网络交换机：

使用缆线将插槽 A4 和 B4 （ e4b ）以及插槽 A4 和 B8 （ e8b ）中的主机‐端 b 端口连接到主机交换机。

image::../media/oie_cable100_gbe_qsfp28.svg[OIE cable100 GbE QSFP28]



 a| 
image::../media/oie_legend_icon_4_dr.svg[OIE 图例图标 4 驱动器]
 a| 
使用缆线连接25 GbE连接：

使用缆线将插槽5和B5 (5a、5b、5c和5d)以及插槽A7和B7 (7a、7b、7c和7d)中的端口连接到25 GbE网络交换机。

image::../media/oie_cable_sfp_gbe_copper.svg[OIE 使用缆线连接 SFP GbE 铜缆]



 a| 
** 将缆线固定到缆线管理臂上(未显示)。
** 将电源线连接到PSU并将其连接到不同的电源(未显示)。PSU 1和3为所有A侧组件供电、而PSU2和PSU4则为所有B侧组件供电。

 a| 
image::../media/oie_cable_power.svg[OIE缆线电源]

image::../media/drw_a900fas9500_power_source_icon_IEOPS-1142.svg[DRW a900FAS9500电源图标IEOPS 1142.]

|===


--
====


== 第 4 步：使用缆线将控制器连接到驱动器架

使用缆线将DS212C或DS224C驱动器架连接到控制器。


NOTE: 有关更多SAS布线信息和工作表、请参见link:../sas3/overview-cabling-rules-examples.html["SAS 布线规则，工作表和示例概述—带有 IOM12 模块的磁盘架"]

.开始之前
* 填写适用于您系统的SAS布线工作表。请参阅。 link:../sas3/overview-cabling-rules-examples.html["SAS 布线规则，工作表和示例概述—带有 IOM12 模块的磁盘架"]
* 请务必检查插图箭头以确定正确的缆线连接器拉片方向。存储模块的缆线拉片已启动，而磁盘架上的拉片已关闭。


image::../media/oie_cable_pull_tab_up.svg[电缆拉片方向]

image::../media/oie_cable_pull_tab_down.svg[OIE 缆线下拉卡舌]


NOTE: 插入连接器时、您应感觉到连接器卡入到位；如果您不觉得连接器卡嗒声、请将其卸下、然后将其翻转并重试。

. 使用以下动画或图将控制器连接到三个(一个驱动器架的一个堆栈和两个驱动器架的一个堆栈) DS224C驱动器架。
+
.动画—为驱动器架布线
video::c958aae6-9d08-4d3d-a213-ae7c017040cd[panopto]
+
image::../media/drw_9500_sas_shelf_cabling.svg[DRW 9500SAS磁盘架布线]

+
[cols="20%,80%"]
|===
| 步骤 | 在每个控制器上执行 


 a| 
image::../media/oie_legend_icon_1_mb.svg[OIE图例图标1 MB]
 a| 
使用图作为参考、将驱动器架堆栈1连接到控制器。

image::../media/oie_cable_mini_sas_hd_to_mini_sas_hd.svg[OIE使用缆线将迷你SAS HD连接到迷你SAS HD]

迷你SAS缆线



 a| 
image::../media/oie_legend_icon_2_t.svg[OIE图例图标2 t]
 a| 
使用图作为参考、将驱动器架堆栈2连接到控制器。

image::../media/oie_cable_mini_sas_hd_to_mini_sas_hd.svg[OIE使用缆线将迷你SAS HD连接到迷你SAS HD]

迷你SAS缆线

|===




== 第 5 步：完成系统设置和配置

您可以使用仅连接到交换机和笔记本电脑的集群发现完成系统设置和配置，也可以直接连接到系统中的控制器，然后连接到管理交换机。

[role="tabbed-block"]
====
.选项 1 ：如果启用了网络发现
--
如果您在笔记本电脑上启用了网络发现，则可以使用自动集群发现完成系统设置和配置。

. 使用以下动画或图形设置一个或多个驱动器架 ID ：
+
.动画—设置磁盘架ID和#8217
video::95a29da1-faa3-4ceb-8a0b-ac7600675aa6[panopto]
+
image::../media/drw_power-on_set_shelf_ID_set.svg[已设置 DRW 电源打开设置磁盘架 ID]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
拆下端盖。



 a| 
image::../media/legend_icon_02.svg[图例图标 02]
 a| 
按住磁盘架 ID 按钮，直到第一位数字闪烁，然后按进入 0-9 。


NOTE: 第一个数字将继续闪烁



 a| 
image::../media/legend_icon_03.svg[图例图标 03]
 a| 
按住磁盘架 ID 按钮，直到第二位数字闪烁，然后按进入 0-9 。


NOTE: 第一个数字停止闪烁、第二个数字继续闪烁。



 a| 
image::../media/legend_icon_04.svg[图例图标04]
 a| 
更换端盖。



 a| 
image::../media/legend_icon_05.svg[图例图标05]
 a| 
等待 10 秒，以显示琥珀色 LED （！） 显示，然后重新启动驱动器架以设置磁盘架 ID 。

|===
. 打开两个节点电源上的电源开关。
+
.动画—打开控制器的电源
video::a905e56e-c995-4704-9673-adfa0005a891[panopto]
+
image::../media/drw_9500_power-on.svg[打开DRW 9500"电源]

+

NOTE: 初始启动可能需要长达八分钟的时间。

. 确保您的笔记本电脑已启用网络发现。
+
有关详细信息，请参见笔记本电脑的联机帮助。

. 使用以下动画将您的笔记本电脑连接到管理交换机。
+
.动画—将笔记本电脑连接到管理交换机
video::d61f983e-f911-4b76-8b3a-ab1b0066909b[panopto]
+
image::../media/dwr_laptop_to_switch_only.svg[DWR 笔记本电脑仅连接到交换机]

. 选择列出的 ONTAP 图标以发现：
+
image::../media/drw_autodiscovery_controler_select.svg[DRW 自动发现控制器选择]

+
.. 打开文件资源管理器。
.. 单击左窗格中的 network 。
.. 右键单击并选择刷新。
.. 双击 ONTAP 图标并接受屏幕上显示的任何证书。
+

NOTE: XXXXX 是目标节点的系统序列号。

+
此时将打开 System Manager 。



. 使用 System Manager 引导式设置使用中收集的数据配置系统 https://library.netapp.com/ecm/ecm_download_file/ECMLP2862613["《 ONTAP 配置指南》"^]。
. 设置您的帐户并下载 Active IQ Config Advisor ：
+
.. 登录到现有帐户或创建帐户。
+
https://mysupport.netapp.com/eservice/public/now.do["NetApp 支持注册"^]

.. 注册您的系统。
+
https://mysupport.netapp.com/eservice/registerSNoAction.do?moduleName=RegisterMyProduct["NetApp 产品注册"^]

.. 下载 Active IQ Config Advisor 。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]



. 运行 Config Advisor 以验证系统的运行状况。
. After you have completed the initial configuration, go to the https://www.netapp.com/data-management/oncommand-system-documentation/["ONTAP 和 AMP ； ONTAP System Manager 文档资源"^] page for information about configuring additional features in ONTAP.


--
.选项 2 ：如果未启用网络发现
--
如果您使用的不是基于 Windows 或 Mac 的笔记本电脑或控制台，或者未启用自动发现，则必须使用此任务完成配置和设置。

. 为笔记本电脑或控制台布线并进行配置：
+
.. 使用 N-8-1 将笔记本电脑或控制台上的控制台端口设置为 115200 波特。
+

NOTE: 有关如何配置控制台端口的信息，请参见笔记本电脑或控制台的联机帮助。

.. 使用系统随附的控制台缆线将控制台缆线连接到笔记本电脑或控制台、然后将笔记本电脑连接到管理子网上的交换机。
+
image::../media/drw_9500_cable_console_switch_controller.svg[DRW 9500缆线 控制台交换机控制器]

.. 使用管理子网上的一个 TCP/IP 地址为笔记本电脑或控制台分配 TCP/IP 地址。


. 使用以下动画设置一个或多个驱动器架 ID ：
+
.动画—设置磁盘架ID和#8217
video::95a29da1-faa3-4ceb-8a0b-ac7600675aa6[panopto]
+
image::../media/drw_power-on_set_shelf_ID_set.svg[已设置 DRW 电源打开设置磁盘架 ID]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
拆下端盖。



 a| 
image::../media/legend_icon_02.svg[图例图标 02]
 a| 
按住磁盘架 ID 按钮，直到第一位数字闪烁，然后按进入 0-9 。


NOTE: 第一个数字将继续闪烁



 a| 
image::../media/legend_icon_03.svg[图例图标 03]
 a| 
按住磁盘架 ID 按钮，直到第二位数字闪烁，然后按进入 0-9 。


NOTE: 第一个数字停止闪烁、第二个数字继续闪烁。



 a| 
image::../media/legend_icon_04.svg[图例图标04]
 a| 
更换端盖。



 a| 
image::../media/legend_icon_05.svg[图例图标05]
 a| 
等待 10 秒，以显示琥珀色 LED （！） 显示，然后重新启动驱动器架以设置磁盘架 ID 。

|===
. 打开两个节点电源上的电源开关。
+
.动画—打开控制器的电源
video::a905e56e-c995-4704-9673-adfa0005a891[panopto]
+
image::../media/drw_9500_power-on.svg[打开DRW 9500"电源]




NOTE: 初始启动可能需要长达八分钟的时间。

. 将初始节点管理 IP 地址分配给其中一个节点。
+
[cols="1,2"]
|===
| 如果管理网络具有 DHCP... | 那么 ... 


 a| 
已配置
 a| 
记录分配给新控制器的 IP 地址。



 a| 
未配置
 a| 
.. 使用 PuTTY ，终端服务器或环境中的等效项打开控制台会话。
+

NOTE: 如果您不知道如何配置 PuTTY ，请查看笔记本电脑或控制台的联机帮助。

.. 在脚本提示时输入管理 IP 地址。


|===
. 使用笔记本电脑或控制台上的 System Manager 配置集群：
+
.. 将浏览器指向节点管理 IP 地址。
+

NOTE: The format for the address is +https://x.x.x.x+.

.. Configure the system using the data you collected in the https://library.netapp.com/ecm/ecm_download_file/ECMLP2862613["《 ONTAP 配置指南》"^] 。


. 设置您的帐户并下载 Active IQ Config Advisor ：
+
.. 登录到现有帐户或创建帐户。
+
https://mysupport.netapp.com/eservice/public/now.do["NetApp 支持注册"^]

.. 注册您的系统。
+
https://mysupport.netapp.com/eservice/registerSNoAction.do?moduleName=RegisterMyProduct["NetApp 产品注册"^]

.. 下载 Active IQ Config Advisor 。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]



. 运行 Config Advisor 以验证系统的运行状况。
. After you have completed the initial configuration, go to the https://www.netapp.com/data-management/oncommand-system-documentation/["ONTAP 和 AMP ； ONTAP System Manager 文档资源"^] page for information about configuring additional features in ONTAP.


--
====