---
permalink: fas9500/maintain-overview.html 
sidebar: sidebar 
keywords: FAS9500 maintenance, maintenance, repairing FAS9500, repairing aff FAS9500, replace FAS9500 components, replace FAS9500 components 
summary: 维护FAS9500硬件 
---
= 维护FAS9500硬件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
维护 FAS9500 存储系统的硬件，以确保长期可靠性和最佳性能。定期执行维护任务（例如更换故障组件），有助于防止停机和数据丢失。

维护过程假定 FAS9500 存储系统已部署为ONTAP环境中的存储节点。



== 系统组件

对于FAS9500存储系统、您可以对以下组件执行维护过程。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["启动媒体 - 自动恢复"]
 a| 
启动介质存储存储系统用于启动的一组主要ONTAP映像文件。在自动恢复期间，系统从合作伙伴节点检索启动映像，并自动运行相应的启动菜单选项以在替换启动介质上安装该映像。自动启动介质恢复过程仅在ONTAP 9.17.1 及更高版本中受支持。如果您的存储系统运行的是早期版本的ONTAP，请使用link:bootmedia-replace-workflow.html["手动启动恢复程序"] 。



 a| 
link:bootmedia-replace-workflow.html["启动媒体 - 手动恢复"]
 a| 
启动介质存储存储系统用于启动的一组主要ONTAP映像文件。在手动恢复期间，您从 USB 驱动器启动存储系统并手动恢复文件系统映像和配置。如果您的存储系统运行的是ONTAP 9.17.1 及更高版本，请使用link:bootmedia-replace-workflow-bmr.html["自动启动恢复程序"]。



 a| 
link:caching_module_hot_swap.html["缓存模块"]
 a| 
如果系统注册了一条AutoSupport (ASUP)消息、指出控制器的缓存模块已脱机、则必须更换该模块。



 a| 
link:chassis_replace_overview.html["机箱"]
 a| 
机箱是托管所有控制器组件(例如控制器/CPU单元、电源和I/O)的物理机箱



 a| 
link:controller_replace_overview.html["控制器"]
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实现ONTAP功能。



 a| 
link:dimm_replace.html["DIMM"]
 a| 
如果存在内存不匹配或 DIMM 发生故障，则必须更换 DIMM （双列直插式内存模块）。



 a| 
link:dcpm-nvram11-battery-replace.html["DCPM"]
 a| 
DCPM (目标控制器电源模块)包含NVRAM11电池。



 a| 
link:fan_swap_out.html["风扇"]
 a| 
风扇用于冷却控制器。



 a| 
link:pci_cards_and_risers_replace.html["I/O 模块"]
 a| 
I/O模块(输入/输出模块)是一个硬件组件、充当控制器与需要与控制器交换数据的各种设备或系统之间的媒介。



 a| 
link:led_module_replace.html["LED USB"]
 a| 
LED USB 模块可连接到控制台端口和系统状态。



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
NVRAM模块（非易失性随机存取存储器）允许控制器在电源循环或系统重启后保留数据，而NVRAM DIMM 则维护NVRAM设置。



 a| 
link:power_supply_swap_out.html["电源"]
 a| 
电源设备在控制器中提供冗余电源。



 a| 
link:rtc_battery_replace.html["实时时钟电池"]
 a| 
实时时钟电池可在断电时保留系统日期和时间信息。

|===