---
permalink: fas9500/pci_cards_and_risers_replace.html 
sidebar: sidebar 
keywords:  
summary: 要更换 I/O 模块，您必须执行一系列特定的任务。 
---
= 更换I/O模块—FAS9500
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要更换 I/O 模块，您必须执行一系列特定的任务。

* 您可以将此操作步骤与系统支持的所有 ONTAP 版本结合使用。
* 系统中的所有其他组件必须正常运行；否则，您必须联系技术支持。




== 第 1 步：关闭受损节点

要关闭受损控制器，您必须确定控制器的状态，并在必要时接管控制器，以便运行正常的控制器继续从受损控制器存储提供数据。

If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示 false ，则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/index.html["CLI 管理概述"^]。

.步骤
. 如果启用了 AutoSupport ，则通过调用 AutoSupport 消息禁止自动创建案例： `ssystem node AutoSupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
以下 AutoSupport 消息禁止自动创建案例两小时： `cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
`正在等待交还 ...`
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
从运行正常的控制器接管或暂停受损的控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===




== 第 2 步：更换 I/O 模块

要更换 I/O 模块，请在机箱中找到该模块，然后按照特定步骤顺序进行操作。

. 如果您尚未接地，请正确接地。
. 拔下与目标 I/O 模块关联的所有布线。
+
请确保为这些缆线贴上标签，以便您知道这些缆线来自何处。

. 从机箱中卸下目标 I/O 模块：
+
.. 按下带字母和编号的凸轮按钮。
+
凸轮按钮离开机箱。

.. 向下旋转凸轮闩锁，直到其处于水平位置。
+
I/O 模块从机箱中分离，并从 I/O 插槽中移出大约 1/2 英寸。

.. 拉动 I/O 模块侧面的拉片，将 I/O 模块从机箱中卸下。
+
确保跟踪 I/O 模块所在的插槽。

+





endif::[]
