---
permalink: fas2800/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: fas 2800, post, boot, media, okm, nse, nve, onboard key manager, netapp storage encryption, netapp volume encryption 
summary: 检查环境变量后，您必须完成特定于已启用板载密钥管理器（ OKM\ ）， NetApp 存储加密 \ （ NSE\ ）或 NetApp 卷加密 \ （ NVE\ ）的系统的步骤。 
---
= 根据需要还原OKM、NSE和NVE—FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
选中环境变量后、您必须使用在此操作步骤开头捕获的设置完成特定于启用了板载密钥管理器(OKM)、NetApp存储加密(NSE)或NetApp卷加密(NVE)的系统的步骤。


NOTE: 如果随板载密钥管理器一起启用了 NSE 或 NVE ，则必须还原在此操作步骤开头捕获的设置。

.步骤
. 将控制台缆线连接到目标控制器。
. 在 LOADER 提示符处使用 `boot_ontap` 命令启动控制器。
. 检查控制台输出：
+
[cols="1,3"]
|===
| 如果控制台显示 ... | 那么 ... 


 a| 
登录提示符
 a| 
转至步骤 7 。



 a| 
正在等待交还
 a| 
.. 登录到配对控制器。
.. 使用 `storage failover show` 命令确认目标控制器已准备好进行交还。


|===
. 使用 `storage failover giveback -fromnode local -only-cfo-aggregates true local` 命令将控制台缆线移至配对控制器并交还目标控制器存储。
+
** 如果命令因磁盘发生故障而失败，请物理断开故障磁盘，但将磁盘保留在插槽中，直到收到更换磁盘为止。
** 如果命令因 CIFS 会话打开而失败，请与客户联系，了解如何关闭 CIFS 会话。
+

NOTE: 终止 CIFS 可能会导致数据发生原因丢失。

** 如果命令因配对节点 " 未就绪 " 而失败，请等待 5 分钟，使 NVMEM 同步。
** 如果命令因 NDMP ， SnapMirror 或 SnapVault 进程而失败，请禁用此进程。有关详细信息，请参见相应的文档中心。


. 请等待 3 分钟，然后使用 `storage failover show` 命令检查故障转移状态。
. 在 clustershell 提示符处，输入 `net int show -is-home false` 命令以列出不在其主控制器和端口上的逻辑接口。
+
如果任何接口列为 `false`，使用将这些接口还原回其主端口 `net int revert -vserver Cluster -lif _nodename_` 命令：

. 将控制台缆线移至目标控制器，然后运行 `version -v` 命令以检查 ONTAP 版本。
. 使用 `storage failover modify -node local -auto-giveback true` 命令禁用自动交还后，可将其还原。
. 在 clustershell 提示符处使用 `storage encryption disk show` 查看输出。
. 使用 `security key-manager key query` 命令显示存储在密钥管理服务器上的身份验证密钥的密钥 ID 。
+
** 如果 `restored` column = `yes/true` ，则表示您已完成更换过程，并可继续完成更换过程。
** 如果 `Key Manager type` = `external` and the `restored` column = anything other than `yes/true` ，请使用 `security key-manager external restore` 命令还原身份验证密钥的密钥 ID 。
+

NOTE: 如果命令失败，请联系客户支持。

** 如果 `密钥管理器类型` = `板载` 和 `还原` 列 = 除 `yes/true` 以外的任何其他内容，请使用 `security key-manager on板 载同步` 命令重新同步密钥管理器类型。
+
使用 security key-manager key query 验证所有身份验证密钥的 `restored` column = `yes/true` 。



. 将控制台缆线连接到配对控制器。
. 使用 `storage failover giveback -fromnode local` 命令交还控制器。
. 使用 `storage failover modify -node local -auto-giveback true` 命令禁用自动交还后，可将其还原。
. 如果启用了AutoSupport、则使用还原/取消禁止自动创建案例 `system node autosupport invoke -node * -type all -message MAINT=END`

