---
permalink: fas2800/bootmedia-replace.html 
sidebar: sidebar 
keywords: fas2800, replace, boot, media, controller, module, fru map 
summary: 您必须在控制器中找到启动介质并按照说明进行更换。 
---
= 更换启动介质- FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


要更换启动介质，您必须卸下受损的控制器模块，安装替代启动介质并将启动映像传输到 USB 闪存驱动器。



== 第 1 步：卸下控制器模块

[role="lead"]
要访问控制器内部的组件，您必须先从系统中卸下控制器模块，然后再卸下控制器模块上的盖板。

. 如果您尚未接地，请正确接地。
. 松开将缆线绑在缆线管理设备上的钩环带，然后从控制器模块上拔下系统缆线和 SFP （如果需要），并跟踪缆线的连接位置。
. 按压凸轮把手上的闩锁，直到其释放为止，完全打开凸轮把手以从中板释放控制器模块，然后用两只手将控制器模块拉出机箱。
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[DRW 285 PCM拆卸、安装IEOPS 694]

. 将控制器模块翻转，将其放在平稳的表面上。
. 按下控制器模块两侧的蓝色按钮以松开护盖、然后向上旋转护盖、使其脱离控制器模块、从而打开护盖。
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[DRW 285控制器模块盖板打开IEOPS 695]



[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
控制器模块护盖释放按钮

|===


== 第 2 步：更换启动介质

找到位于夹层卡下方的控制器模块中的启动介质、然后按照说明进行更换。

.动画-更换启动介质
video::10a29a01-a86e-451c-b05a-af4701726f57[panopto]
image:../media/drw_2850_replace_boot_media_IEOPS-696.svg["宽度=500"]

[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[图例图标 01]
 a| 
启动介质锁定卡舌

|===
.步骤
. 如果您尚未接地，请正确接地。
. 按照下图或控制器模块上的FRU示意图卸下夹层卡：
+
.. 通过将夹层卡挡板从控制器模块中直接滑出来卸下夹层卡挡板。
.. 拧松夹层卡上的翼形螺钉。
+

NOTE: 您可以用手指或螺丝刀拧松翼形螺钉。如果您用手指、则可能需要向上旋转NV电池、以便在其旁边的指旋螺钉上购买更好的手指。

.. 垂直向上提起夹层卡。


. 更换启动介质：
+
.. 按下启动介质外壳上的蓝色按钮、将启动介质从其外壳中释放出来、向上旋转启动介质、然后轻轻地将其从启动介质插槽中竖直拉出。
+

NOTE: 请勿将启动介质竖直向上扭曲或拉，因为这样可能会损坏插槽或启动介质。

.. Align the edges of the replacement boot media with the boot media socket, and then gently push it into the socket.
检查启动介质以确保其完全正确地固定在插槽中、如有必要、请取出启动介质并将其重新插入插槽。
.. 按下蓝色锁定按钮、向下旋转启动介质、然后释放锁定按钮以将启动介质锁定到位。


. 重新安装夹层卡：
+
.. 将主板上的插槽与夹层卡上的插槽对齐、然后将卡轻轻地插入插槽中。
.. 拧紧夹层卡上的三个翼形螺钉。
.. 重新安装夹层挡板。


. 重新安装控制器模块护盖并将其锁定到位。




== 第 3 步：将启动映像传输到启动介质

使用已安装系统映像的USB闪存驱动器将系统映像安装在替代启动介质上。在此操作步骤期间、您必须还原var文件系统。

.开始之前
* 您必须具有一个格式化为MBR/FAT32且容量至少为4 GB的USB闪存驱动器。
* 您必须具有网络连接。


.步骤
. 将适当的ONTAP映像版本下载到已格式化的USB闪存驱动器：
+
.. 使用 ... https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_determine_if_the_running_ONTAP_version_supports_NetApp_Volume_Encryption_(NVE)["如何确定正在运行的ONTAP版本是否支持NetApp卷加密(NVE)"^] 以确定当前是否支持卷加密。
+
*** 如果集群支持NVE、请使用NetApp卷加密下载映像。
*** 如果集群不支持NVE、请下载不带NetApp卷加密的映像。
请参见 https://kb.netapp.com/onprem/ontap/os/Which_ONTAP_image_should_I_download%3F_With_or_without_Volume_Encryption%3F["我应该下载哪个ONTAP映像？是否使用卷加密？"^] 有关详细信息：




. 解压缩下载的映像。
+

NOTE: 如果要使用 Windows 提取内容，请勿使用 WinZip 提取网络启动映像。使用其他提取工具，例如 7-Zip 或 WinRAR 。

+
解压缩的服务映像文件中有两个文件夹：

+
** `启动`
** `EFI`
+
... 将 `EFI` 文件夹复制到 USB 闪存驱动器上的顶部目录。
+
USB 闪存驱动器应具有 EFI 文件夹，并且与受损控制器运行的服务映像（ BIOS ）版本相同。

... 从笔记本电脑中取出 USB 闪存驱动器。




. 安装控制器模块：
+
.. 将控制器模块的末端与机箱中的开口对齐，然后将控制器模块轻轻推入系统的一半。
.. 重新对控制器模块进行配置。
+
重新布线时，如果已卸下介质转换器（ SFP ），请务必重新安装它们。



. 将 USB 闪存驱动器插入控制器模块上的 USB 插槽。
+
确保将 USB 闪存驱动器安装在标有 USB 设备的插槽中，而不是 USB 控制台端口中。

. 将控制器模块完全推入系统中，确保凸轮把手离开 USB 闪存驱动器，用力推动凸轮把手以完成控制器模块的就位，将凸轮把手推至关闭位置，然后拧紧翼形螺钉。
+
控制器一旦完全安装到机箱中，就会开始启动。

. 按 Ctrl-C 中断启动过程，并在加载程序提示符处停止。如果看到正在启动自动启动，请按 Ctrl-C 中止 ...
+
如果未显示此消息，请按 Ctrl-C ，选择选项以启动到维护模式，然后暂停控制器以启动到加载程序。

. 对于机箱中有一个控制器的系统，重新连接电源并打开电源。
+
系统开始启动并停留在 LOADER 提示符处。

. 在 LOADER 提示符处设置网络连接类型：
+
** 如果要配置 DHCP ： `ifconfig e0a -auto`
+

NOTE: 您配置的目标端口是在通过网络连接还原 var 文件系统期间，用于与运行正常的控制器中受损的控制器进行通信的目标端口。You can also use the e0M port in this command.

** 如果要配置手动连接： `ifconfig e0a -addr=filer_addr -mask=netmask -gw=gateway-dns=dns_addr-domain=dns_domain`
+
*** filer_addr 是存储系统的 IP 地址。
*** netmask 是连接到 HA 配对节点的管理网络的网络掩码。
*** gateway 是网络的网关。
*** dns_addr 是网络上名称服务器的 IP 地址。
*** dns_domain 是域名系统（ DNS ）域名。
+
如果使用此可选参数，则无需在网络启动服务器 URL 中使用完全限定域名。您只需要服务器的主机名。





+

NOTE: 您的接口可能需要其他参数。有关详细信息，可以在固件提示符处输入 `help ifconfig` 。


