---
permalink: fas2800/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: 将电源设备、硬盘驱动器和控制器模块从受损机箱移至更换机箱、然后将受损机箱从设备机架或系统机柜更换为与受损机箱型号相同的更换机箱。 
---
= 移动并更换硬件- FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将电源设备、硬盘驱动器和控制器模块从受损机箱移至更换机箱、然后将受损机箱从设备机架或系统机柜更换为与受损机箱型号相同的更换机箱。



== 第 1 步：移动电源

在更换机箱时移出电源设备包括关闭受损机箱的电源、断开其连接并将其从受损机箱中卸下、以及在更换机箱上安装和连接该电源设备。

. 如果您尚未接地，请正确接地。
. 关闭电源并断开电源线：
+
.. 关闭电源上的电源开关。
.. 打开电源线固定器，然后从电源拔下电源线。
.. 从电源拔下电源线。


. 按压电源凸轮把手上的闩锁，然后打开凸轮把手，以便从中板完全释放电源。
. 使用凸轮把手将电源滑出系统。
+

CAUTION: 卸下电源时，请始终用双手支撑其重量。

. 对其余所有电源重复上述步骤。
. 用双手支撑电源边缘并将其与系统机箱中的开口对齐，然后使用凸轮把手将电源轻轻推入机箱。
+
电源具有键控功能，只能单向安装。

+

NOTE: 将电源滑入系统时，请勿用力过大。您可能会损坏连接器。

. 合上凸轮把手，使闩锁卡入到锁定位置，并且电源完全就位。
. 重新连接电源线，并使用电源线锁定机制将其固定到电源。
+

NOTE: 仅将电源线连接到电源。此时请勿将电源线连接到电源。





== 第 2 步：卸下控制器模块

从受损机箱中卸下一个或多个控制器模块。

. 松开将缆线绑在缆线管理设备上的钩环带，然后从控制器模块上拔下系统缆线和 SFP （如果需要），并跟踪缆线的连接位置。
+
将缆线留在缆线管理设备中，以便在重新安装缆线管理设备时，缆线排列有序。

. 从控制器模块的左右两侧卸下缆线管理设备并将其放在一旁。
. 按压凸轮把手上的闩锁，直到其释放为止，完全打开凸轮把手以从中板释放控制器模块，然后用两只手将控制器模块拉出机箱。
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[卸下控制器]

. 将控制器模块放在一旁安全的地方。
. 对机箱中的第二个控制器模块重复上述步骤。




== 第3步：将驱动器移至更换机箱

将受损机箱中每个驱动器托架开口处的驱动器移至更换机箱中的同一托架开口处。

. 从系统正面轻轻卸下挡板。
. 删除驱动器：
+
.. 按下LED另一侧的释放按钮。
.. 将凸轮把手拉至完全打开位置，以使驱动器从中板中取出，然后将驱动器轻轻滑出机箱。
+
驱动器应与机箱分离，以便滑出机箱。

+

NOTE: 卸下驱动器时，请始终用双手支撑其重量。

+

NOTE: 驱动器很脆弱。尽可能少地对其进行处理，以防止对其造成损坏。



. 将受损机箱中的驱动器与更换机箱中的同一托架开口对齐。
. 将驱动器轻轻推入机箱，直至其完全移动。
+
凸轮把手啮合并开始旋转至闭合位置。

. 将驱动器的其余部分用力推入机箱、然后将凸轮把手推入驱动器支架以锁定凸轮把手。
+
请务必缓慢地关闭凸轮把手，使其与驱动器托架前部正确对齐。如果安全，则单击。

. 对系统中的其余驱动器重复此过程。




== 第 4 步：从设备机架或系统机柜中更换机箱

从设备机架或系统机柜中卸下现有机箱、然后在设备机架或系统机柜中安装替代机箱。

. 从机箱安装点卸下螺钉。
. 在两三个人的帮助下、将受损机箱滑出系统机柜中的机架导轨或设备机架中的_L_支架、然后将其放在一旁。
. 如果您尚未接地，请正确接地。
. 由两到三人组成，通过将更换机箱引导至系统机柜中的机架导轨或设备机架中的 _L_ 支架，将更换机箱安装到设备机架或系统机柜中。
. 将机箱完全滑入设备机架或系统机柜中。
. 使用从受损机箱中卸下的螺钉将机箱前部固定到设备机架或系统机柜。
. 如果尚未安装挡板，请安装挡板。




== 第 5 步：安装控制器

将控制器模块和任何其他组件安装到替代机箱中、将其启动至维护模式。

对于在同一机箱中具有两个控制器模块的 HA 对，安装控制器模块的顺序尤为重要，因为一旦将其完全装入机箱，它就会尝试重新启动。

. 将控制器模块的末端与机箱中的开口对齐，然后将控制器模块轻轻推入系统的一半。
+

NOTE: 请勿将控制器模块完全插入机箱中，除非系统指示您这样做。

. 将控制台重新连接到控制器模块，然后重新连接管理端口。
. 对更换机箱中的第二个控制器重复上述步骤。
. 完成控制器模块的安装：
+
.. 在凸轮把手处于打开位置的情况下，用力推入控制器模块，直到它与中板并完全就位，然后将凸轮把手合上到锁定位置。
+

NOTE: 将控制器模块滑入机箱时，请勿用力过大，以免损坏连接器。

.. 如果尚未重新安装缆线管理设备，请重新安装该设备。
.. 使用钩环带将缆线绑定到缆线管理设备。
.. 对更换机箱中的第二个控制器模块重复上述步骤。


. 将电源连接到不同的电源，然后打开电源。
. 将每个控制器启动至维护模式：
+
.. 在每个控制器开始启动时，如果您看到消息 `Press Ctrl-C for Boot Menu` ，请按 `Ctrl-C` 以中断启动过程。
+

NOTE: 如果您未看到此提示，并且控制器模块启动到 ONTAP ，请输入 `halt` ，然后在 LOADER 提示符处输入 `boot_ontap` ，并在出现提示时按 `Ctrl-C` ，然后重复此步骤。

.. 从启动菜单中，选择维护模式选项。



