---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2800, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: 更换电源设备包括关闭、断开和卸下受损电源设备以及安装、连接和打开替代电源设备。 
---
= 更换电源- FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
更换电源设备包括关闭、断开和卸下受损电源设备以及安装、连接和打开替代电源设备。

系统中的所有其他组件必须正常运行；否则，您必须联系技术支持。

* 电源为冗余且可热插拔。
* 此操作步骤用于一次更换一个电源。
+

NOTE: 最好在从机箱中卸下电源后两分钟内更换电源。系统仍可正常运行，但 ONTAP 会向控制台发送有关电源降级的消息，直到更换电源为止。

* 电源可自动进行范围设置。


.动画-更换电源
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.步骤
. 根据控制台错误消息或通过电源上的 LED 确定要更换的电源。
. 如果您尚未接地，请正确接地。
. 关闭电源并断开电源线：
+
.. 关闭电源上的电源开关。
.. 打开电源线固定器，然后从电源拔下电源线。
.. 从电源拔下电源线。


. 按压电源凸轮把手上的闩锁，然后打开凸轮把手，以便从中板完全释放电源。
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[DRW 2800更换PSU IEOPS 702]

. 使用凸轮把手将电源滑出系统。
+

CAUTION: 卸下电源时，请始终用双手支撑其重量。

. 确保新电源的开关处于 OFF 位置。
. 用双手支撑电源边缘并将其与系统机箱中的开口对齐，然后使用凸轮把手将电源轻轻推入机箱。
+
电源具有键控功能，只能单向安装。

+

NOTE: 将电源滑入系统时，请勿用力过大。您可能会损坏连接器。

. 合上凸轮把手，使闩锁卡入到锁定位置，并且电源完全就位。
. 重新连接电源布线：
+
.. 将电源线重新连接到电源和电源。
.. 使用电源线固定器将电源线固定到电源。


+
电源恢复供电后，状态 LED 应为绿色。

. 打开新电源的电源，然后验证电源活动 LED 的运行情况。
+
电源联机后，电源 LED 将亮起。

. 按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"^]有关详细信息、请参见页面。

