---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2820, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: 热插拔 FAS2820 系统中的电源需要关闭、断开并卸下受损电源，然后安装、连接并开启替换电源。 
---
= 热插拔 FAS2820 系统中的电源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果 FAS2820 系统中的电源出现故障或性能下降，可在不中断系统运行的情况下对其进行热插拔更换。此过程包括关闭和移除受损电源，然后安装并接通更换电源。

如果系统中的任何其他组件无法正常工作，请与技术支持联系。

* 电源为冗余且可热插拔。
* 此操作步骤用于一次更换一个电源。
+

NOTE: 从机箱中卸下电源后，请在两分钟内更换电源。系统继续运行，但 ONTAP 会向控制台发送有关电源降级的消息，直至更换电源。

* 电源可自动进行范围设置。


.动画-更换电源
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.步骤
. 根据控制台错误消息或通过电源上的 LED 确定要更换的电源。
. 如果您尚未接地，请正确接地。
. 关闭电源并断开电源线：
+
.. 关闭电源上的电源开关。
.. 打开电源线固定器，然后从电源拔下电源线。
.. 从电源拔下电源线。


. 按压电源凸轮把手上的闩锁，然后打开凸轮把手，以便从中板完全释放电源。
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[更换PSU]

. 使用凸轮把手将电源滑出系统。
+

CAUTION: 卸下电源时，请始终用双手支撑其重量。

. 确保新电源的开关处于 OFF 位置。
. 使用双手支撑电源边缘并将其与系统机箱中的开口对齐，然后使用凸轮手柄将电源轻轻推入机箱。
+
电源具有键控功能，只能单向安装。

+

NOTE: 将电源滑入系统时，请勿用力过大。您可能会损坏连接器。

. 合上凸轮把手，使闩锁卡入到锁定位置，并且电源完全就位。
. 重新连接电源布线：
+
.. 将电源线重新连接到电源和电源。
.. 使用电源线固定器将电源线固定到电源。


+
恢复电源后，状态 LED 应为绿色。

. 打开新电源的电源，然后验证电源活动 LED 的运行情况。
+
电源联机后，电源 LED 将亮起。

. 按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"^]有关详细信息、请参见页面。

