---
permalink: asa250/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a250, replace the boot media 
summary: 在更换 ASA A250 系统中的启动介质之前，请确保满足成功更换的必要要求。 
---
= 自动启动介质恢复的要求 - ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更换 ASA A250 中的启动介质之前，请确保满足成功更换的必要要求。这包括验证您是否有正确的替换启动介质，确认受损控制器上的 e0S (e0M 扳手) 端口没有故障，并确定是否已启用板载密钥管理器 (OKM) 或外部密钥管理器 (EKM)。

只有 ONTAP 9.18.1 及更高版本才支持自动启动介质恢复过程。如果您的存储系统运行的是早期版本的 ONTAP，请使用 link:bootmedia-replace-workflow.html["手动启动恢复程序"]。

[NOTE]
====
NetApp 强烈建议您在使用的设备上启用控制台日志记录，并在执行此过程时执行以下操作：

* 在维护期间保持 AutoSupport 启用状态。这允许 NetApp 支持在发生问题时接收诊断信息。
* 为任何 CLI 会话启用会话日志记录。这将创建维护活动期间所有命令和系统输出的完整记录。有关如何启用会话日志记录的指导，请参见 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何配置 PuTTY 以优化与 ONTAP 系统的连接"^]。


====
* 您必须使用与从NetApp收到的容量相同的替代FRU组件来更换故障组件。
* 确认受损控制器上的 e0S 接口（e0M wrench 端口）无故障。
+
e0M 端口用于在自动启动恢复过程中在两个控制器之间进行通信。

* 对于 OKM，您需要集群范围的密码以及备份数据。
* 对于EMM、您需要配对节点上以下文件的副本：
+
** /cfcard/kmip/servers.cfg文件。
** /cfcard/kmip/certs/client.crt文件。
** /cfcard/kmip/certs client.key文件。
** /cfcard/kmip/certs或CA.prom文件。


* 更换受损的启动介质时，将命令应用到正确的控制器至关重要：
+
** _受损控制器_是您正在执行维护的控制器。
** _健康控制器_是受损控制器的 HA 伙伴。




.下一步行动
查看引导介质要求后，您可以link:bootmedia-shutdown-bmr.html["关闭控制器"]。
