---
permalink: c30-60/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, replace the chassis 
summary: 使用与受损机箱型号相同的新机箱更换受损机箱。 
---
= 更换机箱的要求- AFF C30和AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更换AFF C30或AFF C60系统中的机箱之前、请确保满足成功更换的必要要求。其中包括验证系统中的所有其他组件是否正常工作、验证是否具有正确的更换机箱以及必要的工具。

在更换机箱之前、请务必查看以下要求和注意事项。



== 要求

* 更换的机箱必须与受损机箱型号相同。此过程适用于相似更换、而不适用于升级。
* 存储系统中的所有其他组件都必须正常运行；否则、您必须先联系、 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"]然后再继续此过程。




== 注意事项

* *机箱更换过程会造成系统中断。*For a two-node cluster, you will have a complete service outage and a partial outage in a multi-node cluster.
* 您可以对存储系统支持的所有ONTAP版本使用机箱更换过程。
* 在编写机箱更换过程时、假设您要将挡板、驱动器、任何驱动器挡片和控制器移至新机箱。
* 如果需要、您可以打开存储系统位置(蓝色) LED、以帮助您以物理方式定位受影响的存储系统。使用SSH登录到BMC并输入 `system location-led _on_`命令。
+
存储系统具有三个定位LED：操作员显示面板上一个、每个控制器上一个。Location LEDs remain illuminated for 30 minutes.

+
您可以输入命令将其关闭 `system location-led _off_`。如果您不确定LED是亮起还是熄灭、可以输入命令来检查其状态 `system location-led show`。



.下一步是什么？
查看机箱更换要求后、您需要link:chassis-replace-shutdown.html["关闭控制器"]
