---
permalink: c30-60/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, prerequisite, replace the controller module 
summary: 在更换AFF C30或AFF C60系统中的控制器之前、请确保满足成功更换控制器所需的要求。这包括验证系统中的所有其他组件是否正常运行、验证是否具有正确的替代控制器以及将控制器的控制台输出保存到文本日志文件。 
---
= 更换控制器的要求- AFF C30和AFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在更换AFF C30或AFF C60系统中的控制器之前、请确保满足成功更换控制器所需的要求。这包括验证系统中的所有其他组件是否正常运行、验证是否具有正确的替代控制器以及将控制器的控制台输出保存到文本日志文件。

您必须查看控制器更换过程的要求和注意事项。



== 要求

* 所有磁盘架都必须正常工作。
* 运行正常的控制器必须能够接管要更换的控制器（在本操作步骤 中称为 "`受损控制器` " ）。
* 您必须将控制器更换为相同型号类型的控制器。您不能仅通过更换控制器来升级系统。
* 在此过程中、您不能更改任何驱动器或磁盘架。
* 您必须始终将控制器的控制台输出捕获到文本日志文件中。
+
此控制台输出记录了可用于解决更换过程中可能遇到的问题的过程。





== 注意事项

* 请务必将此过程中的命令应用于正确的控制器：
+
** 受损控制器是指要更换的控制器。
** _replacement_ 控制器是一个新控制器，用于更换受损的控制器。
** _health_ 控制器是运行正常的控制器。


* 如果需要、您可以打开存储系统位置(蓝色) LED、以帮助您以物理方式定位受影响的存储系统。使用SSH登录到BMC并输入 `system location-led _on_`命令。
+
存储系统具有三个定位LED：操作员显示面板上一个、每个控制器上一个。Location LEDs remain illuminated for 30 minutes.

+
您可以输入命令将其关闭 `system location-led _off_`。如果您不确定LED是亮起还是熄灭、可以输入命令来检查其状态 `system location-led show`。



.下一步是什么？
查看更换AFF C30或AFF C60控制器的要求后，您需要link:controller-replace-shutdown.html["关闭受损控制器"]。
