---
permalink: c250/drive-replace.html 
sidebar: sidebar 
keywords: aff c250, replace the drives 
summary: 如果平台向系统控制台记录一条警告消息，指出驱动器出现故障，则必须更换驱动器。In addition, both the fault LED on the operator display panel and the fault LED on the failed drive are illuminated. 
---
= 更换SSD驱动器—AFF C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在I/O运行期间无中断更换发生故障的SSD驱动器。

When a drive fails, the platform logs a warning message to the system console indicating which drive has failed.In addition, both the fault LED on the operator display panel and the fault LED on the failed drive are illuminated.

.开始之前
* 在更换驱动器之前，请遵循最佳实践并安装最新版本的磁盘认证包（ DQP ）。
* Identify the failed disk drive by running the `storage disk show -broken` command from the system console.
+
The failed drive appears in the list of failed drives.If it does not, you should wait, and then run the command again.

+
该驱动器可能需要长达数小时才能显示在故障驱动器列表中。

* 确定是否已启用 SED 身份验证。
+
如何更换磁盘取决于磁盘驱动器的使用方式。如果启用了 SED 身份验证，则必须使用 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["《 ONTAP 9 NetApp 加密高级指南》"]。这些说明描述了更换 SED 之前和之后必须执行的附加步骤。

* 确保您的平台支持替换的驱动器。看 https://hwu.netapp.com["NetApp Hardware Universe"]。
* 确保系统中的所有其他组件均正常运行；否则，您必须联系技术支持。


.关于此任务
在固件版本不是最新的新驱动器上，驱动器固件会自动更新（无中断）。

更换多个磁盘驱动器时、在移除每个故障磁盘驱动器与插入更换磁盘驱动器之间、必须等待70秒、以使存储系统能够识别是否存在每个新磁盘。

您可以手动分配驱动器所有权，然后在此操作步骤中稍后重新启用自动驱动器分配。

.步骤
. 如果您想手动分配替换驱动器的驱动器所有权，则需要禁用自动驱动器分配（如果已启用）。
+
.. 验证是否已启用自动驱动器分配： `storage disk option show`
+
您可以在任一控制器模块上输入命令。

+
如果启用了自动驱动器分配，则输出会在 "`Auto Assign` " 列中显示 `on` （对于每个控制器模块）。

.. 如果启用了自动驱动器分配，请将其禁用： `storage disk option modify -node node_name -autodassign off`
+
您必须在两个控制器模块上禁用自动驱动器分配。



. 正确接地。
. 以物理方式确定故障驱动器。
+
驱动器发生故障时，系统会向系统控制台记录一条警告消息，指示哪个驱动器发生故障。此外，驱动器架操作员显示面板上的警示（琥珀色） LED 和故障驱动器将亮起。

+

NOTE: 故障驱动器上的活动（绿色） LED 可能会亮起（稳定亮起），表示驱动器已通电，但不应闪烁，这表示 I/O 活动。故障驱动器没有 I/O 活动。

. 删除故障驱动器：
+
.. 按下驱动器表面上的释放按钮以打开凸轮把手。
.. 使用凸轮把手将驱动器滑出磁盘架，并用另一只手支撑驱动器。


. 请至少等待 70 秒，然后再插入替代驱动器。
+
这样，系统就可以识别出驱动器已被删除。

. 插入替代驱动器：
+
.. 在凸轮把手处于打开位置的情况下，用双手插入替代驱动器。
.. 按，直到驱动器停止。
.. 合上凸轮把手、使驱动器完全固定在中板中、并且把手卡入到位。
+
请务必缓慢地关闭凸轮把手，使其与驱动器正面正确对齐。



. 验证驱动器的活动（绿色） LED 是否亮起。
+
如果驱动器的活动 LED 稳定亮起，则表示驱动器已通电。当驱动器的活动 LED 闪烁时，表示驱动器已通电且 I/O 正在进行中。如果驱动器固件正在自动更新，则 LED 将闪烁。

. 如果要更换另一个驱动器，请重复步骤 3 至 7。
. 如果您在步骤1中禁用了自动驱动器分配、请手动分配驱动器所有权、然后根据需要重新启用自动驱动器分配。
+
.. 显示所有未拥有的驱动器：
+
`storage disk show -container-type unassigned`

+
您可以在任一控制器模块上输入命令。

.. 分配每个驱动器：
+
`storage disk assign -disk disk_name -owner node_name`

+
您可以在任一控制器模块上输入命令。

+
您可以使用通配符一次分配多个驱动器。

.. 如果需要、重新启用自动驱动器分配：
+
`storage disk option modify -node node_name -autoassign on`

+
您必须在两个控制器模块上重新启用自动驱动器分配。



. 按照套件随附的 RMA 说明将故障部件退回 NetApp 。
+
接触 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"]如果您需要 RMA 号码或更换程序的额外帮助。


