---
permalink: asa-r2-a1k/nvdimm-battery-replace.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the nv battery, NV battery 
summary: To replace the NV battery, you must remove the controller module, remove the battery, replace the battery, and then reinstall the controller module. 
---
= 更换NV电池- ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
To replace the NV battery, you must remove the controller module, remove the battery, replace the battery, and then reinstall the controller module.

系统中的所有其他组件必须正常运行；否则，您必须联系技术支持。



== 第 1 步：关闭受损控制器

关闭或接管受损控制器。

要关闭受损控制器，您必须确定控制器的状态，并在必要时接管控制器，以便运行正常的控制器继续从受损控制器存储提供数据。

.关于此任务
* 如果您使用的是SAN系统，则必须已检查受损控制器SCSI刀片的事件消息  `cluster kernel-service show`。 `cluster kernel-service show`命令(在priv高级模式下)可显示节点名称、该节点的仲裁状态、该节点的可用性状态以及该节点的运行状态。
+
每个 SCSI 刀片式服务器进程应与集群中的其他节点保持仲裁关系。在继续更换之前，必须先解决所有问题。

* If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示false、则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。


.步骤
. 如果启用了AutoSupport、则通过调用AutoSupport消息禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
以下AutoSupport 消息禁止自动创建案例两小时： `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
+

NOTE: 当您看到_Do you want to disable auto-giveback？_时、输入`y`。

. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
正在等待交还
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符
 a| 
从运行正常的控制器接管或暂停受损的控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===




== 第 2 步：卸下控制器模块

在更换控制器模块或更换控制器模块内部的组件时、您必须从机柜中卸下控制器模块。

. 检查系统插槽4/5中的NVRAM状态指示灯。控制器模块的前面板上还有一个NVRAM LED。查找NV图标：
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[NVRAM警示和状态LED位置图]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["标注编号1、宽度=30制"]
 a| 
NVRAM 状态 LED



 a| 
image:../media/legend_icon_02.svg["标注编号1、宽度=30制"]
 a| 
NVRAM警示LED

|===
+

NOTE: 如果NVRAM状态LED闪烁、则可能表示控制器模块未被接管或正常暂停(未提交的数据)。如果受损控制器模块未被配对控制器模块成功接管、请先联系、 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"] 然后再继续此过程。

+
受损控制器模块上的NVRAM状态LED的一般行为如下：

+
** 当控制器模块断电且控制器模块处于"正在等待恢复"状态、或者控制器模块未被正确接管或暂停(未提交的数据)时、NVRAM状态LED会闪烁。
** 从机柜中卸下控制器模块后、NVRAM状态LED会闪烁、这可能意味着控制器模块未被接管或暂停(未提交的数据)。确认此控制器模块已被配对控制器模块完全接管，或者受损控制器模块显示 `waiting for giveback`。然后、可以忽略闪烁的LED指示灯(并且可以从机柜中卸下控制器)。


. 如果您尚未接地，请正确接地。
. 在设备正面、将手指钩入锁定凸轮上的孔中、挤压凸轮杆上的卡舌、然后同时朝您的方向轻轻而稳固地旋转两个闩锁。
+
控制器模块会稍微移出机柜。

+
image::../media/drw_a1k_pcm_remove_replace_ieops-1375.svg[控制器删除图形]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["标注编号1、宽度=30制"]
| A锁定凸轮锁扣 
|===
. 将控制器模块滑出机箱、然后将其放在平稳的表面上。
+
将控制器模块滑出机柜时、请确保支撑好其底部。





== 第3步：更换NV电池

从控制器模块中取出发生故障的NV电池、然后安装更换用的NV电池。

. 打开空气管道盖、找到NV电池。
+
image::../media/drw_a1k_remove_replace_nvmembat_ieops-1379.svg[重新调整NV电池的速度]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["标注编号1、Wides=30bex"]
| NV蓄电池空气管道盖 


 a| 
image:../media/legend_icon_02.svg["标注编号2、宽度=30个"]
 a| 
NV电池插头

|===
. 向上提起蓄电池以接触蓄电池插头。
. 挤压电池插头表面的夹子以从插座中释放插头、然后从插座中拔下电池电缆。
. 将电池从空气管道和控制器模块中提出、然后放在一旁。
. 从包装中取出更换用电池。
. 将更换用的电池组安装到控制器中：
+
.. 将电池插头插入提升板插槽，并确保插头锁定到位。
.. 将电池组插入插槽，然后用力向下按电池组，以确保其锁定到位。


. 合上NV空气管道盖。
+
确保插头锁定在插槽中。





== 第 4 步：重新安装控制器模块

重新安装并启动控制器模块。

. 如果尚未关闭此通风管，请关闭此通风管。
. 将控制器模块的一端与机柜中的开口对齐、然后将控制器模块滑入机箱、使拉杆从系统正面转开。
. 一旦控制器模块阻止您进一步滑动、请向内旋转凸轮把手、直到它们在风扇下锁紧
+

NOTE: 将控制器模块滑入机箱时、请勿用力过度、以免损坏连接器。

+
控制器模块在盘柜中完全就位后、即开始启动。

. 使用 `storage failover modify -node local -auto-giveback true` 命令禁用自动交还后，可将其还原。
. 如果启用了AutoSupport、请使用命令还原/取消禁止自动创建案例 `system node autosupport invoke -node * -type all -message MAINT=END` 。




== 第 5 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"]有关详细信息、请参见页面。
