= 第 1 步：验证并设置机箱的 HA 状态
:allow-uri-read: 


您必须按照套件附带的RMA说明验证机箱的HA状态并将故障部件退回给NetApp。



== 第 1 步：验证并设置机箱的 HA 状态

您必须验证机箱的 HA 状态，并在必要时更新此状态以匹配您的系统配置。

. 在维护模式下，从任一控制器模块显示本地控制器模块和机箱的 HA 状态： `ha-config show`
+
所有组件的 HA 状态都应相同。

. 如果为机箱显示的系统状态与您的系统配置不匹配：
+
.. 设置机箱的 HA 状态： `ha-config modify chassis _ha-state_`
+
ha-state_ 的值可以是以下值之一：

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mCCIP`
*** `non-ha`


.. 确认设置已更改： `ha-config show`


. 如果尚未执行此操作，请重新对系统的其余部分进行布线。
. 重新安装系统正面的挡板。




== 第2步：在双节点MetroCluster配置中切回聚合

此任务仅限适用场景双节点 MetroCluster 配置。

.步骤
. 验证所有节点是否处于 `enabled` 状态： `MetroCluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 验证所有 SVM 上的重新同步是否已完成： `MetroCluster SVM show`
. 验证修复操作正在执行的任何自动 LIF 迁移是否已成功完成： `MetroCluster check lif show`
. 在运行正常的集群中的任何节点上使用 `MetroCluster switchback` 命令执行切回。
. 验证切回操作是否已完成： `MetroCluster show`
+
当集群处于 `waiting for-switchback` 状态时，切回操作仍在运行：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
当集群处于 `normal` 状态时，切回操作完成。：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切回需要很长时间才能完成，您可以使用 `MetroCluster config-replication resync-status show` 命令检查正在进行的基线的状态。

. 重新建立任何 SnapMirror 或 SnapVault 配置。




== 第 3 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"]有关详细信息、请参见页面。
