= 
:allow-uri-read: 


如果存储系统具有可用插槽、请将新的I/O模块安装到其中一个可用插槽中。如果所有插槽均已占用、请卸下现有I/O模块以留出空间、然后安装新模块。

.开始之前
* 检查 https://hwu.netapp.com/["NetApp Hardware Universe"^] 以确保新的I/O模块与您的存储系统和您正在运行的ONTAP版本兼容。
* If multiple slots are available, check the slot priorities in https://hwu.netapp.com/["NetApp Hardware Universe"^] and use the best one available for your I/O module.
* 确保所有其他组件均正常运行。


[role="tabbed-block"]
====
.将I/O模块添加到可用插槽
--
您可以将新的I/O模块添加到具有可用插槽的存储系统中。

.步骤
. 如果您尚未接地，请正确接地。
. 向下旋转缆线管理托架、方法是拉动缆线管理托架内部的按钮、然后向下旋转。
. 从托架上卸下目标插槽空白模块：
+
.. 按下目标插槽中空白模块上的凸轮闩锁。
.. 将凸轮闩锁尽可能远离模块。
.. 将手指插入凸轮拉杆开口中、然后将模块拉出机箱、从而将模块从机箱中卸下。


. 安装 I/O 模块：
+
.. 将I/O模块与机柜插槽开口的边缘对齐。
.. 将模块轻轻地滑入插槽，直至完全滑入机箱，然后将凸轮闩锁一直向上旋转，以将模块锁定到位。


. 使用缆线将I/O模块连接到指定设备。
+

NOTE: 确保所有未使用的 I/O 插槽都安装了空格，以防止可能出现散热问题。

. 将缆线管理托架向上旋转到关闭位置。
. 从Loader提示符处、重新启动节点：
+
`bye`

+

NOTE: 此操作将重新初始化I/O模块和其他组件、然后重新启动节点。

. 从配对控制器交还控制器：
+
`storage failover giveback -ofnode target_node_name`

. 对控制器 B 重复上述步骤
. 在运行状况良好的节点上、如果禁用了自动交还、请将其还原：
+
`storage failover modify -node local -auto-giveback _true_`

. 如果启用了AutoSupport、则还原自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.将I/O模块添加到完全填充的系统
--
您可以通过卸下现有I/O模块并在其位置安装新的I/O模块、将I/O模块添加到完全填充的系统中。

.关于此任务
确保您了解将新I/O模块添加到完全填充的系统的以下情形：

[cols="1,2"]
|===
| 场景 | 需要执行操作 


 a| 
NIC到NIC (端口数相同)
 a| 
LIF 将在其控制器模块关闭时自动迁移。



 a| 
NIC到NIC (端口数不同)
 a| 
将选定的生命周期重新分配到其他主端口。有关详细信息、请参见 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["迁移 LIF"^] 。



 a| 
通过NIC连接到存储I/O模块
 a| 
使用 System Manager 将 LIF 永久迁移到不同的主端口，如中所述 https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["迁移 LIF"^]。

|===
.步骤
. 如果您尚未接地，请正确接地。
. 拔下目标 I/O 模块上的所有布线。
. 向下旋转缆线管理托架、方法是拉动缆线管理托架内部的按钮、然后向下旋转。
. 从机箱中卸下目标 I/O 模块：
+
.. 按下凸轮闩锁按钮。
.. 将凸轮闩锁尽可能远离模块。
.. 将手指插入凸轮拉杆开口中、然后将模块拉出机箱、从而将模块从机箱中卸下。
+
确保跟踪 I/O 模块所在的插槽。



. 将I/O模块安装到机柜中的目标插槽中：
+
.. 将模块与机柜插槽开口的边缘对齐。
.. 将模块轻轻地滑入插槽，直至完全滑入机箱，然后将凸轮闩锁一直向上旋转，以将模块锁定到位。


. 使用缆线将I/O模块连接到指定设备。
. 重复拆卸和安装步骤以更换控制器的其他模块。
. 将缆线管理托架向上旋转到关闭位置。
. 从加载程序提示符：_BYE_重新启动控制器
+
此操作将重新初始化PCIe卡和其他组件、并重新启动节点。

+

NOTE: 如果您在重新启动期间遇到问题描述 、请参见 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1494308["BURT 1494308 -更换I/O模块期间可能触发环境关闭"]

. 从配对控制器交还控制器：
+
`storage failover giveback -ofnode target_node_name`

. 如果已禁用自动交还、请启用此功能：
+
`storage failover modify -node local -auto-giveback true`

. 执行以下操作之一：
+
** 如果您卸下了NIC I/O模块并安装了新的NIC I/O模块、请对每个端口使用以下network命令：
+
`storage port modify -node *_<node name>__ -port *_<port name>__ -mode network`

** 如果您卸下了NIC I/O模块并安装了存储I/O模块，请按照中所述安装NS224磁盘架并为其布线link:../ns224/hot-add-shelf-overview.html["热添加工作流"]。


. 对控制器 B 重复上述步骤


--
====