= 
:allow-uri-read: 


 `boot_recovery -partner`对于运行ONTAP 9．16.0及更高版本的ASA R2平台、您可以使用命令从配对节点还原ONTAP映像(启动介质恢复)。

.开始之前
当您启动某个节点且该节点上的启动介质损坏时、您将在Loader提示符处看到以下消息以及启动过程STOP：

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
如果您看到此消息、则必须还原ONTAP映像

.步骤
. 在Loader提示符处、输入_boot_recovery -Partner_命令。
+
屏幕将显示消息 `Starting boot media recovery (BMR) process press Ctrl-C to abort...`并开始初始检查。

. 在Loader配置本地集群端口并通过执行网络启动时监控此过程 `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`。
+
网络启动运行后、 `Starting BMR ...`屏幕上会显示、并且安装过程将完成。

+
.. 如果未配置密钥管理器、您将看到以下消息：
+
....
key manager is not configured. Exiting.
....
.. 如果您看到以下消息、则表示已配置板载密钥管理器(Onboard Key Manager、OKM)：
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
转至以完成恢复过程。

.. 如果您看到以下消息、则表示已配置外部密钥管理器(EKM)。转到EMM主题并完成恢复过程：
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. 监控从配对系统执行还原备份配置、env文件、MDB和rdb的BRE过程。
. 如果出现以下情况、则节点将重新启动、并且B完善 了BBR:


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....