= 
:allow-uri-read: 


You can replace a failed drive nondisruptively while I/O is in progress.

.开始之前
* 存储系统必须支持您要安装的驱动器。
+
https://hwu.netapp.com["NetApp Hardware Universe"^]

* 如果启用了自加密驱动器(SED)身份验证、则必须按照ONTAP文档中的SED更换说明进行操作。
+
ONTAP 文档中的说明介绍了在更换 SED 之前和之后必须执行的其他步骤。

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["使用命令行界面概述 NetApp 加密"^]

* 存储系统中的所有其他组件都必须正常运行、否则、您必须先联系、 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"]然后再继续此过程。
* 验证要删除的驱动器是否出现故障。
+
您可以运行 `storage disk show -broken` 命令来验证驱动器是否出现故障。故障驱动器将显示在故障驱动器列表中。如果不是，则应等待，然后重新运行命令。

+

NOTE: 根据驱动器类型和容量，该驱动器可能需要长达数小时才能显示在故障驱动器列表中。



.关于此任务
* 更换故障驱动器时、您必须在卸下驱动器和插入替代驱动器之间等待70秒、以使存储系统能够识别驱动器已卸下。
* 最佳实践是、在热插拔驱动器之前、安装磁盘认证包(DQP)的最新版本。
+
安装最新版本的 DQP 后，您的系统便可识别和使用新认证的驱动器。这样可以避免出现有关驱动器信息不最新以及由于无法识别驱动器而阻止驱动器分区的系统事件消息。DQP 还会通知您驱动器固件不是最新的。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["NetApp 下载：磁盘认证包"^]

* 最佳实践是、在更换FRU组件之前、应在系统上安装最新版本的NVMe磁盘架模块(NSM)固件和驱动器固件。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 下载：磁盘架固件"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 下载：磁盘驱动器固件"^]

+
[NOTE]
====
请勿将固件还原到不支持您的磁盘架及其组件的版本。

====
* 在固件版本不是最新的新驱动器上，驱动器固件会自动更新（无中断）。
+

NOTE: 驱动器固件检查每两分钟进行一次。

* 如果需要、您可以打开存储系统位置(蓝色) LED、以帮助您以物理方式定位受影响的存储系统。使用SSH登录到BMC并输入 `system location-led _on_`命令。
+
存储系统具有三个定位LED：操作员显示面板上一个、每个控制器上一个。Location LEDs remain illuminated for 30 minutes.

+
您可以输入命令将其关闭 `system location-led _off_`。如果您不确定LED是亮起还是熄灭、可以输入命令来检查其状态 `system location-led show`。


