= 
:allow-uri-read: 


要使用此过程，您的存储系统必须运行 ONTAP 9.17.1 或更高版本，并且您的存储系统必须满足运行的 ONTAP 版本的所有要求。


NOTE: 如果您的存储系统未运行 ONTAP 9.17.1 或更高版本，或者不满足您的存储系统运行的 ONTAP 版本的所有要求，则无法使用此操作步骤，必须使用 link:io-module-replace.html["更换 I/O 模块程序"]。

[role="tabbed-block"]
====
.ONTAP 9.17.1 或 9.18.1RC
--
* 您正在使用等效的 I/O 模块热插拔插槽 4 中的故障群集和 HA I/O 模块。无法更改 I/O 模块类型。
* 具有故障集群和 HA I/O 模块的控制器（受损控制器）必须已经接管了正常的合作伙伴控制器。如果 I/O 模块出现故障，则应自动进行接管。
+
对于双节点群集，存储系统无法识别哪个控制器具有出现故障的 I/O 模块，因此任一控制器都可能启动接管。仅当具有故障 I/O 模块的控制器（受损控制器）已接管健康控制器时，才支持热插拔。热插拔 I/O 模块是恢复而不会中断的唯一方法。

+
您可以通过输入以下命令来验证受损控制器是否成功接管了健康控制器 `storage failover show`命令。

+
如果您不确定哪个控制器的 I/O 模块出现故障，请联系 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"] 。

* 您的存储系统配置必须仅有一个位于插槽 4 中的集群和 HA I/O 模块，而不是两个集群和 HA I/O 模块。
* 您的存储系统必须是双节点（无交换机或有交换机）集群配置。
* 存储系统中的所有其他组件都必须正常运行；如果未正常运行、请先联系、 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"]然后再继续此过程。


--
.ONTAP 9.18.1GA 或更高版本
--
* 您正在热插拔任何插槽中的以太网 I/O 模块，该插槽具有用于集群、HA 和客户端的任意端口组合，并具有等效的 I/O 模块。无法更改 I/O 模块类型。
+
具有用于存储或 MetroCluster 的端口的以太网 I/O 模块不可热插拔。

* 您的存储系统（无交换机或交换机集群配置）可以具有存储系统支持的任意数量的节点。
* 集群中的所有节点都必须运行相同的 ONTAP 版本（ONTAP 9.18.1GA 或更高版本）或运行相同 ONTAP 版本的不同补丁级别。
+
如果集群中的节点运行不同的 ONTAP 版本，则视为混合版本集群，不支持热插拔 I/O 模块。



* 存储系统中的控制器可以处于以下状态之一：
+
** 两个控制器都可以启动并运行 I/O（提供数据）。
** 如果接管是由故障的 I/O 模块引起的，并且控制器在其他方面正常工作，则任一控制器都可能处于接管状态。
+
在某些情况下，由于 I/O 模块故障，ONTAP 可以自动接管任一控制器。例如，如果出现故障的 I/O 模块包含所有群集端口（该控制器上的所有群集链接都将关闭），ONTAP 会自动执行接管。





* 存储系统中的所有其他组件都必须正常运行；如果未正常运行、请先联系、 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"]然后再继续此过程。


--
====