= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AFF 系统
--
AFF A系列和AFF C系列系统提供了一个专为虚拟化环境量身定制的强大横向扩展平台。它们可以作为独立系统部署、也可以作为NetApp ONTAP配置中的高性能层部署。link:https://www.netapp.com/data-storage/all-flash-san-storage-array["详细了解AFF系统"](英文)

从以下ONTAP版本开始、支持AFF A系列和AFF C系列系统。

ONTAP 9.16.1.::
+
--
* AFF A20
* AFF A30
* AFF A50
* AFF C30
* AFF C60
* AFF C80


--
ONTAP 9.15.1.::
+
--
* AFF A1K
* AFF A70
* AFF A90


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10.1::
+
--
* AFF A900


--
ONTAP 9.8::
+
--
* AFF A250


--
ONTAP 9.7::
+
--
* AFF A400
* AFF A800


--


--
.ASA r2系统
--
ASA R2系统提供统一的硬件和软件解决方案、可根据仅SAN客户的需求提供简化的体验。link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["详细了解ASA R2系统"](英文)

从以下ONTAP版本开始、支持ASA R2系统。

ONTAP 9.17.1.::
+
--
* ASA C30


--
ONTAP 9.16.1.::
+
--
* ASA A20
* ASA A30
* ASA A50


--
ONTAP 9.16.0.::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.ASA 系统
--
ASA A系列和ASA C系列系统提供简化的专用SAN体验、可使用FCP或iSCSI协议为企业级任务关键型数据库和其他SAN工作负载提供持续的数据可用性。link:https://www.netapp.com/data-storage/all-flash-san-storage-array["详细了解ASA系统"](英文)

从以下ONTAP版本开始、支持ASA系统。

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9.8::
+
--
* ASA AFF A250
* ASA AFF A800


--
ONTAP 9.7::
+
--
* ASA AFF A400


--


--
.FAS 系统
--
FAS系统可提供高效安全的二级存储、这是用于分层、备份和灾难恢复的终极解决方案。link:https://www.netapp.com/data-storage/fas/["详细了解FAS系统"](英文)

从以下ONTAP版本开始、支持FAS系统。

ONTAP 9.16.1.::
+
--
* FAS50


--
ONTAP 9.15.1.::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1::
+
--
* FAS2820


--
ONTAP 9.11.1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9.7::
+
--
* FAS2750
* FAS8300
* FAS8700


--


--
.驱动器架
--
驱动器架专为NetApp AFF、ASA和FAS系统设计、可帮助您提供数字化转型所需的性能、故障恢复能力和灵活性。

从以下ONTAP版本开始提供驱动器架。

ONTAP 9.16.1.:: 具有NSM100B模块的NS224
ONTAP 9.6:: 具有NSM100模块的NS224磁盘架


--
====