= 


在关闭并停用 node1 之前，您需要记录有关其集群网络，管理和 FC 端口以及 NVRAM 系统 ID 的信息。稍后将 node1 映射到 node3 并重新分配磁盘时，您需要在操作步骤中提供此信息。

.步骤
. 【第 1 步】输入以下命令并捕获其输出：
+
`network route show`

+
系统将显示类似于以下示例的输出：

+
[listing]
----
 cluster::> network route show

 Vserver        Destination    Gateway      Metric
  -------------- -------------- ----------- -------
  iscsi vserver  0.0.0.0/0      10.10.50.1  20
  node1          0.0.0.0/0      10.10.20.1  10
  ....
  node2          0.0.0.0/0      192.169.1.1 20
----
. 输入以下命令并捕获其输出：
+
`vserver services name-service dns show`

+
系统将显示类似于以下示例的输出：

+
[listing]
----
 cluster::> vserver services name-service dns show
                                                               Name
 Vserver        State     Domains                              Servers
 -------------- --------- ------------------------------------ ---------------
 node 1 2       enabled   alpha.beta.gamma.netapp.com          10.10.60.10,
                                                               10.10.60.20
 vs_base1       enabled   alpha.beta.gamma.netapp.com,         10.10.60.10,
                          beta.gamma.netapp.com,               10.10.60.20
 ...
 ...
 vs peer1        enabled  alpha.beta.gamma.netapp.com,         10.10.60.10,
                          gamma.netapp.com                     10.10.60.20
----
. [[man_record_node1_step3]] 在任一控制器上输入以下命令，以查找 node1 上的集群网络和节点管理端口：
+
`network interface show -curr-node <node1> -role cluster ， intercluster ， node-mgmt ， cluster-mgmt`

+
系统将显示集群中节点的集群，集群间，节点管理和集群管理 LIF ，如以下示例所示：

+
[listing]
----
 cluster::> network interface show -curr-node <node1>
            -role cluster,intercluster,node-mgmt,cluster-mgmt

              Logical       Status     Network            Current  Current Is
  Vserver     Interface     Admin/Oper Address/Mask       Node     Port    Home
  ----------- ------------- ---------- ------------------ -------- ------- ----
  vserver1
              cluster mgmt   up/up     192.168.x.xxx/24   node1    e0c     true
  node1
              intercluster   up/up     192.168.x.xxx/24   node1    e0e     true
              clus1          up/up     169.254.xx.xx/24   node1    e0a     true
              clus2          up/up     169.254.xx.xx/24   node1    e0b     true
              mgmt1          up/up     192.168.x.xxx/24   node1    e0c     true
 5 entries were displayed.
----
+

NOTE: 您的系统可能没有集群间 LIF 。

. 捕获中命令输出中的信息 <<man_record_node1_step3,第 3 步>> 以在部分中使用 link:map_ports_node1_node3.html["将端口从 node1 映射到 node3"]。
+
要将新控制器端口映射到旧控制器端口，需要提供输出信息。

. 在 node1 上输入以下命令：
+
`network port show -node <node1> -type physical`

+
系统将显示节点上的物理端口，如以下示例所示：

+
[listing]
----
 sti8080mcc-htp-008::> network port show -node sti8080mcc-htp-008 -type physical

 Node: sti8080mcc-htp-008

                                                                  Ignore
                                            Speed(Mbps)  Health   Health
 Port  IPspace  Broadcast Domain Link MTU   Admin/Oper   Status   Status
 ----  -------  ---------------- ---- ----  -----------  -------  -------
 e0M   Default  Mgmt             up   1500  auto/1000    healthy  false
 e0a   Default  Default          up   9000  auto/10000   healthy  false
 e0b   Default  -                up   9000  auto/10000   healthy  false
 e0c   Default  -                down 9000  auto/-       -        false
 e0d   Default  -                down 9000  auto/-       -        false
 e0e   Cluster  Cluster          up   9000  auto/10000   healthy  false
 e0f   Default  -                up   9000  auto/10000   healthy  false
 e0g   Cluster  Cluster          up   9000  auto/10000   healthy  false
 e0h   Default  Default          up   9000  auto/10000   healthy  false
 9 entries were displayed.
----
. 记录端口及其广播域。
+
稍后，需要在操作步骤中将广播域映射到新控制器上的新端口。

. 在 node1 上输入以下命令：
+
`network fcp adapter show -node <node1>`

+
系统将显示节点上的 FC 端口，如以下示例所示：

+
[listing]
----
 cluster::> fcp adapter show -node <node1>
                      Connection  Host
 Node         Adapter Established Port Address
 ------------ ------- ----------- ------------
 node1
               0a     ptp         11400
 node1
               0c     ptp         11700
 node1
               6a     loop        0
 node1
               6b     loop        0
 4 entries were displayed.
----
. 记录端口。
+
稍后在操作步骤中映射新控制器上的新 FC 端口需要输出信息。

. 如果您之前没有这样做，请输入以下命令，检查 node1 上是否配置了接口组或 VLAN ：
+
`network port ifgrp show`

+
`network port vlan show`

+
您将使用部分中的信息 link:map_ports_node1_node3.html["将端口从 node1 映射到 node3"]。

. 执行以下操作之一：
+
[cols="60,40"]
|===
| 如果您 ... | 那么 ... 


| 已在部分中记录 NVRAM 系统 ID 编号 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。 | 转到下一部分， link:retire_node1.html["停用 node1"]。 


| 未在部分中记录 NVRAM 系统 ID 编号 link:prepare_nodes_for_upgrade.html["准备要升级的节点"] | 完成 <<man_record_node1_step11,第 11 步>> 和 <<man_record_node1_step12,第 12 步>> 然后继续 link:retire_node1.html["停用 node1"]。 
|===
. 【 man_record_node1_step11]] 在任一控制器上输入以下命令：
+
`ssystem node show -instance -node <node1>`

+
系统将显示 node1 的相关信息，如以下示例所示：

+
[listing]
----
 cluster::> system node show -instance -node <node1>
                              Node: node1
                             Owner:
                          Location: GDl
                             Model: FAS6240
                     Serial Number: 700000484678
                         Asset Tag: -
                            Uptime: 20 days 00:07
                   NVRAM System ID: 1873757983
                         System ID: 1873757983
                            Vendor: NetApp
                            Health: true
                       Eligibility: true
----
. [[man_record_node1_step12]] 记录要在部分中使用的 NVRAM 系统 ID 编号 link:install_boot_node3.html["安装并启动 node3"]。

