= 
:allow-uri-read: 


在将 node1 替换为 node3 之前，您需要先使用 storage aggregate relocation 命令将非根聚合从 node1 移动到 node2 ，然后再验证重新定位。

.步骤
. 【第 1 步】通过完成以下子步骤重新定位非根聚合：
+
.. 将权限级别设置为高级：
+
`set -privilege advanced`

.. 输入以下命令：
+
`storage aggregate relocation start -node <node1> -destination <node2>-aggregate-list * -no-controller-upgrade true`

.. 出现提示时，输入 `y` 。
+
重新定位将在后台进行。重新定位聚合可能需要几秒到几分钟的时间。时间包括客户端中断和非中断部分。此命令不会重新定位任何脱机或受限聚合。

.. 输入以下命令，返回到管理员级别：
+
`set -privilege admin`



. 在 node1 上输入以下命令，以检查重新定位状态：
+
`storage aggregate relocation show -node <node1>`

+
重新定位聚合后，输出将显示该聚合的 `D1` 。

+

NOTE: 等待 node1 拥有的所有非根聚合重新定位到 node2 ，然后再继续下一步。

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果重新定位 ... | 那么 ... 


| 所有聚合均已成功 | 转至 <<man_relocate_1_2_step4,第 4 步>>。 


| 任何聚合出现故障或被否决  a| 
.. 检查 EMS 日志以了解更正操作。
.. 执行更正操作。
.. 重新定位任何出现故障或被否决的聚合： `storage aggregate relocation start -node <node1> - destination <node2> -aggregate-list * -no-controller-upgrade true`
.. 出现提示时，输入 `y` 。
.. 返回到管理员级别： `set -privilege admin` 如有必要，您可以使用以下方法之一强制执行重新定位：
+
*** 覆盖否决检查： `s存储聚合重新定位 start -override-vetoes true -no-controller-upgrade`
*** 覆盖目标检查： `s存储聚合重新定位 start -override-destination-checks true -no-controller-upgrade`




请参见 link:other_references.html["参考资料"] 要链接到 _Disks 和聚合高级指南 _ 和 _Storage ONTAP 9 命令：手册页参考 _ ，请了解有关存储聚合重新定位命令的详细信息。

|===
. [[man_relocate_1_2_step4]] 验证所有非根聚合是否均已联机及其在节点 2 上的状态：
+
`storage aggregate show -node <node2> -state online -root false`

+
以下示例显示 node2 上的非根聚合处于联机状态：

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
aggr_1
           744.9GB 744.8GB      0% online       5 node2            raid_dp,
                                                                   normal
aggr_2     825.0GB 825.0GB      0% online       1 node2            raid_dp,
                                                                   normal
2 entries were displayed.
----
+
如果 node2 上的聚合脱机或变为外部聚合，请在 node2 上使用以下命令将其联机，每个聚合一次：

+
`storage aggregate online -aggregate <aggr_name>`

. 在 node2 上输入以下命令并检查其输出，以验证 node2 上的所有卷是否联机：
+
`volume show -node <node2> -state offline`

+
如果 node2 上的任何卷脱机，请在 node2 上使用以下命令将其联机，每个卷一次：

+
`volume online -vserver <vserver-name> -volume <volume-name>`

+
可在上一个 `volume show` 命令的输出中找到与此命令结合使用的 `vserver-name` 。

. 在 node2 上输入以下命令：
+
`storage failover show -node <node2>`

+
输出应显示以下消息：

+
[listing]
----
Node owns partner's aggregates as part of the nondisruptive controller upgrade procedure.
----
. 验证 node1 不拥有任何联机的非根聚合：
+
`storage aggregate show -owner-name <node1> -ha-policy sfo -state online`

+
输出不应显示任何已重新定位到 node2 的联机非根聚合。


