= 


如果要升级具有内部磁盘驱动器的控制器，则需要完成多个命令并检查其输出，以确保任何内部磁盘驱动器都不包含根聚合或数据聚合。

如果您不升级内部磁盘驱动器上具有聚合的控制器，请跳过本节并转到一节 link:prepare_nodes_for_upgrade.html["准备要升级的节点"]。

.步骤
. 输入 nodeshell ，每个原始节点输入一次。
+
`ssystem node run -node <node_name>`

. 显示内部驱动器：
+
`ssysconfig -av`

+
系统将显示有关节点配置的详细信息，包括存储，如以下示例所示的部分输出所示：

+
....

node> sysconfig -av
slot 0: SAS Host Adapter 0a (PMC-Sierra PM8001 rev. C, SAS, UP)
                Firmware rev: 01.11.06.00
                 Base WWN: 5:00a098:0008a3b:b0
                 Phy State: [0] Enabled, 6.0 Gb/s
                            [1] Enabled, 6.0 Gb/s
                            [2] Enabled, 6.0 Gb/s
                            [3] Enabled, 6.0 Gb/s
                ID Vendor Model FW Size
                00.0 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.1 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.2 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.3 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.4 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.5 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.6 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.7 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.8 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.9 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.10: NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.11: NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
...
....
. 检查 `ssysconfig -av` 命令的存储输出以确定内部磁盘驱动器，然后记录相关信息。
+
内部驱动器的 ID 开头为 "00" 。"00" 表示内部磁盘架，小数点后的数字表示各个磁盘驱动器。

. 【 man_aggr_step4]] 在两个控制器上输入以下命令：
+
`aggr status -r`

+
系统将显示节点的聚合状态，如以下示例中的部分输出所示：

+
[listing]
----
node> aggr status -r
Aggregate aggr2 (online, raid_dp, parity uninit'd!) (block checksums)
Plex /aggr2/plex0 (online, normal, active)
RAID group /aggr2/plex0/rg0 (normal, block checksums)

RAID Disk Device    HA SHELF BAY CHAN Pool Type RPM  Used (MB/blks)     Phys (MB/blks)
--------- --------- -- ----- --- ---- ---- ---- ---- ------------------ ------------------
dparity   0a.00.1   0a   0    1  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
parity    0a.00.3   0a   0    3  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
data      0a.00.9   0a   0    9  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
...
----
+

NOTE: 用于创建聚合的设备可能不是物理磁盘，而是分区。

. 检查 `aggr status -r` 命令的输出，以使用内部磁盘驱动器确定聚合，然后记录相关信息。
+
在上一步的示例中， "aggr2" 使用内部驱动器，如磁盘架 ID "0" 所示。

. 在两个控制器上输入以下命令：
+
`aggr status -y`

+
系统将显示聚合上卷的相关信息，如以下示例中的部分输出所示：

+
....
node> aggr status -v
...
 aggr2   online   raid_dp, aggr    nosnap=off, raidtype=raid_dp, raidsize=14,
                  64-bit           raid_lost_write=on, ignore_inconsistent=off,
                  rlw_on           snapmirrored=off, resyncsnaptime=60,
                                   fs_size_fixed=off, lost_write_protect=on,
                                   ha_policy=cfo, hybrid_enabled=off, percent_snapshot_space=0%,
                                   free_space_realloc=off, raid_cv=on, thorough_scrub=off
         Volumes: vol6, vol5, vol14
...
 aggr0   online   raid_dp, aggr    root, diskroot, nosnap=off, raidtype=raid_dp,
                  64-bit           raidsize=14, raid_lost_write=on, ignore_inconsistent=off,
                  rlw_on           snapmirrored=off,  resyncsnaptime=60, fs_size_fixed=off,
                                   lost_write_protect=on, ha_policy=cfo, hybrid_enabled=off,
                                   percent_snapshot_space=0%, free_space_realloc=off, raid_cv=on
         Volumes: vol0
....
+
根据中的输出 <<man_aggr_step4,第 4 步>> 第 6 步： aggr2 使用三个内部驱动器— "0a.00.1" ， "0a.00.3" 和 "0a.00.9" ， "aggr2" 上的卷分别为 "vol6" ， "vol5" 和 "vol14" 。此外，在步骤 6 的输出中， "aggr0" 的读数在聚合信息的开头包含 "root" 一词。这表示它包含根卷。

. 检查 `aggr status -v` 命令的输出，以确定属于内部驱动器上任何聚合的卷，以及这些卷中是否有任何卷包含根卷。
. 在每个控制器上输入以下命令，以退出 nodeshell ：
+
`退出`

. 执行以下操作之一：
+
[cols="35,65"]
|===
| 如果控制器 ... | 那么 ... 


| 请勿在内部磁盘驱动器上包含任何聚合 | 继续执行此操作步骤。 


| 包含聚合，但内部磁盘驱动器上没有卷 | 继续执行此操作步骤。* 注 * ：继续操作之前，必须将聚合置于脱机状态，然后销毁内部磁盘驱动器上的聚合。请参见 link:other_references.html["参考资料"] 链接到 _Disk 和聚合高级指南 _ 以了解有关管理聚合的信息。 


| 在内部驱动器上包含非根卷 | 继续执行此操作步骤。* 注 * ：在继续操作之前，必须先将卷移动到外部磁盘架，使聚合脱机，然后销毁内部磁盘驱动器上的聚合。请参见 link:other_references.html["参考资料"] 链接到 _Disk 和聚合高级指南 _ 以了解有关移动卷的信息。 


| 包含内部驱动器上的根卷 | 请勿继续使用此操作步骤。您可以参考来升级控制器 link:other_references.html["参考资料"] 链接到 _NetApp 支持站点 _ 并使用操作步骤 _ 通过移动卷 _ 在运行集群模式 Data ONTAP 的一对节点上升级控制器硬件。 


| 在内部驱动器上包含非根卷，您不能将这些卷移动到外部存储 | 请勿继续使用此操作步骤。您可以使用操作步骤升级运行集群模式 Data ONTAP 的一对节点上的控制器硬件并移动 volumes_ 来升级控制器。请参见 link:other_references.html["参考资料"] 链接到 _NetApp 支持站点 _ ，您可以在其中访问此操作步骤。 
|===

