= 
:allow-uri-read: 


. 【 man_lif_verif_3_step6]] 通过输入以下命令将每个 NAS 数据 LIF 迁移到 node3 ，每个 LIF 一次：
+
`network interface migrate -vserver <vserver_name> -lif <LIF_name> -destination-node <node3> -destination-port <netport_ifgrp>`

. 【 man_lif_verif_3_step7]] 确保数据迁移持久：
+
`network interface modify -vserver <vserver_name> -lif <LIF_name>-home-port <netport_ifgrp> -home-node <node3>`

. 【 man_lif_verif_3_step8]] 确保 SAN LIF 位于 node3 上的正确端口上：
+
.. 输入以下命令并检查其输出：
+
`network interface show -data-protocol iscsi_FCP -home-node <node3>`

+
系统将返回类似于以下示例的输出：

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. 如果 node3 中的任何 SAN LIF 或 SAN LIF 组位于 node1 上不存在的端口上，或者需要映射到其他端口，请通过完成以下子步骤将其移动到 node3 上的相应端口：
+
... 将 LIF 状态设置为 "down" ：
+
`network interface modify -vserver <vserver_name> -lif <LIF_name> -status-admin down`

... 从端口集中删除 LIF ：
+
`portset remove -vserver <vserver_name> -portset <portset_name> -port-name <port_name>`

... 输入以下命令之一：
+
**** 移动单个 LIF ：
+
`network interface modify -vserver <vserver_name> -lif <LIF_name> -home-port <new_home_port>`

**** 将一个不存在或不正确的端口上的所有 LIF 移动到新端口：
+
`network interface modify ｛ -home-port <port_on_node1> -home-node <node1> -role data ｝ -home-port <new_home_port_on_node3 >`

**** 将 LIF 重新添加到端口集：
+
`portset add -vserver <vserver_name> -portset <portset_name> -port-name <port_name>`

+

NOTE: 您需要确保将 SAN LIF 移动到与原始端口具有相同链路速度的端口。







. 将所有 LIF 的状态修改为 "up" ，以便 LIF 可以在节点上接受和发送流量：
+
`network interface modify -home-port <port_name> -home-node <node3>-lif data -status-admin up`

. 在任一节点上输入以下命令并检查其输出，以验证 LIF 是否已移至正确的端口，以及 LIF 的状态是否为 "up" ，具体方法是在任一节点上输入以下命令并检查输出：
+
`network interface show -home-node <node3> -role data`

. [[man_lif_verif_3_step11]] 如果任何 LIF 已关闭，请通过为每个 LIF 输入以下命令将 LIF 的管理状态设置为 "up" ：
+
`network interface modify -vserver <vserver_name> -lif <LIF_name> -status-admin up`

. 向 NetApp 发送 node1 的升级后 AutoSupport 消息：
+
`ssystem node AutoSupport invoke -node <node3> -type all -message "node1 successfully uped" from <platform_old> to <platform_new>"`


