= 


要确保设置正确，必须启用 HA 对。此外，还必须验证 node3 和 node4 是否可以访问彼此的存储，并且它们都不拥有属于集群上其他节点的数据 LIF 。此外，您必须确保 node3 拥有 node1 的聚合， node4 拥有 node2 的聚合，并且两个节点的卷均联机。

.步骤
. 在其中一个节点上输入以下命令，以启用存储故障转移：
+
`storage failover modify -enabled true -node <node3>`

. 验证是否已启用存储故障转移：
+
`s存储故障转移显示`

+
以下示例显示了启用存储故障转移时命令的输出：

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. 执行以下操作之一：
+
|===
| 如果集群为 ... | Description 


| 双节点集群 | 在任一节点上输入以下命令以启用集群高可用性： `cluster ha modify -configured true` 


| 包含两个以上节点的集群 | 转至 <<man_ensure_setup_Step4,第 4 步>>。 
|===
. 【 man_ense_setup_Step4]] 输入以下命令并检查输出，以验证 node3 和 node4 是否属于同一集群：
+
`cluster show`

. 输入以下命令并检查输出，以验证 node3 和 node4 是否可以访问彼此的存储：
+
`storage failover show -fields local-missing-disks ， partner-missing-disks`

. 输入以下命令并检查输出，以验证 node3 和 node4 均不拥有集群中其他节点拥有的主数据 LIF ：
+
`network interface show`

+
如果 node3 或 node4 拥有集群中其他节点所拥有的主数据 LIF ，请使用 `network interface revert` 命令将数据 LIF 还原到其主所有者。

. 确认 node3 拥有 node1 中的聚合，而 node4 拥有 node2 中的聚合：
+
`storage aggregate show -owner-name <node3>` `storage aggregate show -owner-name <node4>`

. 确定是否有任何卷脱机：
+
`volume show -node <node3> -state offline` `volume show -node <node4> -state offline`

. 如果任何卷处于脱机状态，请将其与您在中捕获的脱机卷列表进行比较 link:prepare_nodes_for_upgrade.html#step19d["第 19 步（ d ）"] 在 _Prepare the nodes for upgrade" 中，根据需要输入以下命令使任何脱机卷联机，每个卷一次：
+
`volume online -vserver <vserver-name> -volume <volume_name>`

. 通过为每个节点输入以下命令，为新节点安装新许可证：
+
`ssystem license add -license-code < 许可证代码，许可证代码，许可证代码 ...>`

+
license-code 参数接受一个包含 28 个大写字母字符密钥的列表。您可以一次添加一个许可证，也可以一次添加多个许可证，每个许可证密钥用逗号分隔。

. 如果在配置中使用了 NetApp 存储加密（ NSE ），并且您将 `setenv bootarg.storageencryption.support` 命令设置为 "true" ，并将 `kmip.init.maxwait` 变量 "off" （在中 link:install_boot_node3.html#step16["第 16 步"] 对于 _Install and boot node3_ ），您需要重置变量： `set diag ； systemshell -node <node-name> -command sudo kenv -u -p kmip.init.maxwait`
. 要从原始节点中删除所有旧许可证，请输入以下命令之一：
+
`ssystem license clean-up -unused -expired` `ssystem license delete -serial number <node_serial number> -package <licensable_package>`

+
** 要删除所有已过期的许可证，请输入：
+
`ssystem license clean-up -expired`

** 要删除所有未使用的许可证，请输入：
+
`ssystem license clean-up -unused`

** 要从集群中删除特定许可证，请在节点上输入以下命令：
+
`ssystem license delete -serial number <node1-serial number> -package *` `ssystem license delete -serial -number <node2-serial number> -package *`

+
此时将显示以下输出：

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
输入 `y` 删除所有软件包。



. 输入以下命令并检查其输出，以验证是否已正确安装许可证：
+
`s系统许可证显示`

+
您可能需要将输出与中捕获的输出进行比较 link:prepare_nodes_for_upgrade.html#step30["第 30 步"] 的 _ 准备节点以进行升级 _ 。

. 通过在两个节点上执行以下命令来配置 SP ：
+
`ssystem service-processor network modify -node <node-name>`

+
转至 link:other_references.html["参考资料"] 链接到系统管理参考 _ 以了解 SP 的相关信息，以及 _System 9 ONTAP 命令：手册页参考 _ 以了解有关 `ssystem service-processor network modify` 命令的详细信息。

. 对其中一个新节点执行以下操作：
+
.. 输入以下命令，输入高级权限级别：
+
`set -privilege advanced`

.. 输入以下命令：
+
`storage failover modify -node <node-name> -cifs-no-duration default-medium_low`

+
*** 如果系统的工作负载的 50% 到 75% 的操作小于 4 KB ，请输入 `medium` 。
*** 如果系统的工作负载的 75% 到 100% 的操作小于 4 KB ，请输入 `low` 。


.. 输入以下命令，返回到管理员级别：
+
`set -privilege admin`

.. 重新启动系统以确保更改生效。


. 如果要在新节点上设置无交换机集群，请转至 link:other_references.html["参考资料"] 要链接到 _Network 支持站点 _ 并按照 _switchover to a two-node switchless cluster_ 中的说明进行操作。


如果在 node3 和 node4 上启用了存储加密，请完成中的步骤 link:set_up_storage_encryption_new_controller.html["在新控制器模块上设置存储加密"]。否则，请完成中的步骤 。
