= 


要关闭受损节点，您必须确定此节点的状态，并在必要时切换此节点，以便运行正常的节点继续从受损节点存储提供数据。

.关于此任务
* 如果您使用的是 NetApp 存储加密，则必须按照的 " 将 SED 恢复到未受保护的模式 " 一节中的说明重置 MSID https://docs.netapp.com/us-en/ontap/system-admin/index.html["CLI 管理概述"]。
* 您必须在此操作步骤末尾保持电源处于打开状态，以便为运行正常的节点供电。


.步骤
. 检查 MetroCluster 状态以确定受损节点是否已自动切换到运行正常的节点： `MetroCluster show`
. 根据是否发生了自动切换，按照下表继续操作：
+
[cols="1,2"]
|===
| 如果受损节点 ... | 那么 ... 


 a| 
已自动切换
 a| 
继续执行下一步。



 a| 
未自动切换
 a| 
从运行正常的节点执行计划内切换操作： `MetroCluster switchover`



 a| 
未自动切换，您尝试使用 `MetroCluster switchover` 命令进行切换，并且切换已被否决
 a| 
查看否决消息，如果可能，请解决问题描述并重试。如果无法解决问题描述问题，请联系技术支持。

|===
. 在运行正常的集群中运行 `MetroCluster heal -phase aggregates` 命令，以重新同步数据聚合。
+
[listing]
----
controller_A_1::> metrocluster heal -phase aggregates
[Job 130] Job succeeded: Heal Aggregates is successful.
----
+
如果修复被否决，您可以使用 ` override-vetoes` 参数重新发出 `MetroCluster heal` 命令。如果使用此可选参数，则系统将覆盖任何阻止修复操作的软否决。

. 使用 MetroCluster operation show 命令验证操作是否已完成。
+
[listing]
----
controller_A_1::> metrocluster operation show
    Operation: heal-aggregates
      State: successful
Start Time: 7/25/2016 18:45:55
   End Time: 7/25/2016 18:45:56
     Errors: -
----
. 使用 `storage aggregate show` 命令检查聚合的状态。
+
[listing]
----
controller_A_1::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes            RAID Status
--------- -------- --------- ----- ------- ------ ---------------- ------------
...
aggr_b2    227.1GB   227.1GB    0% online       0 mcc1-a2          raid_dp, mirrored, normal...
----
. 使用 `MetroCluster heal -phase root-aggregates` 命令修复根聚合。
+
[listing]
----
mcc1A::> metrocluster heal -phase root-aggregates
[Job 137] Job succeeded: Heal Root Aggregates is successful
----
+
如果修复被否决，您可以使用 -override-vetoes 参数重新发出 `MetroCluster heal` 命令。如果使用此可选参数，则系统将覆盖任何阻止修复操作的软否决。

. 在目标集群上使用 `MetroCluster operation show` 命令验证修复操作是否已完成：
+
[listing]
----

mcc1A::> metrocluster operation show
  Operation: heal-root-aggregates
      State: successful
 Start Time: 7/29/2016 20:54:41
   End Time: 7/29/2016 20:54:42
     Errors: -
----
. 在受损控制器模块上，断开电源。

