= 
:allow-uri-read: 


将更换的 I/O 模块联机，验证 I/O 模块端口已成功初始化，验证插槽已通电，然后验证 I/O 模块是否联机并被识别。

.关于此任务
更换 I/O 模块并将端口恢复到正常状态后，LIF 将恢复到更换的 I/O 模块。

.步骤
. 使更换 I/O 模块联机：
+
.. 输入以下命令：
+
`system controller slot module insert -node _impaired_node_name_ -slot _slot_number_`

.. 进入 `y`当您看到提示“您想继续吗？”
+
输出应确认 I/O 模块已成功联机（开机、初始化并投入使用）。

+
例如，以下命令使节点 2（受损控制器）上的插槽 7 联机，并显示该过程已成功完成的消息：

+
[listing]
----
node2::> system controller slot module insert -node node2 -slot 7

Warning: IO_2X_100GBE_NVDA_NIC module in slot 7 of node node2 will be powered on and initialized.

Do you want to continue? {y|n}: `y`

The module has been successfully powered on, initialized and placed into service.
----


. 验证 I/O 模块上的每个端口是否已成功初始化：
+
.. 从受损控制器的控制台输入以下命令：
+
`event log show -event \*hotplug.init*`

+

NOTE: 任何所需的固件更新和端口初始化可能需要几分钟时间。

+
输出应显示一个或多个 hotplug.init.success EMS 事件和 `_hotplug.init.success:_`在 `_Event_`列中，指示 I/O 模块上的每个端口已成功初始化。

+
例如，以下输出显示 I/O 端口 e7b 和 e7a 的初始化成功：

+
[listing]
----
node2::> event log show -event *hotplug.init*

Time                Node             Severity      Event

------------------- ---------------- ------------- ---------------------------

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e7b" in slot 7 succeeded

7/11/2025 16:04:06  node2      NOTICE        hotplug.init.success: Initialization of ports "e7a" in slot 7 succeeded

2 entries were displayed.
----
.. 如果端口初始化失败，请查看 EMS 日志以了解要采取的后续步骤。


. 验证 I/O 模块插槽已通电并准备就绪：
+
`system controller slot module show`

+
输出应显示插槽状态为  `_powered-on_`，因此 I/O 模块可以运行。

. 确认 I/O 模块已联机并可识别。
+
从受损控制器的控制台输入命令：

+
`system controller config show -node local -slot _slot_number_`

+
如果 I/O 模块已成功联机并被识别，则输出将显示 I/O 模块信息，包括插槽的端口信息。

+
例如，对于插槽 7 中的 I/O 模块，您应该看到类似于以下内容的输出：

+
[listing]
----
node2::> system controller config show -node local -slot 7

Node: node2
Sub- Device/
Slot slot Information
---- ---- -----------------------------
   7    - Dual 40G/100G Ethernet Controller CX6-DX
                  e7a MAC Address: d0:39:ea:59:69:74 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2807GJFM-B
                  e7b MAC Address: d0:39:ea:59:69:75 (auto-100g_cr4-fd-up)
                          QSFP Vendor:        CISCO-BIZLINK
                          QSFP Part Number:   L45593-D218-D10
                          QSFP Serial Number: LCC2809G26F-A
                  Device Type:        CX6-DX PSID(NAP0000000027)
                  Firmware Version:   22.44.1700
                  Part Number:        111-05341
                  Hardware Revision:  20
                  Serial Number:      032403001370
----

