---
permalink: c190/chassis-replace-complete-rma.html 
sidebar: sidebar 
keywords: aff c190, verify and set HA state, run diagnostics 
summary: 您必须验证机箱的 HA 状态并运行系统级诊断。 
---
= 还原并验证配置— AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须验证机箱的 HA 状态并运行系统级诊断。



== 第 1 步：验证并设置机箱的 HA 状态

您必须验证机箱的 HA 状态，并在必要时更新此状态以匹配您的系统配置。

. 在维护模式下，从任一控制器模块显示本地控制器模块和机箱的 HA 状态：
+
` * ha-config show*`

+
所有组件的 HA 状态都应相同。

. 如果为机箱显示的系统状态与您的系统配置不匹配：
+
.. 设置机箱的 HA 状态：
+
` * ha-config modify chassis _ha-state_*`

+
` ha-state_` 的值可以是以下值之一：

+
*** `ha`
*** `non-ha`


.. 确认设置已更改：
+
` * ha-config show*`



. 如果尚未执行此操作，请重新对系统的其余部分进行布线。
. 下一步取决于您的系统配置。
+
[cols="1,2"]
|===
| 如果您的系统位于 ... | 那么 ... 


 a| 
一种独立配置
 a| 
.. 退出维护模式：
+
` * 暂停 *`

.. 转至 link:chassis-replace-move-hardware.html["正在完成更换过程"]。




 a| 
与另一个控制器模块的 HA 对
 a| 
退出维护模式： ` * halt*`

此时将显示 LOADER 提示符。

|===




== 第 2 步：运行系统级诊断

安装新机箱后，应运行互连诊断。

您的系统必须处于 LOADER 提示符处，才能启动系统级诊断。

诊断过程中的所有命令都是从要更换组件的控制器发出的。

. 如果要维护的控制器不在 LOADER 提示符处，请执行以下步骤：
+
.. 从显示的菜单中选择维护模式选项。
.. 控制器启动到维护模式后，暂停控制器：
+
` * 暂停 *`

+
问题描述命令后，您应等待系统停留在 LOADER 提示符处。

+

NOTE: 在启动过程中，您可以安全地响应 `y` 提示：



. 如果采用 HA 配置，请在第二个控制器上重复上述步骤。
+

NOTE: 两个控制器必须处于维护模式才能运行互连测试。

. 在 LOADER 提示符处，访问专为系统级诊断而设计的专用驱动程序，以便正常运行：
+
` * boot_diags*`

+
在启动过程中，您可以安全地对提示 `y` 做出响应，直到显示维护模式提示符（ * > ）为止。

. 从维护模式提示符处启用互连诊断测试：
+
` * sldiag device modify -dev interconnect -SEL enable*`

+
默认情况下，互连测试处于禁用状态，必须启用才能单独运行。

. 从维护模式提示符处运行互连诊断测试：
+
` * sldiag 设备运行 -dev interconnect *`

+
您只需要从一个控制器运行互连测试。

. 验证更换机箱是否未导致硬件问题：
+
` * sldiag device status -dev interconnect -long -state failed*`

+
如果没有测试失败，则系统级诊断会返回到提示符，或者会列出因测试组件而导致的失败的完整状态。

. 根据上一步的结果继续操作。
+
[cols="1,2"]
|===
| 如果系统级诊断测试 ... | 那么 ... 


 a| 
已完成，无任何故障
 a| 
.. 清除状态日志：
+
` * sldiag device clearstatus*`

.. 验证是否已清除日志：
+
` * sldiag device status*`

+
此时将显示以下默认响应：

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 在两个控制器上退出维护模式：
+
` * 暂停 *`

+
系统将显示 LOADER 提示符。

+

NOTE: 您必须在两个控制器上退出维护模式，然后再继续执行任何操作。

.. 在 LOADER 提示符处对两个控制器输入以下命令：
+
` * 再见 *`

.. 使控制器恢复正常运行：


|===
+
[cols="1,2"]
|===
| 如果您的系统运行的是 ONTAP | 那么 ... 


 a| 
集群中有两个节点
 a| 
问题描述以下命令：

` * 节点：： > cluster ha modify -configured true*`

` * 节点：： > storage failover modify -node node0 -enabled true*`



 a| 
集群中的节点数超过两个
 a| 
问题描述此命令：

` * 节点：： > storage failover modify -node node0 -enabled true*`



 a| 
在独立配置中
 a| 
您在这项特定任务中没有其他步骤。您已完成系统级诊断。



 a| 
导致某些测试失败
 a| 
确定问题的发生原因。

.. 退出维护模式：
+
` * 暂停 *`

.. 执行完全关闭，然后断开电源。
.. 验证您是否已遵循在运行系统级诊断时确定的所有注意事项，缆线是否已牢固连接以及硬件组件是否已正确安装在存储系统中。
.. 重新连接电源，然后打开存储系统的电源。
.. 重新运行系统级诊断测试。


|===




== 第 3 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。请参见 https://mysupport.netapp.com/site/info/rma["部件退回和放大器；更换"] 第页，了解更多信息。
