---
permalink: fas-70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas70, fas90, verify and set HA state, complete the replacement process 
summary: 重新启动控制器，验证系统健康状况，并将故障部件返回给NetApp ，以完成 FAS70 和 FAS90 机箱更换程序的最后一步。 
---
= 完成机箱更换 - FAS70 和 FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
重新启动控制器，验证系统健康状况，并将故障部件返回给NetApp ，以完成 FAS70 和 FAS90 机箱更换程序的最后一步。



== 第1步：启动控制器并交还控制器

控制器重新启动后、启动ONTAP并交还控制器。

.步骤
. Check the console output:
+
.. 如果控制器启动至Loader提示符、请使用命令重新启动控制器 `boot_ontap`。
.. 如果重新启动后控制台显示 `waiting for giveback`、请登录到配对控制器、然后使用命令检查更换后的控制器是否已准备好进行恢复 `storage failover show`。


. 执行回给：
+
.. 将控制台缆线连接到配对控制器。
.. 通过交还存储使受损控制器恢复正常运行： `storage failover giveback -ofnode _impaired_node_name_`
.. 如果自动交还功能已禁用，请重新启用它： `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`
.. 如果启用了AutoSupport、则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`






== 第2步：验证存储系统运行状况

控制器交还存储后，您应使用检查整体运行状况 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。

.步骤
. 完成恢复后、运行Active IQ Config Advisor以验证存储系统的运行状况。
. 更正您遇到的任何问题。




== 第 3 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。 https://mysupport.netapp.com/site/info/rma["部件退回和更换"]有关详细信息、请参见页面。
