---
permalink: fas-70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas70, fas90, how to recable the system, how to reassign disks 
summary: 重新启动系统。 
---
= 交还控制器—FAS70和FAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
验证存储和网络连接、然后交还控制器。



== 交还控制器

如果已启用、请重置加密并使控制器恢复正常运行。

[role="tabbed-block"]
====
.无加密
--
. 在Loader提示符处，输入 `boot_ontap`。
. 当控制台消息停止时、按<enter>。
+
** 如果看到_login"提示符、请转到本节末尾的下一步。
** 如果您看到_wawaigif for nifecback_、请按<enter>键、登录到配对节点、然后转到本节末尾的下一步。


. 通过交还存储使受损控制器恢复正常运行： `storage failover giveback -ofnode _impaired_node_name_`。
. 如果已禁用自动交还，请重新启用它： `storage failover modify -node local -auto-giveback true`。
. 如果启用了AutoSupport，则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`。


--
.板载加密(OKM)
--
. 在Loader提示符处，输入 `boot_ontap maint`。
. 使用命令检查TMP固件版本 `sysconfig -v`。
+
** 如果版本低于5.63，请联系 https://support.netapp.com["NetApp 支持"]。
** 如果版本高于5.63，请退出到Loader提示符： `halt`。


. 从Loader提示符处启动到ONTAP菜单 `boot_ontap menu`、然后选择选项10。
. 输入OKM密码短语。您可以从客户处获取此密码短语，也可以联系 https://support.netapp.com["NetApp 支持"]。
+

NOTE: 系统将提示您输入密码短语两次。

. 出现提示时、输入备份密钥数据。
. 在启动菜单中、输入选项 `1`进行正常启动。
. 当显示_wawawaite_for vig-back_时、按<enter>键。
. 将控制台缆线移至配对节点并以身份登录 `admin`。
. 确保已修复节点上的所有核心转储均已保存，方法是进入高级模式” `set -privilege advanced`，然后 `run local partner savecore`。
. 返回管理控制杆： `set privilege admin`。
. 仅交还CFO聚合(根聚合)： `storage failover giveback -fromnode local -only-cfo-aggregates true`
+
** 如果遇到错误，请联系 https://support.netapp.com["NetApp 支持"]。


. 在恢复报告完成后等待5分钟，然后检查故障转移状态和恢复状态： `storage failover show`和 `storage failover show-giveback`。
. 将控制台缆线移至替代节点并输入 `security key-manager onboard sync`
+

NOTE: 系统将提示您为此集群输入集群范围的OKM密码短语。

. 使用以下命令检查密钥的状态： `security key-manager key query -key-type svm-KEK`。
+
如果_Restored_列显示_TRUE_以外的内容，请联系 https://support.netapp.com["NetApp 支持"]。

. 通过交还存储使受损控制器恢复正常运行： `storage failover giveback -ofnode _impaired_node_name_`。
. 如果已禁用自动交还，请重新启用它： `storage failover modify -node local -auto-giveback true`。
. 如果启用了AutoSupport，则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`。


--
.外部密钥管理器(EKM)
--
. 如果根卷已使用外部密钥管理器进行加密，并且控制台电缆已连接至替代节点，请输入并选择选项 `11`。 `boot_ontap menu`
. 回答 `y`或 `n`以下问题：
+
是否有/cfcard/kmip/certs/client.crt文件的副本？｛y/n｝

+
是否有/cfcard/kmip/certs / client.key文件的副本？｛y/n｝

+
是否有/cfcard/kmip/certs文件的副本？｛y/n｝

+
或

+
是否有/cfcard/kmip/servers.cfg文件的副本？｛y/n｝

+
您是否知道KMIP服务器地址？｛y/n｝

+
您是否知道KMIP端口？｛y/n｝

+

NOTE: 如有问题、请联系 https://support.netapp.com["NetApp 支持"]。

. 提供以下信息：
+
** 客户端证书(client.crt)文件内容。
** 客户端密钥(client.key)文件内容。
** KMIP服务器CA (CA.prom)文件内容。
** KMIP服务器的IP地址。
** KMIP服务器的端口。


. 系统运行完毕后、您将看到启动菜单。选择"1"进行正常启动。
. 检查接管状态： `storage failover show`。
. 确保已修复节点上的所有核心转储均已保存，方法是进入高级模式” `set -privilege advanced`，然后 `run local partner savecore`。
. 通过交还存储使受损控制器恢复正常运行： `storage failover giveback -ofnode _impaired_node_name_`。
. 如果已禁用自动交还，请重新启用它： `storage failover modify -node local -auto-giveback true`。
. 如果启用了AutoSupport，则还原/取消禁止自动创建案例： `system node autosupport invoke -node * -type all -message MAINT=END`。


--
====