---
permalink: asa-c400/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa c400, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: '要将系统恢复到完全运行状态，您必须还原 NetApp 存储加密配置（如果需要），并为新控制器安装许可证，然后按照套件随附的 RMA 说明将故障部件退回 NetApp 。请通过联系技术支持 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"]， 888-463-8277 （北美）， 00-800-44-638277 （欧洲）或 +800-800-80-800 （亚太地区）（如果您需要 RMA 编号或有关更换操作步骤的其他帮助）。' 
---
= 完整的系统还原—ASA C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
To restore your system to full operation, you must restore the NetApp Storage Encryption configuration (if necessary), and install licenses for the new controller, and return the failed part to NetApp, as described in the RMA instructions shipped with the kit.



== 第 1 步：在 ONTAP 中为替代控制器安装许可证

如果受损节点正在使用需要标准（节点锁定）许可证的 ONTAP 功能，则必须为 _replacement_ 节点安装新许可证。对于具有标准许可证的功能，集群中的每个节点都应具有自己的功能密钥。

.关于此任务
在安装许可证密钥之前， _replacement_ 节点仍可使用需要标准许可证的功能。但是，如果受损节点是集群中唯一具有此功能许可证的节点，则不允许更改此功能的配置。此外，在节点上使用未经许可的功能可能会使您不符合您的许可协议，因此您应尽快在 _replacement_ 节点上安装替代许可证密钥。

.开始之前
许可证密钥必须采用 28 个字符的格式。

您有 90 天的宽限期来安装许可证密钥。宽限期过后，所有旧许可证将失效。安装有效的许可证密钥后，您可以在 24 小时内安装所有密钥，直到宽限期结束。

.步骤
. 如果需要新的许可证密钥，请在上获取替代许可证密钥 https://mysupport.netapp.com/site/global/dashboard["NetApp 支持站点"] 在软件许可证下的我的支持部分中。
+

NOTE: 系统会自动生成所需的新许可证密钥，并将其发送到文件中的电子邮件地址。如果您未能在 30 天内收到包含许可证密钥的电子邮件，应联系技术支持。

. 安装每个许可证密钥： ` + system license add -license-code license-key ， license-key...+`
. 如果需要，删除旧许可证：
+
.. 检查未使用的许可证： `license clean-up -unused -simulate`
.. 如果列表显示正确，请删除未使用的许可证： `license clean-up -unused`






== 第2步：验证LIF并注册序列号

在将 _replacement_ 节点恢复使用之前，您应验证 LIF 是否位于其主端口上，如果启用了 AutoSupport ，则注册 _replacement_ 节点的序列号，并重置自动交还。

.步骤
. 验证逻辑接口是否正在向其主服务器和端口报告： `network interface show -is-home false`
+
如果任何LUN列为false、请将其还原到其主端口： `network interface revert -vserver * -lif *`

. 向 NetApp 支持部门注册系统序列号。
+
** 如果启用了 AutoSupport ，请发送 AutoSupport 消息以注册序列号。
** 如果未启用 AutoSupport ，请调用 https://mysupport.netapp.com["NetApp 支持"] 注册序列号。


. 如果已触发AutoSupport维护窗口、请使用结束此窗口 `system node autosupport invoke -node * -type all -message MAINT=END` 命令：
. 如果已禁用自动交还，请重新启用它： `storage failover modify -node local -auto-giveback true`




== 第 3 步：切回双节点 MetroCluster 配置中的聚合

在双节点 MetroCluster 配置中完成 FRU 更换后，您可以执行 MetroCluster 切回操作。这样会将配置恢复到其正常运行状态，以前受损站点上的 sync-source Storage Virtual Machine （ SVM ）现在处于活动状态，并从本地磁盘池提供数据。

此任务仅限适用场景双节点 MetroCluster 配置。

.步骤
. 验证所有节点是否处于 `enabled` 状态： `MetroCluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 验证所有 SVM 上的重新同步是否已完成： `MetroCluster SVM show`
. 验证修复操作正在执行的任何自动 LIF 迁移是否已成功完成： `MetroCluster check lif show`
. 在运行正常的集群中的任何节点上使用 `MetroCluster switchback` 命令执行切回。
. 验证切回操作是否已完成： `MetroCluster show`
+
当集群处于 `waiting for-switchback` 状态时，切回操作仍在运行：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
当集群处于 `normal` 状态时，切回操作完成。：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切回需要很长时间才能完成，您可以使用 `MetroCluster config-replication resync-status show` 命令检查正在进行的基线的状态。

. 重新建立任何 SnapMirror 或 SnapVault 配置。




== 第 4 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。请参见 https://mysupport.netapp.com/site/info/rma["部件退回和放大器；更换"] 第页，了解更多信息。
