---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 了解是否可以使用 ARL 升级一对运行 ONTAP 9.8 的控制器。 
---
= 使用 ARL 升级控制器的准则
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
要了解是否可以使用 ARL 升级一对运行 ONTAP 9.8 的控制器，取决于原始控制器和替代控制器的平台和配置。



==== 支持 ARL 升级

在使用适用于 ONTAP 9.8 的 ARL 操作步骤升级一对节点时，您必须验证是否可以对原始控制器和替代控制器执行 ARL 。

您应检查所有已定义聚合的大小以及原始系统支持的磁盘数。然后，您必须将支持的聚合大小和磁盘数量与新系统支持的聚合大小和磁盘数量进行比较。此信息可在中找到 link:https://hwu.netapp.com["Hardware Universe"]。新系统支持的聚合大小和磁盘数必须等于或大于原始系统支持的聚合大小和磁盘数。

您应在集群混用规则中验证在更换原始控制器后，新节点是否可以成为现有节点集群的一部分。有关集群混合规则的详细信息，请参见 link:https://hwu.netapp.com["Hardware Universe"]。


NOTE: 如果要升级的系统支持内部驱动器（例如 FAS2700 或 AFF A250 ），但没有内部驱动器，请使用 _using aggregate relocation to manually Upgrade Controller Hardware_ 中的操作步骤。

配置了 SnapLock 企业版和 SnapLock 合规性卷的系统支持使用 ARL 升级控制器。



==== 双节点无交换机集群

如果要升级双节点无交换机集群中的节点，则可以在执行升级时将这些节点保留在无交换机集群中。您无需将其转换为交换集群。



==== ARL 不支持升级

您不能执行以下升级：

* 更换不支持与原始控制器相连的磁盘架的控制器
+
请参见 link:https://hwu.netapp.com["Hardware Universe"] 磁盘支持信息。

* 具有内部驱动器的入门级控制器，例如： FAS 2500 。
+
如果要使用内部驱动器升级入门级控制器，请参见中的操作步骤 _Upgrading a pair of nodes running 集群模式 Data ONTAP by moving volumes_ link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html["《控制器硬件升级快速指南》"]。





==== 故障排除

如果在升级控制器时出现任何问题，请参见 link:troubleshooting_overview.html["故障排除"] 部分，请参见操作步骤末尾的详细信息和可能的解决方案。

如果您未找到与遇到的问题相关的解决方案，则应联系技术支持。
