---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/preparing_for_netboot.html 
keywords: preparing, netboot, ndac, ontap 
summary: 在操作步骤中物理装入 node3 和 node4 后，您可能需要通过网络启动它们。 
---
= 准备网络启动
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在操作步骤中物理装入 node3 和 node4 后，您可能需要通过网络启动它们。术语 `netboot` 表示您从远程服务器上存储的 ONTAP 映像启动。在准备网络启动时，您必须将 ONTAP 9 启动映像的副本放在系统可以访问的 Web 服务器上。

.开始之前
* 确认您可以使用系统访问 HTTP 服务器。
* 您需要从 NetApp 支持站点下载适用于您的平台和正确版本的 ONTAP 所需的系统文件 link:https://mysupport.netapp.com["mysupport.netapp.com"]。


如果新控制器上安装的 ONTAP 9 版本与原始控制器上安装的版本不同，则必须通过网络启动这些控制器。安装每个新控制器后，您可以从 Web 服务器上存储的 ONTAP 9 映像启动系统。然后，您可以将正确的文件下载到启动介质设备，以供后续系统启动。

.步骤
. 【 man_netboot_Step1]] 访问 NetApp 支持站点以下载用于执行系统网络启动的文件。
. 从 NetApp 支持站点的软件下载部分下载相应的 ONTAP 软件，并将 ` <ontap_version>_image.tgz` 文件存储在可通过 Web 访问的目录中。
. 切换到可通过 Web 访问的目录，并验证所需文件是否可用。


[cols="30,70"]
|===
| 针对 ... | 那么 ... 


| FAS/AFF8000 系列系统 | 使用以下命令将 ` <ontap_version>_image.tgz` 文件的内容解压缩到目标目录： `tar -zxvf <ontap_version>_image.tgz` * 注意 * ：如果要在 Windows 上提取内容，请使用 7-Zip 或 WinRAR 提取网络启动映像。您的目录列表应包含一个包含内核文件的 netboot 文件夹： `netboot/kernel` 


| 所有其他系统 | 您的目录列表应包含以下文件： ` <ontap_version>_image.tgz` * 注释 * ：您不需要提取 ` <ontap_version>_image.tgz` 文件的内容。 
|===
您将使用中目录中的信息 link:stage_3_installing_and_booting_node3_overview.html["第 3 阶段"]。
