---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: 在 ONTAP 命令行中输入以下命令，开始控制器更换过程。 
---
= 准备要升级的节点
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 <stdin> 中未解析的指令 - 包括： .//_include/ru_auto_prepare_nodes_upgrade_top_step>

. 【第 4 步】按照系统控制台上控制器更换操作步骤的指示运行以下一组命令。
+
您必须分别运行和保存以下命令的输出：

+
** vserver services name-service dns show
** network interface show -curr-node <nodename> -role <cluster ， intercluster ， node-mgmt ， cluster-mgmt ， data>
** network port show -node <node_name> -type physical
** service-processor show -node * -instance
** network fcp adapter show -node <node_name>
** network port ifgrp show
** system node show -instance -node <node_name>
** 运行 -node <node_name> sysconfig
** storage aggregate show -node <node_name>
** volume show -node <node_name>
** storage array config show -switch <switch_name>
** system license show -owner <node_name>
** storage encryption disk show
** security key-manager backup show
** security key-manager external show
** security key-manager external show-status
** 可访问性 show -detail





NOTE: 如果使用板载密钥管理器（ OKM ）进行 NetApp 卷加密，请准备好密钥管理器密码短语，以便稍后在操作步骤中完成密钥管理器重新同步。

在 <stdin> 中未解析的指令 - 包括： ../_include/ru_auto_correct_aggregate_ownery.adoc]]

在 <stdin> 中未解析的指令 - 包括： ../_include/Rm_auto_license.adoc]]
