---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/reboots_panics_or_power_cycles.html 
keywords: reboots, panics, power, cycles, node, crash 
summary: 系统可能发生崩溃—重新启动，崩溃或重新启动。 
---
= 重新启动，崩溃或重新启动
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在升级的不同阶段，系统可能会崩溃—重新启动，崩溃或重新启动。

这些问题的解决方案取决于它们发生的时间。



== 在预检查阶段重新启动，崩溃或重新启动



=== 在 HA 对的预检查阶段仍处于启用状态之前，节点 1 或节点 2 崩溃

如果 node1 或 node2 在预检查阶段之前崩溃，则尚未重新定位任何聚合，并且 HA 对配置仍处于启用状态。

接管和交还可以正常进行。

.步骤
. 检查控制台是否存在系统可能已发出的 EMS 消息，并采取建议的更正操作。
. 继续执行节点对升级操作步骤。




== 在第一个资源释放阶段重新启动，崩溃或重新启动



=== 在 HA 对仍处于启用状态的情况下，节点 1 在第一个资源释放阶段崩溃

部分或所有聚合已从 node1 重新定位到 node2 ，并且 HA 对仍处于启用状态。node2 接管 node1 的根卷以及未重新定位的任何非根聚合。

重新定位的聚合的所有权与因主所有者未发生更改而被接管的非根聚合的所有权相同。

当 node1 进入 `Waiting for giveback` 状态时， node2 将交还所有 node1 非根聚合。

.步骤
. 启动 node1 后， node1 的所有非根聚合均已移回 node1 。您必须使用以下命令手动将聚合从 node1 重新定位到 node2 ： `storage aggregate relocation start -node node1 -destination node2 -aggregate-list * - ndocontroller-upgrade true`
. 继续执行节点对升级操作步骤。




=== 在禁用 HA 对的情况下， Node1 在第一个资源释放阶段崩溃

Node2 不会接管，但它仍在从所有非根聚合提供数据。

.步骤
. 启动 node1 。
. 继续执行节点对升级操作步骤。




=== 在 HA 对仍处于启用状态的情况下，节点 2 在第一个资源释放阶段失败

node1 已将其部分或全部聚合重新定位到 node2 。已启用 HA 对。

node1 接管 node2 的所有聚合以及它已重新定位到 node2 的任何自身聚合。node2 启动时，聚合重新定位将自动完成。

.步骤
. 启动 node2 。
. 继续执行节点对升级操作步骤。




=== 在第一个资源释放阶段以及禁用 HA 对之后， Node2 会崩溃

Node1 不接管。

.步骤
. 启动 node2 。
+
在 node2 启动期间，所有聚合都会发生客户端中断。

. 继续执行节点对升级操作步骤的其余部分。




== 在第一个验证阶段重新启动，崩溃或重新启动



=== 在禁用 HA 对的情况下，节点 2 在第一个验证阶段崩溃

Node2 崩溃后 Node3 不会接管，因为 HA 对已禁用。

.步骤
. 启动 node2 。
+
在 node2 启动期间，所有聚合都会发生客户端中断。

. 继续执行节点对升级操作步骤。




=== 在禁用 HA 对的情况下，节点 3 在第一个验证阶段崩溃

Node2 不会接管，但它仍在从所有非根聚合提供数据。

.步骤
. 启动 node3 。
. 继续执行节点对升级操作步骤。




== 在第一个资源重新获取阶段重新启动，崩溃或重新启动



=== 在聚合重新定位期间，节点 2 在第一个资源重新获取阶段崩溃

node2 已将其部分或全部聚合从 node1 重新定位到 node3 。node3 用于从已重新定位的聚合提供数据。HA 对已禁用，因此不存在接管。

未重新定位的聚合发生客户端中断。启动 node2 时， node1 的聚合将重新定位到 node3 。

.步骤
. 启动 node2 。
. 继续执行节点对升级操作步骤。




=== 在聚合重新定位期间，节点 3 在第一个资源重新获取阶段崩溃

如果在 node2 将聚合重新定位到 node3 时 node3 崩溃，则在 node3 启动后，此任务将继续执行。

Node2 将继续为其余聚合提供服务，但已重新定位到 Node3 的聚合会在 Node3 启动期间发生客户端中断。

.步骤
. 启动 node3 。
. 继续升级控制器。




== 在检查后阶段重新启动，崩溃或重新启动



=== 在后检查阶段，节点 2 或节点 3 崩溃

HA 对已禁用，因此不是接管。重新启动的节点中的聚合发生客户端中断。

.步骤
. 启动节点。
. 继续执行节点对升级操作步骤。




== 在第二个资源释放阶段重新启动，崩溃或重新启动



=== Node3 在第二个资源释放阶段崩溃

如果 node2 重新定位聚合时 node3 崩溃，则在 node3 启动后，此任务将继续执行。

Node2 继续为其余聚合提供服务，但已重新定位到 Node3 和 Node3 自己的聚合的聚合在 Node3 启动期间会发生客户端中断。

.步骤
. 启动 node3 。
. 继续执行控制器升级操作步骤。




=== Node2 在第二个资源释放阶段崩溃

如果节点 2 在聚合重新定位期间崩溃，则不会接管节点 2 。

node3 将继续为已重新定位的聚合提供服务，但 node2 拥有的聚合会发生客户端中断。

.步骤
. 启动 node2 。
. 继续执行控制器升级操作步骤。




== 在第二个验证阶段重新启动，崩溃或重新启动



==== Node3 在第二个验证阶段崩溃

如果节点 3 在此阶段崩溃，则不会发生接管，因为 HA 对已禁用。

在 node3 重新启动之前，所有聚合都会发生客户端中断。

.步骤
. 启动 node3 。
. 继续执行节点对升级操作步骤。




=== Node4 在第二个验证阶段崩溃

如果节点 4 在此阶段崩溃，则不会发生接管。node3 从聚合提供数据。

非根聚合发生中断，这些聚合已重新定位，直到 node4 重新启动。

.步骤
. 启动 node4 。
. 继续执行节点对升级操作步骤。

