---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/relocating_non-root_aggregates_and_nas_data_lifs_from_node2_to_node3.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node3 
summary: 在将 node2 替换为 node4 之前，必须将 node2 所拥有的非根聚合重新定位到 node3 。 
---
= 将非根聚合和 NAS 数据 LIF 从 node2 重新定位到 node3
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在将 node2 替换为 node4 之前，必须将 node2 所拥有的非根聚合重新定位到 node3 。

从上一阶段完成后检检查后， node2 的资源版本将自动启动。非根聚合和非 SAN 数据 LIF 将从 node2 迁移到 node3 。

在升级操作步骤期间，远程 LIF 处理 SAN LUN 的流量。升级期间，集群或服务运行状况无需移动 SAN LIF 。

迁移聚合和 LIF 后，此操作将暂停以进行验证。在此阶段，您必须验证是否所有非根聚合和非 SAN 数据 LIF 都已迁移到 node3 。


NOTE: 不会修改聚合和 LIF 的主所有者；只会修改当前所有者。

.步骤
. 使用以下命令验证所有非根聚合是否已联机及其在 node3 上的状态：
+
`storage aggregate show -node node3 -state online -root false`

+
以下示例显示 node2 上的非根聚合处于联机状态：

+
....
cluster::> storage aggregate show -node node3 state online -root false

Aggregate      Size         Available   Used%   State   #Vols  Nodes  RAID     Status
----------     ---------    ---------   ------  -----   -----  ------ -------  ------
aggr_1         744.9GB      744.8GB      0%     online  5      node2  raid_dp  normal
aggr_2         825.0GB      825.0GB      0%     online  1      node2  raid_dp  normal
2 entries were displayed.
....
+
如果 node3 上的聚合脱机或变为外部聚合，请在 node3 上使用以下命令将其联机，每个聚合一次：

+
`storage aggregate online -aggregate <aggr_name>`

. 在 node3 上使用以下命令并检查其输出，以验证 node3 上的所有卷是否联机：
+
`volume show -node node3 -state offline`

+
如果 node3 上的任何卷脱机，请在 node3 上使用以下命令将其联机，每个卷一次：

+
`volume online -vserver <vserver-name> -volume <volume-name>`

+
要与此命令结合使用的 ` <vserver-name>` 可在上一个 `volume show` 命令的输出中找到。

. 验证 LIF 是否已移至正确的端口且状态为 `up` 。如果任何 LIF 已关闭，请为每个 LIF 输入以下命令，将 LIF 的管理状态设置为 `up` ：
+
`network interface modify -vserver <vserver_name> - lif <LIF_name> -home-node <nodename> - status-admin up`

. 如果新硬件上不存在当前托管数据 LIF 的端口，请使用以下命令将其从广播域中删除：
+
`network port broadcast-domain remove-ports`

. 使用以下命令并检查输出，以验证 node2 上是否没有剩余数据 LIF ：
+
`network interface show - curr-node <node2>-role data`


