---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/use_aggregate_relocation_upgrade_controller_hardware_overview.html 
keywords: aggregate, relocation, upgrade, controller, hardware, ontap, non-root, arl, ha, high, availability 
summary: 您可以无中断地升级运行 ONTAP 9.8 的一对节点上的控制器硬件。 
---
= 使用聚合重新定位升级控制器硬件
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在操作步骤期间，您可以使用替代控制器硬件升级原始控制器硬件，从而重新定位非根聚合的所有权。您可以在节点之间多次迁移聚合，以确保在整个升级操作步骤中至少有一个节点从聚合提供数据。您还可以迁移数据逻辑接口（ LIF ），并在继续操作时将新控制器上的网络端口分配给接口组。


NOTE: 在本文档中，原始节点称为 _node1_ 和 _node2_ ，新节点称为 _node3_ 和 _node4_ 。在所述的操作步骤期间， node1 将替换为 node3 ， node2 将替换为 node4 。术语 _node1_ ， _node2_ ， _node3_ 和 _node4_ 仅用于区分原始节点和新节点。在操作步骤之后，必须替换原始节点和新节点的实际名称。但是，实际上，节点名称不会更改：在升级控制器硬件后， node3 的名称为 node1 ， node4 的名称为 node2 。本文档使用术语 _systems with FlexArray Virtualization Software_ 来指属于这些新平台的系统。它使用 V 系列系统一词来表示可连接到存储阵列的不同硬件系统



==== 重要

* 此操作步骤非常复杂，假定您具备高级 ONTAP 管理技能。您还应阅读并了解 link:guidelines_for_upgrading_controllers_with_arl.html["使用 ARL 升级控制器的准则"] 和  开始升级前的章节。
* 此操作步骤假定更换用的控制器硬件是新的，尚未使用。使用 `wipeconfig` 命令准备已用控制器所需的步骤不在此操作步骤中。如果先前使用的是替代控制器硬件，则必须联系技术支持，尤其是在控制器以 7- 模式运行 Data ONTAP 时。
* 您可以使用此操作步骤升级具有两个以上节点的集群中的控制器硬件；但是，您需要为集群中的每个高可用性（ HA ）对单独执行操作步骤。
* 此操作步骤适用场景 FAS 系统， V 系列系统， AFF 系统以及安装了 FlexArray 虚拟化软件的系统。如果安装了所需的许可证，则在 ONTAP 9.5 之后发布的 FAS 系统可以连接到存储阵列。ONTAP 9.5 支持现有 V 系列系统。请参见 V 系列支持表，网址为 link:https://hwu.netapp.com["Hardware Universe"] 有关存储阵列和 V 系列型号的信息。
* 此操作步骤适用场景系统运行 4 节点 NetApp MetroCluster 配置或更高版本。由于 MetroCluster 配置站点可以位于两个物理上不同的位置，因此对于 HA 对，必须在每个 MetroCluster 站点上单独执行控制器自动升级。
* 如果要从 AFF A320 系统升级，您可以使用卷移动升级控制器硬件或联系技术支持。如果您愿意执行卷移动，请参见 link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html["《控制器硬件升级快速指南》"]。

