---
permalink: fas9000/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, replace, boot, media, primary, secondary, image, disruptive, nondisruptive, manual, manual boot recovery 
summary: 启动介质存储系统启动时使用的主系统文件和辅助系统文件（启动映像）。根据您的网络配置，您可以执行非中断式或中断式更换。FAS9000系统仅支持手动启动介质恢复程序。 
---
= 启动介质更换概述—FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
启动介质存储系统启动时使用的主系统文件和辅助系统文件（启动映像）。FAS9000系统仅支持手动启动介质恢复程序。不支持自动启动介质恢复。

启动介质存储系统在启动时使用的一组主文件和二级系统文件（启动映像）。根据您的网络配置，您可以执行无中断或中断更换。

[NOTE]
====
NetApp 强烈建议您在使用的设备上启用控制台日志记录，并在执行此过程时执行以下操作：

* 在维护期间保持 AutoSupport 启用状态。这允许 NetApp 支持在发生问题时接收诊断信息。
* 为任何 CLI 会话启用会话日志记录。这将创建维护活动期间所有命令和系统输出的完整记录。有关如何启用会话日志记录的指导，请参见 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["如何配置 PuTTY 以优化与 ONTAP 系统的连接"^]。


====
You must have a USB flash drive, formatted to FAT32, with the appropriate amount of storage to hold the `image_xxx.tgz`.

您还必须将 `image_xxx.tgz` 文件复制到 USB 闪存驱动器，以供日后在此操作步骤中使用。

* 更换启动介质的无中断和中断方法都要求您还原 `var` 文件系统：
+
** 要进行无中断更换， HA 对不需要连接到网络即可还原 `var` 文件系统。一个机箱中的 HA 对具有一个内部 e0S 连接，用于在它们之间传输 `var` config 。
** 要进行中断更换，您不需要网络连接即可还原 `var` 文件系统，但此过程需要重新启动两次。


* 您必须将故障组件更换为从提供商处收到的替代 FRU 组件。
* 请务必在正确的节点上应用以下步骤中的命令：
+
** 受损节点是指要在其中执行维护的节点。
** 运行状况良好的节点 _ 是受损节点的 HA 配对节点。



