---
permalink: fas9000/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff a700, fas9000, shut, down, impaired, controller, take, over, manual, manual boot recovery 
summary: 您可以根据存储系统硬件配置的不同，使用不同的程序来关闭或接管故障控制器。FAS9000系统仅支持手动启动介质恢复程序。 
---
= 关闭受损控制器- FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用适合您配置的相应程序关闭或接管故障控制器。FAS9000系统仅支持手动启动介质恢复程序。不支持自动启动介质恢复。



== 选项 1 ：大多数系统

通过将其暂停到 LOADER 提示符并捕获引导环境变量来完成受损控制器的关闭。LOADER 提示符是安全停止状态，您可以从中更换启动介质。

.步骤
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至 "Remove controller module" 。



 a| 
`正在等待交还 ...`
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
从运行正常的控制器接管或暂停受损的控制器： `storage failover takeover -ofnode impaired_node_name`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===
. 在 LOADER 提示符处，输入 `printenv` 以捕获所有启动环境变量。将输出保存到日志文件中。
+

NOTE: 如果启动设备损坏或无法正常运行，则此命令可能不起作用。





=== 选项 2 ：控制器位于 MetroCluster 中

After completing the NVE or NSE tasks, you need to complete the shutdown of the impaired node.注意：如果您的系统采用双节点 MetroCluster 配置，请勿使用此操作步骤。

接管并停止受损的控制器，以便健康控制器继续从受损的控制器的存储中提供数据。为此，您需要在 AutoSupport 中禁止自动创建案例，禁用自动回馈，并将受损的控制器带到 LOADER 提示符处。LOADER 提示符是安全停止状态，您可以从中更换 FRU。

* If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示false、则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。
* 如果您使用的是 MetroCluster 配置，则必须确认已配置 MetroCluster 配置状态，并且节点处于已启用且正常的状态（`MetroCluster node show` ）。


.步骤
. 如果启用了AutoSupport 、则通过调用AutoSupport 消息禁止自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
这可以防止在计划的维护时段内打开自动支持案例。最大抑制持续时间为 72 小时。如果维护提前完成，您可以通过调用带有  `MAINT=END` 的 AutoSupport 消息来重新启用案例创建。有关详细信息，请参见  https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["如何在计划维护窗口期间禁止自动创建案例"^]。

+
以下AutoSupport 消息禁止自动创建案例两小时：

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
正在等待交还
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
从运行正常的控制器接管或暂停受损的控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===




== Option 3: Controller is in a two-node MetroCluster

完成 NVE 或 NSE 任务后，您需要关闭受损节点。


NOTE: 如果您的系统采用双节点 MetroCluster 配置，请勿使用此操作步骤。

接管并停止受损的控制器，以便健康控制器继续从受损的控制器的存储中提供数据。为此，您需要在 AutoSupport 中禁止自动创建案例，禁用自动回馈，并将受损的控制器带到 LOADER 提示符处。LOADER 提示符是安全停止状态，您可以从中更换 FRU。

* If you have a cluster with more than two nodes, it must be in quorum.如果集群未达到仲裁或运行状况良好的控制器在资格和运行状况方面显示false、则必须在关闭受损控制器之前更正问题描述 ；请参见 link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["将节点与集群同步"^]。
* 如果您使用的是 MetroCluster 配置，则必须确认已配置 MetroCluster 配置状态，并且节点处于已启用且正常的状态（`MetroCluster node show` ）。


.步骤
. 如果启用了AutoSupport 、则通过调用AutoSupport 消息禁止自动创建案例：
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
这可以防止在计划的维护时段内打开自动支持案例。最大抑制持续时间为 72 小时。如果维护提前完成，您可以通过调用带有  `MAINT=END` 的 AutoSupport 消息来重新启用案例创建。有关详细信息，请参见  https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU92["如何在计划维护窗口期间禁止自动创建案例"^]。

+
以下AutoSupport 消息禁止自动创建案例两小时：

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 从运行正常的控制器的控制台禁用自动交还： `storage failover modify – node local -auto-giveback false`
. 将受损控制器显示为 LOADER 提示符：
+
[cols="1,2"]
|===
| 如果受损控制器显示 ... | 那么 ... 


 a| 
LOADER 提示符
 a| 
转至下一步。



 a| 
正在等待交还
 a| 
按 Ctrl-C ，然后在出现提示时回答 `y` 。



 a| 
系统提示符或密码提示符（输入系统密码）
 a| 
从运行正常的控制器接管或暂停受损的控制器： `storage failover takeover -ofnode _impaired_node_name_`

当受损控制器显示 Waiting for giveback... 时，按 Ctrl-C ，然后回答 `y` 。

|===

