---
permalink: fas9000/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a700, fas9000, sysdiages, ha-config, switchback, chassis 
summary: 您必须验证机箱的 HA 状态，运行诊断并将故障部件退回给 NetApp ，如套件随附的 RMA 说明中所述。 
---
= 完成还原和更换过程— AFF A700 和 FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须验证机箱的 HA 状态，运行诊断并将故障部件退回给 NetApp ，如套件随附的 RMA 说明中所述。



== 第 1 步：验证并设置机箱的 HA 状态

您必须验证机箱的 HA 状态，并在必要时更新此状态以匹配您的系统配置。

.步骤
. 在维护模式下，从任一控制器模块显示本地控制器模块和机箱的 HA 状态： `ha-config show`
+
所有组件的 HA 状态都应相同。

. 如果为机箱显示的系统状态与您的系统配置不匹配：
+
.. 设置机箱的 HA 状态： `ha-config modify chassis _ha-state_`
+
`ha-state` 的值可以是以下值之一：

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mCCIP`
*** `non-ha`


.. 确认设置已更改： `ha-config show`


. 如果尚未执行此操作，请重新对系统的其余部分进行布线。
. 退出维护模式： `halt`
+
此时将显示 LOADER 提示符。





== 第 2 步：运行系统级诊断

安装新机箱后，应运行互连诊断。

您的系统必须处于 LOADER 提示符处，才能启动系统级诊断。

诊断过程中的所有命令都是从要更换组件的节点发出的。

.步骤
. 如果要服务的节点不在 LOADER 提示符处，请执行以下步骤：
+
.. 从显示的菜单中选择维护模式选项。
.. 在节点启动至维护模式后，暂停节点： `halt`
+
问题描述命令后，您应等待系统停留在 LOADER 提示符处。

+

NOTE: 在启动过程中，您可以安全地响应 `y` 提示：



. 如果采用 HA 配置，请在第二个节点上重复上述步骤。
+

NOTE: 两个控制器必须处于维护模式才能运行互连测试。

. 在 LOADER 提示符处，访问专为系统级诊断而设计的特殊驱动程序以正常运行： `boot_diags`
+
在启动过程中，您可以安全地对提示 `y` 做出响应，直到显示维护模式提示符（ * > ）为止。

. 从维护模式提示符处启用互连诊断测试： `sldiag device modify -dev interconnect -SEL enable`
+
默认情况下，互连测试处于禁用状态，必须启用才能单独运行。

. 从维护模式提示符处运行互连诊断测试： `sldiag device run -dev interconnect`
+
您只需要从一个控制器运行互连测试。

. 验证更换机箱是否未导致硬件问题： `sldiag device status -dev interconnect -long -state failed`
+
如果没有测试失败，则系统级诊断会返回到提示符，或者会列出因测试组件而导致的失败的完整状态。

. 根据上一步的结果继续操作。
+
[cols="1,2"]
|===
| 如果系统级诊断测试 ... | 那么 ... 


 a| 
已完成，无任何故障
 a| 
.. 清除状态日志： `sldiag device clearstatus`
.. 验证是否已清除日志： `sldiag device status`
+
此时将显示以下默认响应：

+
[listing]
----
SLDIAG: No log messages are present.
----
.. 在两个控制器上退出维护模式： `halt`
+
系统将显示 LOADER 提示符。

+

NOTE: 您必须在两个控制器上退出维护模式，然后再继续执行任何操作。

.. 在 LOADER 提示符处对两个控制器输入以下命令： `bye`
.. 使节点恢复正常运行：




 a| 
集群中有两个节点
 a| 
问题描述以下命令： `node ：： > cluster ha modify -configured true`

`node ：： > storage failover modify -node node0 -enabled true`



 a| 
集群中的节点数超过两个
 a| 
问题描述此命令：``node ： > storage failover modify -node node0 -enabled true``



 a| 
在双节点 MetroCluster 配置中
 a| 
继续执行下一步。

MetroCluster 切回操作步骤将在更换过程的下一任务中完成。



 a| 
在独立配置中
 a| 
您在这项特定任务中没有其他步骤。

您已完成系统级诊断。



 a| 
导致某些测试失败
 a| 
确定问题的发生原因。

.. 退出维护模式： `halt`
.. 执行完全关闭，然后断开电源。
.. 验证您是否已遵循在运行系统级诊断时确定的所有注意事项，缆线是否已牢固连接以及硬件组件是否已正确安装在存储系统中。
.. 重新连接电源，然后打开存储系统的电源。
.. 重新运行系统级诊断测试。


|===




== 第 3 步：切回双节点 MetroCluster 配置中的聚合

在双节点 MetroCluster 配置中完成 FRU 更换后，您可以执行 MetroCluster 切回操作。这样会将配置恢复到其正常运行状态，以前受损站点上的 sync-source Storage Virtual Machine （ SVM ）现在处于活动状态，并从本地磁盘池提供数据。

此任务仅限适用场景双节点 MetroCluster 配置。

.步骤
. 验证所有节点是否处于 `enabled` 状态： `MetroCluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 验证所有 SVM 上的重新同步是否已完成： `MetroCluster SVM show`
. 验证修复操作正在执行的任何自动 LIF 迁移是否已成功完成： `MetroCluster check lif show`
. 在运行正常的集群中的任何节点上使用 `MetroCluster switchback` 命令执行切回。
. 验证切回操作是否已完成： `MetroCluster show`
+
当集群处于 `waiting for-switchback` 状态时，切回操作仍在运行：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
当集群处于 `normal` 状态时，切回操作完成。：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切回需要很长时间才能完成，您可以使用 `MetroCluster config-replication resync-status show` 命令检查正在进行的基线的状态。

. 重新建立任何 SnapMirror 或 SnapVault 配置。




== 第 4 步：将故障部件退回 NetApp

按照套件随附的 RMA 说明将故障部件退回 NetApp 。请参见 https://["部件退回和放大器；更换"] 第页，了解更多信息。
