---
permalink: asa-c250/maintain-overview.html 
sidebar: sidebar 
keywords: asa C250 maintenance, maintenance, repairing C250, repairing asa C250, replace asa C250 components, replace asa C250 components 
summary: 维护ASA C250硬件 
---
= 维护ASA C250硬件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
维护 ASA C250 存储系统的硬件，以确保长期可靠性和最佳性能。执行定期维护任务，例如更换故障组件，因为这有助于防止停机和数据丢失。

维护程序假设 ASA C250 存储系统已部署为 ONTAP 环境中的存储节点。



== 系统组件

对于ASA C250存储系统、您可以对以下组件执行维护过程。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["启动媒体 - 自动恢复"]
 a| 
启动介质存储存储系统用于启动的主要和辅助 ONTAP 映像文件集。在自动恢复期间，系统会从合作伙伴节点检索启动映像，并自动运行相应的启动菜单选项，以便在替换启动介质上安装映像。自动启动介质恢复过程仅在 ONTAP 9.18.1 及更高版本中受支持。如果您的存储系统运行的是早期版本的 ONTAP，请使用link:bootmedia-replace-workflow.html["手动启动恢复程序"]。



 a| 
link:bootmedia-replace-workflow.html["启动媒体 - 手动恢复"]
 a| 
启动介质存储存储系统用于启动的主要和辅助 ONTAP 映像文件集。在手动恢复期间，您可以从 USB 驱动器启动存储系统，并手动还原文件系统映像和配置。如果您的存储系统运行的是 ONTAP 9.18.1 及更高版本，请使用 link:bootmedia-replace-workflow-bmr.html["自动启动恢复程序"]。



 a| 
link:chassis-replace-workflow.html["机箱"]
 a| 
机箱是托管所有控制器组件(例如控制器/CPU单元、电源和I/O)的物理机箱



 a| 
link:controller-replace-workflow.html["控制器"]
 a| 
控制器由主板，固件和软件组成。它控制驱动器并实现ONTAP功能。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
如果存在内存不匹配或 DIMM 发生故障，则必须更换 DIMM （双列直插式内存模块）。



 a| 
link:drive-replace.html["驱动器"]
 a| 
驱动器是为数据提供物理存储介质的设备。



 a| 
link:fan-replace.html["风扇"]
 a| 
风扇用于冷却控制器。



 a| 
link:mezzanine-replace.html["夹层卡"]
 a| 
夹层卡是一种直接插入另一个插件卡的印刷电路板。



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM 电池"]
 a| 
如果 AC 电源出现故障，NVMEM 电池负责保存缓存数据。



 a| 
link:power-supply-replace.html["电源"]
 a| 
电源可在控制器架中提供冗余电源。



 a| 
link:rtc-battery-replace.html["实时时钟电池"]
 a| 
实时时钟电池可在断电时保留系统日期和时间信息。

|===