---
permalink: ns224/change-shelf-id.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, change, shelf, id, system, ontap, unown, spare, offline, aggregate, change an ns224 drive shelf id 
summary: 当 ONTAP 尚未运行或在将磁盘架连接到系统之前热添加磁盘架时，您可以更改系统中的磁盘架 ID 。您也可以在 ONTAP 启动并运行 \ （控制器模块可用于提供数据 \ ）且磁盘架中的所有驱动器均为无所有者，备用或脱机聚合的一部分时更改磁盘架 ID 。 
---
= 更改磁盘架 ID — NS224 磁盘架
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
当 ONTAP 尚未运行或在将磁盘架连接到系统之前热添加磁盘架时，您可以更改系统中的磁盘架 ID 。您还可以在 ONTAP 启动并运行（控制器模块可用于提供数据）且磁盘架中的所有驱动器均为无主聚合，备用聚合或脱机聚合的一部分时更改磁盘架 ID 。

.开始之前
* 如果 ONTAP 已启动且正在运行（控制器模块可用于提供数据），则必须已验证磁盘架中的所有驱动器是否为无主聚合，备用聚合或脱机聚合的一部分。
+
您可以使用 `storage disk show -shelf _shelf_number_` 命令验证驱动器的状态。如果驱动器出现故障， `Container Type` 列中的输出应显示 `spare` 或 `broken` 。此外， `Container Name` 和 `owner` 列应包含一个短划线。

* 您需要一个带一端直发的回形针或一个窄尖圆头笔。
+
您可以使用回形针或笔形笔通过操作显示面板（ OperatorDisplay Panel ， ODp ）中 LED 右侧的小孔访问磁盘架 ID 按钮。



.关于此任务
* 有效磁盘架 ID 为 00 到 99 。
* HA 对中的磁盘架 ID 必须是唯一的。
* 要使磁盘架 ID 生效，您必须重新打开磁盘架电源（拔下两根电源线，等待适当的时间，然后重新插入）。
+
重新插入电源线之前等待的时间取决于 ONTAP 的状态，如本操作步骤后面所述。

+

NOTE: NS224 磁盘架的电源上没有电源开关。



.步骤
. 如果磁盘架尚未打开，请打开其电源。
+
首先将电源线连接到磁盘架，使用电源线固定器将其固定到位，然后将电源线连接到不同的电源以提高故障恢复能力。

. 拆下左端盖，找到 LED 右侧的小孔。
. 更改磁盘架 ID 的第一个数字：
+
.. 将回形针或球形笔插入小孔。
.. 按住按钮，直到数字显示屏上的第一个数字闪烁，然后释放按钮。
+
此数字可能需要长达 15 秒才能闪烁。此操作将激活磁盘架 ID 编程模式。

+

NOTE: 如果此 ID 闪烁所需时间超过 15 秒，请再次按住此按钮，确保一直按此按钮。

.. 按下并释放此按钮可将此数字向前移动，直到达到所需数字 0 到 9 为止。
+
每个印刷和发布持续时间可短至一秒。

+
第一个数字将继续闪烁。



. 更改磁盘架 ID 的第二个数字：
+
.. 按住该按钮，直到数字显示屏上的第二个数字闪烁。
+
此数字可能需要长达三秒的时间才能闪烁。

+
数字显示屏上的第一个数字停止闪烁。

.. 按下并释放此按钮可将此数字向前移动，直到达到所需数字 0 到 9 为止。
+
第二个数字将继续闪烁。



. 锁定所需的数字，然后按住该按钮，直到第二个数字停止闪烁，以退出编程模式。
+
此数字可能需要长达三秒的时间才能停止闪烁。

+
数字显示屏上的两个数字开始闪烁，耗时值上的琥珀色 LED 在大约 5 秒后亮起，提醒您待定磁盘架 ID 尚未生效。

. 重新启动磁盘架以使磁盘架 ID 生效。
+
您必须从磁盘架上的两个电源上拔下电源线，等待适当的时间，然后将其重新插入磁盘架电源以完成重新启动。

+
插入电源线后立即打开电源。其双色 LED 应呈绿色亮起。

+
** 如果 ONTAP 尚未运行或您要热添加磁盘架（尚未通过缆线连接到系统），请至少等待 10 秒钟。
** 如果 ONTAP 正在运行（控制器可用于提供数据），并且磁盘架中的所有驱动器均为无所有者，备用或脱机聚合的一部分，请至少等待 70 秒。
+
此时， ONTAP 可以正确删除旧磁盘架地址并更新新磁盘架地址的副本。



. 更换左端盖。

