---
permalink: ns224/hot-add-aff-cable-a30-50-60.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, aff a30, aff a50, aff c30, aff c60, cable 
summary: 将 NS224 磁盘架连接到 AFF A30、AFF A50、AFF C30 或 AFF C60 系统，以便每个磁盘架与 HA 对中的每个控制器有两个连接。 
---
= 将 NS224 磁盘架连接到您的 AFF A30、AFF A50、AFF C30 或 AFF C60 系统
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
将 NS224 磁盘架连接到 AFF A30、AFF A50、AFF C30 或 AFF C60 系统，以便每个磁盘架与 HA 对中的每个控制器有两个连接。

如果需要额外存储(到内部磁盘架)、您最多可以将两个NS224磁盘架热添加到AFF A30、AFF C30、AFF A50或AFF C60 HA对。

.关于此任务
* 此过程假设HA对只有内部存储(无外部磁盘架)、并且您要在每个控制器中热添加最多两个额外磁盘架和两个支持RoCE的I/O模块。
* 此过程可解决以下热添加情形：
+
** 在每个控制器中使用一个支持RoCE的I/O模块将第一个磁盘架热添加到HA对。
** 在每个控制器中使用两个支持RoCE的I/O模块将第一个磁盘架热添加到HA对。
** 热-将第二个磁盘架添加到每个控制器中具有两个支持RoCE的I/O模块的HA对中。


* 这些系统可与具有NSM100模块的NS224磁盘架和具有NSM100B模块的NS224磁盘架兼容。为确保将控制器连接到正确的端口、请将每个示意图中的"X"替换为适用于您的模块的正确端口号：
+
[cols="1,4"]
|===
| 模块类型 | 端口标记 


 a| 
NSM100
 a| 
"0"

例如e0a



 a| 
NSM100B
 a| 
"1"

例如e1a

|===


.步骤
. 如果要在每个控制器模块中使用一组支持RoCE的端口(一个支持RoCE的I/O模块)热添加一个磁盘架、并且这是HA对中唯一的NS224磁盘架、请完成以下子步骤。
+
否则，请转至下一步。

+

NOTE: 此步骤假定您已将支持RoCE的I/O模块安装在插槽3中。

+
.. 使用缆线将磁盘架NSM A端口exa连接到控制器A插槽3端口A (E3A)。
.. 使用缆线将磁盘架NSM A端口EXB连接到控制器B插槽3端口b (e3b)。
.. 使用缆线将磁盘架NSM B端口exa连接到控制器B插槽3端口A (E3A)。
.. 使用缆线将磁盘架NSM B端口EXB连接到控制器A插槽3端口b (e3b)。
+
下图显示了在每个控制器模块中使用一个支持 RoCE 的 I/O 模块为一个热添加磁盘架布线：

+
image::../media/drw_ns224_g_1shelf_1card_ieops-2002.svg[为AFF或ASA A30布线,452px,AFF/ASA A50]



. 如果要在每个控制器模块中使用两组支持 RoCE 的端口（两个支持 RoCE 的 I/O 模块）热添加一个或两个磁盘架，请完成相应的子步骤。
+

NOTE: 此步骤假定您已在插槽3和1中安装了支持RoCE的I/O模块。

+
[cols="1,3"]
|===
| 磁盘架 | 布线 


 a| 
磁盘架 1
 a| 
.. 使用缆线将NSM A端口exa连接到控制器A插槽3端口A (E3A)。
.. 使用缆线将NSM A端口EXB连接到控制器B插槽1端口b (e1b)。
.. 使用缆线将NSM B端口exa连接到控制器B插槽3端口A (E3A)。
.. 使用缆线将NSM B端口EXB连接到控制器A插槽1端口b (e1b)。
.. 如果您要快速添加第二个搁板，请完成“`搁板 2`”子步骤；否则，请转到下一步。


下图显示了如何在每个控制器模块中使用两个支持RoCE的I/O模块为一个热添加磁盘架布线：

image::../media/drw_ns224_g_1shelf_2card_ieops-2005.svg[为AFF或ASA A30布线,452px,AFF/ASA A50]



 a| 
磁盘架 2
 a| 
.. 使用缆线将NSM A端口exa连接到控制器A插槽1的端口a (e1a)。
.. 使用缆线将NSM A端口EXB连接到控制器B插槽3端口b (e3b)。
.. 使用缆线将NSM B端口exa连接到控制器B插槽1端口A (e1a)。
.. 使用缆线将NSM B端口EXB连接到控制器A插槽3端口b (e3b)。
.. 转至下一步。


下图显示了在每个控制器模块中使用两个支持RoCE的I/O模块为两个热添加磁盘架布线：

image::../media/drw_ns224_g_2shelf_2card_ieops-2003.svg[为AFF ASA布线,452px,AFF/ASA A50]

|===
. 使用验证热添加磁盘架的布线是否正确 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]。
+
如果生成任何布线错误，请按照提供的更正操作进行操作。



.下一步行动
如果在此过程的准备过程中禁用了自动驱动器分配，则需要手动分配驱动器所有权，然后在需要时重新启用自动驱动器分配。转到 link:hot-add-aff-complete.html["完成热添加"]。

否则、您将完成热添加磁盘架过程。
