---
permalink: ns224/hot-remove-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, drive, aggregate, ha, pair, serving, data, i/o, hot-remove an ns224 
summary: 您可以在已启动并提供数据的 HA 对中热删除已从驱动器中删除聚合的 NS224 驱动器架（ I/O 正在进行中）。 
---
= Hot-remove a shelf - NS224 shelves
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在已启动且正在提供数据（ I/O 正在进行）的 HA 对中热删除已从驱动器中删除聚合的 NS224 驱动器架。

.开始之前
* HA 对不能处于接管状态。
* 您必须已从要移除的磁盘架中的驱动器（驱动器必须为备用驱动器）中删除所有聚合。
+

NOTE: 如果尝试使用要删除的磁盘架上的聚合执行此操作步骤，则可能会使系统出现故障，并出现多磁盘崩溃。

+
您可以使用 `storage aggregate offline -aggregate _aggregate_name_` 命令，然后使用 `storage aggregate delete -aggregate _aggregate_name_` 命令。

* 如果系统随附在系统机柜中，则需要使用十字螺丝刀卸下将磁盘架固定到机柜后部右上角的螺钉。


.关于此任务
* 如果要热移除多个磁盘架，请一次移除一个磁盘架。
* * 最佳实践： * 最佳实践是，从要移除的磁盘架中的驱动器中删除聚合后，删除驱动器所有权。
+
通过从备用驱动器中删除所有权信息，可以根据需要将该驱动器正确集成到另一个节点中。

+
可从磁盘和聚合内容中找到用于从驱动器中删除所有权的操作步骤：

+
https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["磁盘和聚合概述"^]




NOTE: 操作步骤要求您禁用自动驱动器分配。您可以在此操作步骤末尾重新启用自动驱动器分配（在热移除磁盘架后）。

* 如果需要，您可以打开磁盘架的位置（蓝色） LED ，以帮助以物理方式定位受影响的磁盘架： `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
如果您不知道受影响磁盘架的 ` _shelf_name_` ，请运行 `storage shelf show` 命令。

+
一个磁盘架具有三个位置 LED ：一个位于操作员显示面板上，一个位于每个 NSM 模块上。定位 LED 保持亮起 30 分钟。您可以通过输入相同的命令并使用 off 选项来将其关闭。

* 从不支持 RoCE 的专用端口（板载控制器，支持 RoCE 的 PCIe 卡，两者的组合或 I/O 模块）上断开磁盘架连接后，您可以选择重新配置这些端口以供网络使用。
+

NOTE: 如果 HA 对运行的是 ONTAP 9.6 版，则需要一次重新启动一个控制器。如果 HA 对运行的是 ONTAP 9.7 或更高版本，则无需重新启动控制器，除非一个或两个控制器均处于维护模式。此操作步骤假定两个控制器均未处于维护模式。



.步骤
. 正确接地。
. 验证要移除的磁盘架中的驱动器没有聚合（备用），并且所有权已删除：
+
.. 输入以下命令以列出要移除的磁盘架中的所有驱动器： `storage disk show -shelf _shelf_number_`
+
您可以在任一控制器模块上输入命令。

.. 检查输出以确认驱动器上没有聚合。
+
无聚合的驱动器在 `Container Name` 列中有一个短划线。

.. 检查输出以确认所有权已从驱动器中删除。
+
无所有权的驱动器在 `owner` 列中有一个短划线。

+

NOTE: 如果驱动器出现故障，则它们会在 `Container Type` 列中显示 broken 。（故障驱动器没有所有权。）

+
以下输出显示了要移除的磁盘架（磁盘架 2 ）上的驱动器处于正确的状态，可用于移除磁盘架。所有驱动器上的聚合都会被删除；因此，每个驱动器的 `Container Name` 列会显示一个短划线。所有驱动器上的所有权也会被删除；因此，每个驱动器的 `owner` 列中会显示一个短划线。



+
[listing]
----
cluster1::> storage disk show -shelf 2

           Usable           Disk     Container   Container
Disk         Size Shelf Bay Type     Type        Name       Owner
-------- -------- ----- --- ------   ----------- ---------- ---------
...
2.2.4           -     2   4 SSD-NVM  spare                -         -
2.2.5           -     2   5 SSD-NVM  spare                -         -
2.2.6           -     2   6 SSD-NVM  broken               -         -
2.2.7           -     2   7 SSD-NVM  spare                -         -
...
----
. 以物理方式找到要移除的磁盘架。
. 从要移除的磁盘架断开布线：
+
.. 打开电源线固定器，断开电源线与电源的连接，然后从电源中拔下电源线。
+
电源没有电源开关。

.. 断开存储布线（从磁盘架到控制器）。


. 从机架或机柜中物理卸下磁盘架。
+

NOTE: 满载的 NS224 磁盘架的重量最多可达 66.78 磅（ 30.29 千克），需要两个人抬起或使用液压升降机。请避免移除磁盘架组件（从磁盘架前部或后部）以减少磁盘架重量，因为磁盘架重量会变得不平衡。

+

NOTE: 如果您的系统是在机柜中发货的，则必须先拧下将磁盘架固定到后上的两个十字螺钉。这些螺钉位于底部 NSM 模块的机架内侧。您应同时卸下两个 NSM 模块才能使用螺钉。

. 如果要删除多个磁盘架，请重复步骤 2 到 5 。
+
否则，请转至下一步。

. 如果在从驱动器中删除所有权时禁用了自动驱动器分配，请重新启用它： `storage disk option modify -autodassign on`
+
您可以在两个控制器模块上运行命令。

. 您可以通过完成以下子步骤来重新配置不支持专用 RoCE 的端口以供网络使用。
+
否则，您将使用此操作步骤。

+
.. 验证当前为存储配置的非专用端口的名称： `storage port show`
+
您可以在任一控制器模块上输入命令。

+

NOTE: The non-dedicated ports configured for storage use are displayed in the output as follows: If your HA pair is running ONTAP 9.8 or later, the non-dedicated ports display `storage` in the `Mode` column.If your HA pair is running ONTAP 9.7 or 9.6, the non-dedicated ports, which display `false` in the `Is Dedicated?` column, also display `enabled` in the `State` column.

.. 完成适用于 HA 对所运行的 ONTAP 版本的一组步骤：
+
[cols="1,2"]
|===
| 如果 HA 对正在运行 ... | 那么 ... 


 a| 
ONTAP 9.8 或更高版本
 a| 
... 在第一个控制器模块上重新配置非专用端口以供网络使用： `storage port modify -node _node name_ -port _port name_ -mode network`
+
您必须对要重新配置的每个端口运行此命令。

... 重复上述步骤以重新配置第二个控制器模块上的端口。
... 转至子步骤 8c 以验证所有端口更改。




 a| 
ONTAP 9.7
 a| 
... 在第一个控制器模块上重新配置非专用端口以供网络使用： `storage port disable -node _node name_ -port _port name_`
+
您必须对要重新配置的每个端口运行此命令。

... 重复上述步骤以重新配置第二个控制器模块上的端口。
... 转至子步骤 8c 以验证所有端口更改。




 a| 
ONTAP 9.6 版
 a| 
... 在第一个控制器模块上重新配置支持 RoCE 的端口以供网络使用： `storage port disable -node _node name_ -port _port name_`
+
您必须对要重新配置的每个端口运行此命令。

... 重新启动控制器模块以使端口更改生效：
+
`ssystem node reboot -node _node name_ -reason _reason_ for the reboot`

+

NOTE: 必须完成重新启动，然后才能继续执行下一步。重新启动可能需要长达 15 分钟。

... 重复第一步（ A ），重新配置第二个控制器模块上的端口。
... 重复第二步（ b ），重新启动第二个控制器以使端口更改生效。
... 转至子步骤 8c 以验证所有端口更改。


|===
.. 验证是否已重新配置两个控制器模块的非专用端口以供网络使用： `storage port show`
+
您可以在任一控制器模块上输入命令。

+
如果 HA 对运行的是 ONTAP 9.8 或更高版本，则非专用端口会在 `Mode` 列中显示 `network` 。

+
如果 HA 对运行的是 ONTAP 9.7 或 9.6 ，则非专用端口会在 `is dedicated ？` 中显示 `false` 列中，也会在 `State` 列中显示 `d已标记` 。




