---
permalink: ns224/install-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, install, hot-add an ns224 drive shelf 
summary: 您可以在 HA 对满足特定要求后以及完成适用于 HA 对的准备任务后热添加 NS224 驱动器架。 
---
= 为热添加—NS224磁盘架安装磁盘架
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要在机柜或电信机架中安装NS224磁盘架、连接电源线(自动为磁盘架供电)并设置磁盘架ID。

.开始之前
* 请确保您的回形针一侧拉直或使用窄尖的圆珠笔。
+
要更改磁盘架ID、请使用回形针或圆珠笔访问操作员显示面板(ODP)后面的磁盘架ID按钮以执行更改磁盘架ID步骤。

* 请注意、满载的NS224架的重量可达66.78磅(30.29千克)、需要两个人来提升或使用液压提升装置。Avoid removing shelf components (from the front or rear of the shelf) to reduce the shelf weight, because shelf weight will become unbalanced.


.步骤
. 根据需要、按照套件附带的说明安装磁盘架导轨套件。
+

NOTE: 请勿使用法兰安装磁盘架。

. 安装磁盘架：
+
.. 将磁盘架的背面置于导轨上、然后从底部支撑磁盘架、并将其滑入机柜或电信机架。
+
如果要安装多个磁盘架、请将第一个磁盘架直接置于控制器上方。将第二个磁盘架直接放在控制器下方。对任何其他磁盘架重复此模式。

.. 使用套件中提供的安装螺钉将磁盘架固定到机柜或电信机架上。


. 连接电源：
+
.. 将电源线连接到磁盘架并将其固定到位。
+
如果是交流电源、请使用电源线固定器将其固定到位。

+
如果是直流电源、请使用两颗指旋螺钉将其固定到位。

.. 将电源线连接到不同的电源以实现故障恢复能力。
+
连接到电源时，磁盘架将通电；它没有电源开关。正常运行时，电源的双色 LED 将呈绿色亮起。



. 将磁盘架 ID 设置为 HA 对中唯一的数字：
+
有关详细说明，请参见 link:change-shelf-id.html["更改磁盘架 ID — NS224 磁盘架"^]。

+
.. 拆下左端盖，找到 LED 右侧的小孔。
.. 将回形针或类似工具的一端插入小孔中，以到达磁盘架 ID 按钮。
.. 按住按钮（最长 15 秒），直到数字显示屏上的第一个数字闪烁，然后释放按钮。
+
如果此 ID 闪烁所需时间超过 15 秒，请再次按住此按钮，确保一直按此按钮。

.. 按下并释放此按钮可将此数字向前移动，直到达到所需数字 0 到 9 为止。
.. 重复子步骤 4c 和 4d 以设置磁盘架 ID 的第二个数字。
+
此数字可能需要长达三秒（而不是 15 秒）的时间才会闪烁。

.. 按住按钮，直到第二个数字停止闪烁。
+
大约 5 秒钟后，两个数字开始闪烁，并且耗时值上的琥珀色 LED 亮起。

.. 重新启动磁盘架以使磁盘架 ID 生效。
+
您必须从磁盘架上拔下两根电源线，等待 10 秒，然后重新插入。

+
电源恢复供电后，其双色 LED 将呈绿色亮起。





.下一步是什么？
为热添加磁盘架布线。转到。 link:cable-overview-hot-add-shelf.html["热添加布线概述"]
