---
permalink: ns224/prepare-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf 
summary: 您可以在 HA 对满足特定要求后以及完成适用于 HA 对的准备任务后热添加 NS224 驱动器架。 
---
= 准备热添加—NS224磁盘架
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在热添加NS224磁盘架之前、完成适用于HA对的准备任务。

完成适用的准备任务后，请转至 link:prepare-hot-add-shelf.html["安装用于热添加的磁盘架"]。



== 安装支持RoCE的PCIe卡或I/O模块

如果您的平台型号支持使用支持RoCE的PCIe卡或I/O模块、则HA对必须具有足够的支持RoCE的可用以太网端口、以支持要热添加的磁盘架数量。

.步骤
. 对于要热添加的每个磁盘架、验证每个控制器上是否有两个支持RoCE的端口。
+
这些端口可以位于控制器板上，支持 RoCE 的 PCIe 卡上，两者的组合，也可以位于支持 RoCE 的 I/O 模块上，这一点受您的平台型号支持。

. 如果HA对没有足够的支持RoCE的可用端口、请根据您的平台型号将其他PCIe卡或I/O模块安装到正确的控制器插槽中。
+
.. 确定适用于您的平台型号的正确控制器插槽。请参阅。 https://hwu.netapp.com["NetApp Hardware Universe"^]
.. 有关PCIe卡或I/O模块的安装说明、请参见您的平台型号文档。






== 配置支持RoCE的端口以供存储使用

如果HA对具有非专用的RoCE以太网端口、而您要使用这些端口热添加NS224磁盘架、则必须将这些端口配置为用于存储(而不是用于网络连接)。

.开始之前
* 确保在每个控制器中安装了任何其他支持RoCE的PCIe卡或I/O模块。


.关于此任务
* 对于某些平台型号、如果将支持RoCE的PCIe卡或I/O模块安装在控制器上受支持的插槽中、则这些端口会自动默认为storage use (而不是连网)； 但是、建议您完成以下过程、以验证是否已为存储配置支持RoCE的端口。
* 如果您确定 HA 对中不支持 RoCE 的专用端口未配置为存储使用，则配置这些端口是无中断操作步骤。
+
根据HA对运行的ONTAP版本、您可能需要重新启动控制器：

+
** 如果 HA 对运行的是 ONTAP 9.6 版，则需要重新启动控制器，一次重新启动一个控制器。
** 如果 HA 对运行的是 ONTAP 9.7 或更高版本，则无需重新启动控制器，除非一个或两个控制器均处于维护模式。此操作步骤假定两个控制器均未处于维护模式。


* 如果将来需要将端口从存储更改为网络连接，请输入命令 `storage port modify -node _node_name_ -port _port_name_ -mode network`。


.步骤
. 使用SSH或串行控制台端口登录到集群。
. 输入以下命令以验证是否已为HA对中的非专用端口配置存储使用：
+
`storage port show`

+
** 如果 HA 对运行的是 ONTAP 9.8 或更高版本，则非专用端口在 `Mode` 列中显示 `storage` 。
** 如果 HA 对运行的是 ONTAP 9.7 或 9.6 ，则非专用端口会在 `is dedicated ？` 中显示 `false` 列中，也会在 `State` 列中显示 `enabled` 。
+
[NOTE]
====
如果未配置非专用端口以供存储使用，则命令输出将显示以下内容：

*** 如果 HA 对运行的是 ONTAP 9.8 或更高版本，则非专用端口会在 `Mode` 列中显示 `network` 。
*** 如果 HA 对运行的是 ONTAP 9.7 或 9.6 ，则非专用端口会在 `is dedicated ？`` 中显示 `false` 列中，也会在 `State` 列中显示 `d已标记` 。


====


. 如果配置了非专用端口以供存储使用，则可以使用此操作步骤。
+
Otherwise, you need to configure the ports by completing steps 4 through 7.

. 在其中一个控制器上配置用于存储的非专用端口：
+
您必须对要配置的每个端口重复适用的命令。

+
[cols="1,3"]
|===
| 如果 HA 对正在运行 ... | 使用的命令 


 a| 
ONTAP 9.8 或更高版本
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7 或 9.6
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. 如果HA对运行的是ONTAP 9.6，请重新启动控制器，以使端口更改生效： `system node reboot -node _node_name_ -reason _reason_for_the_reboot_`。
+
否则，请转至下一步。

+

NOTE: 重新启动可能需要长达 15 分钟。

. 对第二个控制器重复上述步骤：
+
[cols="1,3"]
|===
| 如果 HA 对正在运行 ... | 那么 ... 


 a| 
ONTAP 9.7 或更高版本
 a| 
.. Repeat step 4.
.. 转至第 7 步。




 a| 
ONTAP 9.6
 a| 
.. 重复步骤4和5。
+

NOTE: 第一个控制器必须已完成重新启动。

.. 转至第 7 步。


|===
. 验证是否已为两个控制器上的非专用端口配置存储使用： `storage port show`
+
** 如果 HA 对运行的是 ONTAP 9.8 或更高版本，则非专用端口在 `Mode` 列中显示 `storage` 。
** 如果 HA 对运行的是 ONTAP 9.7 或 9.6 ，则非专用端口会在 `is dedicated ？` 中显示 `false` 列中，也会在 `State` 列中显示 `enabled` 。






== 可重新对现有磁盘架进行配置

在热添加其他磁盘架之前、根据您的平台型号、您可能需要在不同插槽中的两组端口之间重新对现有磁盘架进行故障恢复(在安装了支持RoCE的其他PCIe卡或I/O模块之后)、以防止插槽故障。

.开始之前
* 确保在每个控制器中安装了任何其他支持RoCE的PCIe卡或I/O模块。
* 确保您安装的具有RoCE功能的PCIe卡或I/O模块上的非专用端口已配置为可用于存储。


.关于此任务
* 如果您的磁盘架具有多路径 HA 连接，则为端口连接重新布线是一种无中断操作步骤。
* 在此过程中、您一次移动一根缆线、以始终保持与磁盘架的连接。
+

NOTE: 移动缆线无需等待从一个端口拔下缆线与将缆线插入另一个端口之间的时间。

* 如果需要，请参阅中适用于您的平台型号的磁盘架布线图 link:cable-overview-hot-add-shelf.html["热添加布线概述"]。


.步骤
. 根据您的平台型号、在不同插槽中的两组支持RoCE的端口之间重新对现有磁盘架的连接进行转换。


[role="tabbed-block"]
====
.AFF A1K
--
如果要热添加第二个或第四个磁盘架、请执行以下操作之一。


NOTE: 如果您有一个AFF A1K HA对、并且要热添加第三个磁盘架、并在每个控制器中安装第三个或第四个支持RoCE的I/O模块、则第三个磁盘架仅连接到第三个或第三个和第四个I/O模块。您无需重新对任何现有磁盘架进行配置。

* 如果要热添加第二个磁盘架、请在每个控制器上的插槽11和插槽10中的支持RoCE的I/O模块之间重新对第一个磁盘架进行配缆线。
+
子步骤假定已将现有磁盘架连接到每个控制器上插槽11中支持RoCE的I/O模块。

+
.. 在控制器 A 上，将缆线从插槽 11 端口 b （ e11b ）移至插槽 10 端口 b （ e10b ）。
.. 对控制器 B 重复相同的缆线移动操作


* 如果要热添加第四个磁盘架、请在每个控制器上的插槽9和插槽8中的支持RoCE的I/O模块之间重新对第三个磁盘架进行配缆线。
+
子步骤假定第三个磁盘架已连接到每个控制器上插槽9中支持RoCE的I/O模块。

+
.. 在控制器 A 上，将缆线从插槽 9 端口 b （ e9b ）移至插槽 8 端口 b （ e8b ）。
.. 对控制器 B 重复相同的缆线移动操作




--
.AFF A70或AFF A90
--
如果要热添加第二个磁盘架、请在每个控制器上的插槽11和插槽8中的支持RoCE的I/O模块之间重新对第一个磁盘架进行配缆线。

子步骤假定已将现有磁盘架连接到每个控制器上插槽11中支持RoCE的I/O模块。

. 在控制器 A 上，将缆线从插槽 11 端口 b （ e11b ）移至插槽 8 端口 b （ e8b ）。
. 对控制器 B 重复相同的缆线移动操作


--
.AFF A800或AFF C800
--
如果要热添加第二个磁盘架、请在每个控制器的插槽5和插槽3中的两组支持RoCE的端口之间重新对第一个磁盘架进行缆线连接。

这些子步骤假定已将现有磁盘架连接到每个控制器上插槽 5 中支持 RoCE 的 PCIe 卡。

. 在控制器 A 上，将缆线从插槽 5 端口 b （ e5b ）移至插槽 3 端口 b （ e3b ）。
. 对控制器 B 重复相同的缆线移动操作


--
.AFF A700
--
如果要热添加第二个磁盘架、请在每个控制器的插槽3和插槽7中的两组支持RoCE的端口之间重新对第一个磁盘架进行缆线连接。

这些子步骤假定已将现有磁盘架连接到每个控制器上插槽 3 中支持 RoCE 的 I/O 模块。

. 在控制器 A 上，将缆线从插槽 3 端口 b （ e3b ）移至插槽 7 端口 b （ e7b ）。
. 对控制器 B 重复相同的缆线移动操作


--
.AFF A400或AFF C400
--
如果要热添加第二个磁盘架、请根据您的平台型号执行以下操作之一：

* 在AFF A400上：
+
在每个控制器上的两组支持RoCE的端口(板载e0c/e0d和插槽5)之间重新对第一个磁盘架进行缆线连接。

+
子步骤假定已将现有磁盘架连接到每个控制器上支持RoCE的板载端口e0c/e0d。

+
.. 在控制器 A 上，将缆线从端口 e0d 移至插槽 5 端口 b （ e5b ）。
.. 对控制器 B 重复相同的缆线移动操作


* 在AFF C400上：
+
在每个控制器的插槽4和插槽5中的两组支持RoCE的端口之间重新对第一个磁盘架进行缆线连接。

+
子步骤假定已将现有磁盘架连接到每个控制器上插槽4中支持RoCE的端口。

+
.. 在控制器A上、将缆线从插槽4端口A (E4A)移至插槽5端口b (e5b)。
.. 对控制器 B 重复相同的缆线移动操作




--
====
. 使用验证重新布线的磁盘架是否已正确布线 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]。
+
如果生成任何布线错误，请按照提供的更正操作进行操作。





== 禁用自动驱动器分配

如果要为热添加的NS224磁盘架手动分配驱动器所有权、则需要禁用自动驱动器分配(如果已启用)。

如果您不确定是否应手动分配驱动器所有权，或者要了解存储系统的驱动器所有权策略的自动分配，请转至 https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["关于磁盘所有权的自动分配"^]。

.步骤
. 验证是否已启用自动驱动器分配： `storage disk option show`
+
您可以在任一节点上输入命令。

+
如果启用了自动驱动器分配、则输出将显示 `on` 在列中 `Auto Assign` (对于每个节点)。

. 如果启用了自动驱动器分配，请将其禁用： `storage disk option modify -node _node_name_ -autodassign off`
+
您必须在两个节点上禁用自动驱动器分配。


