---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: 如果运行 ONTAP 9.7 或更高版本的 HA 对中的 NS224 驱动器架上的启动介质出现故障，或者磁盘架运行的是 NVMe 磁盘架模块（ NSM\ ）固件版本 1.1x 或更高版本，则可以更换启动介质。在驱动器架通电且 I/O 正在进行的情况下，可以无中断地更换启动介质。 
---
= 更换启动介质 &#8201 ； &#8212 ； &#8201 ； NS224 磁盘架
:icons: font
:imagesdir: ../media/


[role="lead"]
如果运行 ONTAP 9.7 或更高版本的 HA 对中的 NS224 驱动器架上的启动介质出现故障，或者磁盘架运行的是 NVMe 磁盘架模块（ NSM ）固件版本 1.1x 或更高版本，则可以更换启动介质。在驱动器架通电且 I/O 正在进行的情况下，可以无中断地更换启动介质。

.开始之前
* 您的 HA 对必须已运行 ONTAP 9.7 或更高版本，并且此版本至少支持 NSM 固件版本，或者您的 HA 对必须已运行 ONTAP 9.6 版本且 NSM 固件版本为 1.1x 或更高版本。
+
您可以在任一控制器的控制台中输入 `storage shelf show -module` 命令，以验证磁盘架上的 NSM 固件版本。

+
[NOTE]
====
如果您的磁盘架未运行 NSM 固件版本 1.1x 或更高版本，则无法更换启动介质，您必须更换 NSM 模块。

link:service-replace-nsm100.html["更换 NSM 模块— NS224 磁盘架"^]

====
* 您需要一把 1 号十字螺丝刀。
+
用于将启动介质固定到主板的螺钉需要 1 号十字螺丝刀；使用其他类型的螺丝刀可能会使螺钉脱开。

* 磁盘架的配对 NSM 模块必须已启动且正在运行，并且已正确布线，以便在卸下出现故障的 FRU （目标 NSM 模块）的 NSM 模块时，磁盘架可以保持连接。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]

* 系统中的所有其他组件必须正常运行。


.关于此任务
* 更换启动介质后，磁盘架的配对 NSM 模块中的启动映像会自动复制到更换的启动介质中。
+
这可能需要长达五分钟的时间。

* 在拆卸和安装 NVMe 磁盘架模块（ NSM ）之间至少留出 70 秒。
+
这样， ONTAP 就有足够的时间来处理 NSM 删除事件。

* * 最佳实践： * 最佳实践是，在更换 FRU 组件之前，应在系统上安装最新版本的 NVMe 磁盘架模块（ NSM ）固件和驱动器固件。
+
[NOTE]
====
请勿将固件还原到不支持您的磁盘架及其组件的版本。

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 下载：磁盘架固件"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 下载：磁盘驱动器固件"^]

====
* 如果需要，您可以打开磁盘架的位置（蓝色） LED ，以帮助以物理方式定位受影响的磁盘架： `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
如果您不知道受影响磁盘架的 ` _shelf_name_` ，请运行 `storage shelf show` 命令。

+
一个磁盘架具有三个位置 LED ：一个位于操作员显示面板上，一个位于每个 NSM 模块上。定位 LED 保持亮起 30 分钟。您可以通过输入相同的命令，但使用 `off` 选项将其关闭。

* 更换启动介质后，您可以按照套件随附的 RMA 说明中所述将故障部件退回 NetApp 。
+
If you need the RMA number or additional help with the replacement procedure, contact technical support at https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"^], 888-463-8277 (North America), 00-800-44-638277 (Europe), or +800-800-80-800 (Asia/Pacific).

* 您可以使用以下视频或写入的步骤更换启动介质。
+
https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=20ed85f9-1f80-4e0e-9219-ab4600070d8a["更换 NS224 驱动器架中的启动介质"^]



.步骤
. 正确接地。
. 从包含要更换的 FRU 的 NSM 模块断开布线：
+
.. 打开电源线固定器，断开电源线与电源的连接，然后从电源中拔下电源线。
+
电源没有电源开关。

.. 断开存储布线与 NSM 模块端口的连接。
+
记下每个缆线连接到的 NSM 模块端口。稍后在此操作步骤中重新插入 NSM 模块时，您需要将缆线重新连接到相同的端口。



. 从磁盘架中卸下 NSM 模块：
+
.. 将索引指针绕过 NSM 模块两侧的锁定机制的指孔。
+

NOTE: 如果您要卸下底部 NSM 模块，并且底部导轨阻碍了对锁定机制的访问，请将索引指针从内部穿过指针孔（通过跨越臂）。

.. 用拇指按住锁定机制顶部的橙色卡舌。
+
闩锁机制将抬起，以清除磁盘架上的闩锁销。

.. 轻轻地将 NSM 模块拉出磁盘架，直到大约三分之一的位置，用双手抓住 NSM 模块的两侧以支撑其重量，然后将其放在平稳的表面上。
+
开始拉动时，锁定装置臂从 NSM 模块伸出并锁定在完全展开的位置。



. 松开 NSM 模块外盖翼形螺钉并打开外盖。
. 以物理方式找到故障启动介质。
+
启动介质位于电源对面的机架机箱墙上。位于启动介质插槽旁边的主板上的启动介质警示（琥珀色） LED 将亮起。

+

NOTE: 从磁盘架中卸下 NSM 模块后，此 LED 将保持亮起 10 分钟。

. 更换启动介质：
+
.. 使用 1 号十字螺丝刀小心地卸下将启动介质底端（有缺口）固定到主板的螺钉。
.. 将启动介质的凹口一端稍向上旋转，然后向您轻拉，直到其从插槽中释放为止，以将其取出。
+
您可以将拇指和食指放在侧边的凹口端，以握住启动介质

.. 从防静电袋中打开启动介质的包装。
.. 将替代启动介质轻轻推入插槽，直至其完全固定在插槽中，以插入该介质。
+
您可以将拇指和食指放在侧边的凹口端，以握住启动介质确保散热器的一侧朝上。

+
正确就位后，当您松开启动介质时，启动介质的带凹口一端会与主板成角度，因为它尚未使用螺钉固定。

.. 在插入启动介质时，轻轻按住启动介质的凹口端，然后使用螺丝刀拧紧螺钉以将启动介质固定到位。
+

NOTE: 将螺钉拧紧到足以将启动介质固定到位的位置，但不要过度拧紧。



. 合上 NSM 模块外盖，然后拧紧翼形螺钉。
. 将 NSM 模块重新插入磁盘架：
+
.. 确保锁定装置臂锁定在完全展开的位置。
.. 用双手将 NSM 模块轻轻滑入磁盘架，直到磁盘架完全支撑 NSM 模块的重量为止。
.. 将 NSM 模块推入磁盘架，直到其停止（距离磁盘架背面大约半英寸）。
+
您可以将拇指放在每个（锁定装置臂的）指环正面的橙色卡舌上，以推入 NSM 模块。

.. 将索引指针绕过 NSM 模块两侧的锁定机制的指孔。
+

NOTE: 如果您要插入底部 NSM 模块，并且底部导轨阻碍了对锁定机制的访问，请将索引指针从内部穿过指针孔（通过跨越臂）。

.. 用拇指按住锁定机制顶部的橙色卡舌。
.. 轻轻向前推，使闩锁超过停止位置。
.. 从锁定机制的顶部释放拇指，然后继续推动，直到锁定机制卡入到位。
+
NSM 模块应完全插入磁盘架并与磁盘架边缘平齐。



. 重新连接到 NSM 模块的布线：
+
.. 将存储布线重新连接到同一两个 NSM 模块端口。
+
插入缆线时，连接器拉片朝上。正确插入缆线后，它会卡入到位。

.. 将电源线重新连接到电源，然后使用电源线固定器固定电源线。
+
正常运行时，电源的双色 LED 将呈绿色亮起。

+
此外，两个 NSM 模块端口 LNK （绿色） LED 均会亮起。如果 LNK LED 不亮，请重新拔插缆线。



. 验证包含故障启动介质的 NSM 模块和磁盘架操作员显示面板上的警示（琥珀色） LED 是否不再亮起。
+
关闭警示 LED 可能需要 5 到 10 分钟。这是 NSM 模块重新启动和完成启动介质映像副本所需的时间。

+
如果故障 LED 保持亮起状态，则可能无法正确安装启动介质或可能存在其他问题描述，您应联系技术支持以获得帮助。

. 运行 Active IQ Config Advisor ，验证 NSM 模块的布线是否正确。
+
如果生成任何布线错误，请按照提供的更正操作进行操作。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]


