---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 您可以在 I/O 正在进行时无中断地更换已启动的 NS224 驱动器架中的故障驱动器。 
---
= Hot-swap a drive - NS224 shelves
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 I/O 正在进行时无中断地更换已启动的 NS224 驱动器架中的故障驱动器。

.开始之前
* NS224 磁盘架必须支持您要安装的驱动器。
+
https://["NetApp Hardware Universe"^]

* 如果启用了 SED 身份验证，则必须使用 ONTAP 文档中的 SED 更换说明。
+
ONTAP 文档中的说明介绍了在更换 SED 之前和之后必须执行的其他步骤。

+
https://["使用命令行界面概述 NetApp 加密"^]

* 系统中的所有其他组件必须正常运行；否则，请联系技术支持。
* 验证要删除的驱动器是否出现故障。
+
您可以运行 `storage disk show -broken` 命令来验证驱动器是否出现故障。故障驱动器将显示在故障驱动器列表中。如果不是，则应等待，然后重新运行命令。

+

NOTE: 根据驱动器类型和容量，该驱动器可能需要长达数小时才能显示在故障驱动器列表中。



.关于此任务
* * 最佳实践： * 最佳实践是，在热插拔驱动器之前，安装最新版本的磁盘认证包（ DQP ）。
+
安装最新版本的 DQP 后，您的系统便可识别和使用新认证的驱动器。这样可以避免出现有关驱动器信息不最新以及由于无法识别驱动器而阻止驱动器分区的系统事件消息。DQP 还会通知您驱动器固件不是最新的。

+
https://["NetApp 下载：磁盘认证包"^]

* * 最佳实践： * 最佳实践是，在更换 FRU 组件之前，应在系统上安装最新版本的 NVMe 磁盘架模块（ NSM ）固件和驱动器固件。
+
https://["NetApp 下载：磁盘架固件"^]

+
https://["NetApp 下载：磁盘驱动器固件"^]

+
[NOTE]
====
请勿将固件还原到不支持您的磁盘架及其组件的版本。

====
* 在固件版本不是最新的新驱动器上，驱动器固件会自动更新（无中断）。
+

NOTE: 驱动器固件检查每两分钟进行一次。

* 如果需要，您可以打开磁盘架的位置（蓝色） LED ，以帮助以物理方式定位受影响的磁盘架： `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
如果您不知道受影响磁盘架的 ` _shelf_name_` ，请运行 `storage shelf show` 命令。

+
一个磁盘架具有三个位置 LED ：一个位于操作员显示面板上，一个位于每个 NSM 模块上。定位 LED 保持亮起 30 分钟。您可以通过输入相同的命令，但使用 `off` 选项将其关闭。

* 拆开备用驱动器的包装时，请保存所有包装材料，以便在退回故障驱动器时使用。
+
If you need the RMA number or additional help with the replacement procedure, contact technical support at https://["NetApp 支持"^], 888-463-8277 (North America), 00-800-44-638277 (Europe), or +800-800-80-800 (Asia/Pacific).

* 以下动画简要介绍了驱动器热插拔操作步骤 的物理拆卸和插入部分。
+
.动画—热插拔NS224驱动器架中的驱动器
video::733011a7-e03a-41b0-8723-aa840133bf25[panopto]
+
.步骤
.. 如果要手动为替代驱动器分配驱动器所有权，则需要禁用自动驱动器分配（如果已启用）。
+

NOTE: 如果磁盘架中的驱动器由 HA 对中的两个控制器模块拥有，则需要手动分配驱动器所有权。

+

NOTE: 您可以手动分配驱动器所有权，然后在此操作步骤中稍后重新启用自动驱动器分配。

+
... 验证是否已启用自动驱动器分配： `storage disk option show`
+
您可以在任一控制器模块上输入命令。

+
如果启用了自动驱动器分配，则输出会在 `Auto Assign` 列中显示 `on` （对于每个控制器模块）。

... 如果启用了自动驱动器分配，请将其禁用： `storage disk option modify -node node_name -autodassign off`
+
您必须在两个控制器模块上禁用自动驱动器分配。



.. 正确接地。
.. 以物理方式确定故障驱动器。
+
驱动器发生故障时，系统会向系统控制台记录一条警告消息，指示哪个驱动器发生故障。此外，驱动器架操作员显示面板上的警示（琥珀色） LED 和故障驱动器将亮起。

+

NOTE: 故障驱动器上的活动（绿色） LED 可能会亮起（稳定亮起），表示驱动器已通电，但不应闪烁，这表示 I/O 活动。故障驱动器没有 I/O 活动。

.. 删除故障驱动器：
+
... 按下驱动器表面上的释放按钮以打开凸轮把手。
... 使用凸轮把手将驱动器滑出磁盘架，并用另一只手支撑驱动器。


.. 请至少等待 70 秒，然后再插入替代驱动器。
+
这样，系统就可以识别出驱动器已被删除。

.. 插入替代驱动器：
+
... 在凸轮把手处于打开位置的情况下，用双手插入替代驱动器。
... 按，直到驱动器停止。
... 合上凸轮把手，使驱动器完全固定在中间板上，并使把手卡入到位。
+
请务必缓慢地关闭凸轮把手，使其与驱动器正面正确对齐。



.. 验证驱动器的活动（绿色） LED 是否亮起。
+
如果驱动器的活动 LED 稳定亮起，则表示驱动器已通电。当驱动器的活动 LED 闪烁时，表示驱动器已通电且 I/O 正在进行中。如果驱动器固件正在自动更新，则 LED 将闪烁。

.. 如果要更换另一个驱动器，请重复步骤 3 到步骤 7 。
.. 如果您在步骤 1 中禁用了自动驱动器分配，请手动分配驱动器所有权，然后根据需要重新启用自动驱动器分配：
+
... 显示所有未分配的驱动器： `storage disk show -container-type unassigned`
+
您可以在任一控制器模块上输入命令。

... 分配每个驱动器： `storage disk assign -disk disk_name -owner owner_name`
+
您可以在任一控制器模块上输入命令。

+
您可以使用通配符一次分配多个驱动器。

... 如果需要，请重新启用自动驱动器分配： `storage disk option modify -node node_name -autodassign on`
+
您必须在两个控制器模块上重新启用自动驱动器分配。






