---
permalink: ns224/service-replace-nsm100.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, impair, nvme, module, nsm, nondisruptive, drive, i/o, nsm, replace an nsm module 
summary: 您可以在已启动且正在执行 I/O 的 NS224 驱动器架中无中断更换受损的 NVMe 磁盘架模块（ NSM\ ）。 
---
= 更换 NSM 模块— NS224 磁盘架
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在已启动且正在执行 I/O 的 NS224 驱动器架中无中断更换受损的 NVMe 磁盘架模块（ NSM ）。

.开始之前
* 磁盘架的配对 NSM 模块必须已启动且正在运行，并且已正确布线，以便在卸下故障 NSM 模块时，磁盘架可以保持连接。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]

* 系统中的所有其他组件必须正常运行。


.关于此任务
* 更换 NSM 模块需要将 DIMM ，风扇和电源从受损的 NSM 模块移至更换的 NSM 模块。
+
您不会移动实时时钟（ Real-time Clock ， RTC ）电池或启动介质。它们预装在替代 NSM 模块中。

* 在拆卸和安装 NVMe 磁盘架模块（ NSM ）之间至少留出 70 秒。
+
这样， ONTAP 就有足够的时间来处理 NSM 删除事件。

* * 最佳实践： * 最佳实践是，在更换 FRU 组件之前，应在系统上安装最新版本的 NVMe 磁盘架模块（ NSM ）固件和驱动器固件。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["NetApp 下载：磁盘架固件"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["NetApp 下载：磁盘驱动器固件"^]

+
[NOTE]
====
请勿将固件还原到不支持您的磁盘架及其组件的版本。

====
* 在固件版本不是最新的新 NSM 模块上，磁盘架（ NSM ）固件会自动更新（无中断）。
+
NSM 模块固件每 10 分钟检查一次。NSM 模块固件更新最多可能需要 30 分钟。

* 如果需要，您可以打开磁盘架的位置（蓝色） LED ，以帮助以物理方式定位受影响的磁盘架： `storage shelf location-led modify -shelf-name _shelf_name_ -led-status on`
+
如果您不知道受影响磁盘架的 `shelf_name` ，请运行 `storage shelf show` 命令。

+
一个磁盘架具有三个位置 LED ：一个位于操作员显示面板上，一个位于每个 NSM 模块上。定位 LED 保持亮起 30 分钟。您可以通过输入相同的命令，但使用 `off` 选项将其关闭。

* 拆开备用 NSM 模块的包装时，请保存所有包装材料，以便在退回发生故障的 NSM 模块时使用。
+
If you need the RMA number or additional help with the replacement procedure, contact technical support at https://mysupport.netapp.com/site/global/dashboard["NetApp 支持"^], 888-463-8277 (North America), 00-800-44-638277 (Europe), or +800-800-80-800 (Asia/Pacific).

* 您可以使用以下视频或写入的步骤更换 NSM 模块。
+
.动画-更换NS224驱动器架中的NSM模块
video::f57693b3-b164-4014-a827-aa86002f4b34[panopto]


.步骤
. 正确接地。
. 以物理方式识别受损的 NSM 模块。
+
系统会向系统控制台记录一条警告消息，指示哪个模块受损。此外，驱动器架操作员显示面板和受损模块上的警示（琥珀色） LED 也会亮起。

. 断开受损 NSM 模块的布线：
+
.. 打开电源线固定器，断开电源线与电源的连接，然后从电源中拔下电源线。
+
电源没有电源开关。

.. 断开存储布线与 NSM 模块端口的连接。
+
记下每个缆线连接到的 NSM 模块端口。您可以将缆线重新连接到此更换用的操作步骤模块上的相同端口。



. 从磁盘架中卸下 NSM 模块：
+
.. 将索引指针绕过 NSM 模块两侧的锁定机制的指孔。
+

NOTE: 如果您要卸下底部 NSM 模块，并且底部导轨阻碍了对锁定机制的访问，请将索引指针从内部穿过指针孔（通过跨越臂）。

.. 用拇指按住锁定机制顶部的橙色卡舌。
+
闩锁机制将抬起，以清除磁盘架上的闩锁销。

.. 轻轻地将 NSM 模块拉出磁盘架，直到大约三分之一的位置，用双手抓住 NSM 模块的两侧以支撑其重量，然后将其放在平稳的表面上。
+
开始拉动时，锁定装置臂从 NSM 模块伸出并锁定在完全展开的位置。



. 拆开备用 NSM 模块的包装，并将其放在受损 NSM 模块附近的水平表面上。
. 松开受损 NSM 模块和更换用 NSM 模块上的翼形螺钉，打开受损 NSM 模块的外盖。
+

NOTE: NSM 模块盖上的 FRU 标签显示了 DIMM 和风扇的位置。

. 将 DIMM 从受损的 NSM 模块移至更换的 NSM 模块。
+
.. 记下插槽中 DIMM 的方向，以便可以使用相同的方向将 DIMM 插入更换用的 NSM 模块。
.. 缓慢地将 DIMM 插槽两端的弹出卡舌推离插槽，然后将 DIMM 从插槽中提出，从而从插槽中弹出 DIMM 。
+

NOTE: 小心握住 DIMM 的边角或边缘，以避免对 DIMM 电路板组件施加压力。弹出器凸耳保持打开位置。

.. 拿住 DIMM 的边角，然后将 DIMM 垂直插入更换用的 NSM 模块上的插槽。
+
DIMM 底部插脚之间的槽口应与插槽中的卡舌对齐。

+
正确插入后， DIMM 应轻松插入，但应紧紧插入插槽中。如果没有，请重新插入 DIMM 。

.. 小心而稳固地向下推 DIMM 的上边缘，直到弹出器卡舌卡入到位，卡入到位于 DIMM 两端的缺口上。
.. 对其余 DIMM 重复子步骤 7a 到 7d 。


. 将风扇从受损的 NSM 模块移至更换的 NSM 模块。
+
.. 从蓝色接触点所在的两侧牢牢抓住风扇，然后垂直提起风扇，将其从插槽中断开。
+
在将风扇提出之前，您可能需要来回轻缓地摇动风扇以断开其连接。

.. 将风扇与更换用的 NSM 模块中的导轨对齐，然后向下推，直到风扇模块连接器在插槽中完全就位。
.. 对其余风扇重复子步骤 8a 和 8b 。


. 合上每个 NSM 模块的外盖，然后拧紧每个翼形螺钉。
. 将电源从受损的 NSM 模块移至更换的 NSM 模块。
+
.. 将凸轮把手旋转到其打开（水平）位置，然后抓住它。
.. 用拇指按下蓝色卡舌以释放锁定机制。
.. 将电源从 NSM 模块中拉出，同时用另一只手支撑其重量。
.. 用双手支撑电源边缘并将其与更换用 NSM 模块的开口对齐。
.. 将电源轻轻推入 NSM 模块，直到锁定机制卡入到位。
+

NOTE: 请勿用力过大，否则可能会损坏内部连接器。

.. 将凸轮把手旋转到关闭位置。


. 将替代 NSM 模块插入磁盘架：
+
.. 确保锁定装置臂锁定在完全展开的位置。
.. 用双手将 NSM 模块轻轻滑入磁盘架，直到磁盘架完全支撑 NSM 模块的重量为止。
.. 将 NSM 模块推入磁盘架，直到其停止（距离磁盘架背面大约半英寸）。
+
您可以将拇指放在每个（锁定装置臂的）指环正面的橙色卡舌上，以推入 NSM 模块。

.. 将索引指针绕过 NSM 模块两侧的锁定机制的指孔。
+

NOTE: 如果您要插入底部 NSM 模块，并且底部导轨阻碍了对锁定机制的访问，请将索引指针从内部穿过指针孔（通过跨越臂）。

.. 用拇指按住锁定机制顶部的橙色卡舌。
.. 轻轻向前推，使闩锁超过停止位置。
.. 从锁定机制的顶部释放拇指，然后继续推动，直到锁定机制卡入到位。
+
NSM 模块应完全插入磁盘架并与磁盘架边缘平齐。



. 重新连接到 NSM 模块的布线：
+
.. 将存储布线重新连接到同一两个 NSM 模块端口。
+
插入缆线时，连接器拉片朝上。正确插入缆线后，它会卡入到位。

.. 将电源线重新连接到电源，然后使用电源线固定器固定电源线。
+
正常运行时，电源的双色 LED 将呈绿色亮起。

+
此外，两个 NSM 模块端口 LNK （绿色） LED 均会亮起。如果 LNK LED 不亮，请重新拔插缆线。



. 验证磁盘架操作员显示面板上的警示（琥珀色） LED 是否不再亮起。
+
NSM 模块重新启动后，操作员显示面板警示 LED 将熄灭。这可能需要三到五分钟。

. 运行 Active IQ Config Advisor ，验证 NSM 模块的布线是否正确。
+
如果生成任何布线错误，请按照提供的更正操作进行操作。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["NetApp 下载： Config Advisor"^]


