---
permalink: fas8300/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas8300, fas8700, shut, chassis, controller, replace, remove, swap, verify, install, power, supply, metrocluster, aggregates, replacement, process, equipment, rack, ha, state, system 
summary: 您必须验证机箱的 HA 状态，运行诊断并将故障部件退回给 NetApp ，如套件随附的 RMA 说明中所述。 
---
= 完成还原和更换过程— FAS8300 和 FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必须验证机箱的 HA 状态，运行诊断并将故障部件退回给 NetApp ，如套件随附的 RMA 说明中所述。



== 第 1 步：验证并设置机箱的 HA 状态

您必须验证机箱的 HA 状态，并在必要时更新此状态以匹配您的系统配置。

.步骤
. 在维护模式下，从任一控制器模块显示本地控制器模块和机箱的 HA 状态： `ha-config show`
+
所有组件的 HA 状态都应相同。

. 如果为机箱显示的系统状态与您的系统配置不匹配：
+
.. 设置机箱的 HA 状态： `ha-config modify chassis _ha-state_`
+
ha-state 的值可以是以下值之一：

+
*** `ha`
*** `mcc`
*** `mcc-2n`
*** `mCCIP`
*** `non-ha`


.. 确认设置已更改： `ha-config show`


. 如果尚未执行此操作，请重新对系统的其余部分进行布线。




== 第 2 步：运行诊断

更换系统中的某个组件后，您应对该组件运行诊断测试。

您的系统必须处于 LOADER 提示符处，才能启动诊断。

诊断过程中的所有命令都是从要更换组件的控制器发出的。

.步骤
. 如果要维护的控制器不在 LOADER 提示符处，请重新启动控制器： `ssystem node halt -node _node_name_`
+
问题描述命令后，您应等待系统停留在 LOADER 提示符处。

. 在 LOADER 提示符处，访问专为系统级诊断而设计的特殊驱动程序以正常运行： `boot_diags`
. 从显示的菜单中选择 * 扫描系统 * 以启用运行诊断测试。
. 从显示的菜单中选择 * 测试系统 * 以运行诊断测试。
. 从各种子菜单中选择一个或多个测试。
. 根据上一步的结果继续操作：
+
** 如果测试失败，请更正此故障，然后重新运行此测试。
** 如果测试未报告任何故障，请从菜单中选择重新启动以重新启动系统。






== 第 3 步：切回双节点 MetroCluster 配置中的聚合

在双节点 MetroCluster 配置中完成 FRU 更换后，您可以执行 MetroCluster 切回操作。这样会将配置恢复到其正常运行状态，以前受损站点上的 sync-source Storage Virtual Machine （ SVM ）现在处于活动状态，并从本地磁盘池提供数据。

此任务仅限适用场景双节点 MetroCluster 配置。

.步骤
. 验证所有节点是否处于 `enabled` 状态： `MetroCluster node show`
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. 验证所有 SVM 上的重新同步是否已完成： `MetroCluster SVM show`
. 验证修复操作正在执行的任何自动 LIF 迁移是否已成功完成： `MetroCluster check lif show`
. 在运行正常的集群中的任何节点上使用 `MetroCluster switchback` 命令执行切回。
. 验证切回操作是否已完成： `MetroCluster show`
+
当集群处于 `waiting for-switchback` 状态时，切回操作仍在运行：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
当集群处于 `normal` 状态时，切回操作完成。：

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
如果切回需要很长时间才能完成，您可以使用 `MetroCluster config-replication resync-status show` 命令检查正在进行的基线的状态。

. 重新建立任何 SnapMirror 或 SnapVault 配置。




== 第 4 步：完成更换过程

按照套件随附的 RMA 说明将故障部件退回 NetApp 。请参见 https://["部件退回和放大器；更换"] 第页，了解更多信息。
